### ISSUE TITLE
Add support for back-end access via HTTPS only

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#117]
[Forum discussion](http://cmsimpleforum.com/viewtopic.php?f=29&t=8727)

**Comment by cmb69** [comment]
Time flies, and nowadays it's considered to be best practice to use HTTPS throughout, so it doesn't appear to make sense to add an option to enforce HTTPS for the back-end only. Therefore I suggest to decline this feature request.

**Comment by Tata55** [comment]
I think that there are on som esevers necessary re-settings to use HTTPS and many CMSimple_XH users are not able to make them.
