### ISSUE TITLE
Replace TinyMCE 3 as default editor

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#123]
[Forum discussion](http://cmsimpleforum.com/viewtopic.php?f=29&t=8765)

**Comment by cmb69** [comment]
IMO we should switch to TinyMCE 4 or CKEditor – I don't mind which of these.

**Comment by manu37** [comment]
I vote for tinymce4, but only because I,m familiar with it. On the other hand ckeditor has powerful plugin extensions (often payware, but still..)

**Comment by TN03** [comment]
I'm fine with TinyMCE4 too

**Comment by cmb69** [comment]
So TinyMCE 4 it shall be. :)
