### ISSUE TITLE
Change page splitting to new XH-split way

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#162]
[Forum discussion](https://cmsimpleforum.com/viewtopic.php?f=16&t=11966)

[Available implementation](https://github.com/TN03/XH_split) (as modification of CMSimple_XH 1.6.7)

Note that this issue is only about the actual page splitting change, not about the default editor (#123), additional and/or new templates (#68), changing the default template, or the language menu/flags. The default editor and the language menu/flags are really a completely unrelated issue; the templates are not, but I suggest to decouple it nonetheless, to avoid a too complex discussion/voting.

**Comment by manu37** [comment]
👍. As solid converting tool is needed.
