### ISSUE TITLE
Introduce Icon-Font

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#168]
Icon-Fonts (opposed to classic single icon images) can save bandwidth and offer a homogenous look &feel, especially if used not only by the core but also by plugins and addons. Therefore I suggest to consider adding a general available icon font to the core.

**Comment by frase-git** [comment]
Fontawesome ist zwar ein bisschen "fett", hat aber zurzeit die größte Auswahl und wird weiterentwickelt.

**Comment by cmb69** [comment]
Die [900 Material-Icons](https://material.io/icons/) gibt es auch als Font; wäre auf jeden Fall eine denkbare Alternative.

Und "fett" sind die Fonts wohl immer, wenn entsprechend viele Glyphen zur Verfügung stehen. Könnte sich aber rechnen, wenn viele Plugins zumindest im Lauf der Zeit mitziehen.

**Comment by frase-git** [comment]
Mit den Material-Icons wäre ich auch sehr einverstanden.
Wollen wir abstimmen lassen? Oder erst im Forum diskutieren?

**Comment by cmb69** [comment]
Ich denke erst mal [im Forum diskutieren](https://cmsimpleforum.com/viewtopic.php?f=29&t=12584). Gerne auch auf deutsch. :)

**Comment by cmb69** [comment]
[frase suggested](https://cmsimpleforum.com/viewtopic.php?f=16&t=12587&p=58913#p58913) to add Fa_XH to the standard distribution, what would resolve this feature request.
