### ISSUE TITLE
filebrowser: attempt to delete a unempty directory

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#17]
Unknow error type [4096]: Argument 2 passed to Filebrowser\View::info() must be of the type array, string given, called in C:\xampp\htdocs\CMSimpleDev\plugins\filebrowser\classes\Controller.php on line 561 and defined
C:\xampp\htdocs\CMSimpleDev\plugins\filebrowser\classes\View.php:479

**Comment by cmb69** [comment]
Thanks. That's caused by the more strict typing in master: the second argument to Filebrowser\View::info() must now always be an array, but isn't in several occasions.

**Comment by cmb69** [comment]
I suggest to keep this fix.
