### ISSUE TITLE
Drop support for legal notices page

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#198]
See https://cmsimpleforum.com/viewtopic.php?f=29&t=12626.

**Comment by cmb69** [comment]
I suggest to merge PR #220.

**Comment by Tata55** [comment]
I am not sure about this. The legal requirements may change from country to country. In some countries such announcements are strictly required. Basically, the function creating this link automatically may be passed anytime. But - if somewhere really needed - a simple hidden page may be linked easily. So I would agree with dropping this off.

**Comment by cmb69** [comment]
To clarify: this is about http://www.cmsimple-xh.org/?CMSimple_Legal_Notices, but not http://www.cmsimple-xh.org/?Legal_Notices. While something like the latter may be legally required, the former is not (as the GPL doesn't require it).

**Comment by Tata55** [comment]
IC, anyway, present paranoia about all security and legal topics makes me crazy already. If people just knew what all is checked, controlled, manipulated etc. …

PaedDr. Martin Sereday
Štúrova 2
053 04 Spišské Podhradie
SLOVAKIA
+421 907 974 541
www.cmsimple.sk    |  Proroctvá hopiov
