### ISSUE TITLE
Flaggen werden nicht gefunden

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#199]
(aktueller Master 05.04.20117)
Hat man mehrere Sprachen angelegt und wechselt in eine Nicht-Standard-Sprache, wird in der Konsole 404 für die Flaggen gemeldet. Es wird (z.B. bei english) gesucht in: `/en/userfiles/images/flags/en.gif`.
Im Adminmodus NICHT.
Die Flaggen werden allerdings in jedem Fall korrekt angezeigt.

**Comment by cmb69** [comment]
Hm, das kann ich nicht reproduzieren. Handelt es sich bei diesem Problem vielleicht um eine Flagge in Content? content/content.htm enhält ja die dt. und engl. Flagge, 2lang/content/content.htm aber nicht. Wenn man aber den content/content.htm für die Zweitsprache nutzt, dann würden diese Flaggen nicht gefunden.

**Comment by lck-git** [comment]
> Hm, das kann ich nicht reproduzieren.
ich auch nicht. Getestet mit 4 Sprachen unter Xampp und neueste master Version. Aber vielleicht habe ich es auch nicht richtig verstanden, wann das genau auftritt.

>(aktueller Master 05.04.20117)
Jetzt ist alles klar, deswegen :smirk:

**Comment by frase-git** [comment]
**20117** Sehr schön. Das menschelt.

Also: Es gibt jetzt eine Online-Demo. (Link folgt in wenigen Minuten unter https://github.com/TN03/XH_split/issues/24)
Dort (online) tritt das Problem nicht auf.
Local unter xampp mit PHP 7.1.1 aber doch.

**Comment by lck-git** [comment]
> Local unter xampp mit PHP 7.1.1 aber doch.

Aha, hatte unter Xampp mit PHP 5.6.3 getestet.

**Comment by cmb69** [comment]
> Local unter xampp mit PHP 7.1.1 aber doch.

Hab's mir gerade aufgesetzt, und auch da kann ich das Problem nicht reproduzieren. Sind denn im Sprachmenü tatsächlich die `<img>` `source` Attribute falsch?

**Comment by frase-git** [comment]
> Sind denn im Sprachmenü tatsächlich die `<img>` source Attribute falsch?

Nein, sind sie nicht. Die Flaggen werden korrekt angezeigt.

![ff-flags](https://cloud.githubusercontent.com/assets/24246330/24710717/458b2a0c-1a1e-11e7-8ec6-49348a7f6f4e.png)

**Comment by cmb69** [comment]
> Nein, sind sie nicht. Die Flaggen werden korrekt angezeigt.

Dann such doch bitte mal im HTML-Quellcode, wo da die falschen srcs herkommen. 

Wenn ich mir den Screenshot anschaue, und meine Kristallkugel befrage, dann sagt sie mir, dass weiter unten auf dieser Seite ein Important Advice/Wichtiger Hinweis kommt, und links von diesen Texten Flaggen fehlen. Die stammen nämlich aus dem Default Content (content/content.htm) und der ist eben nicht für Zweitsprachen geeignet. Deshalb wird ja auch 2lang/content/content.htm ausgeliefert, der diese Flaggen nicht enthält.

**Comment by frase-git** [comment]
Aua, das tut weh.
Danke für den "wichtigen Hinweis".
Dieser ganze Wirbel, nur weil ich nicht gucken kann ...
Issue #199 - für die Katz.
Rrrrrrr, ich mach einfach nichts mehr. Da mach ich auch nichts mehr falsch. ;-)

**Comment by cmb69** [comment]
> Rrrrrrr, ich mach einfach nichts mehr.

Das muss ja nun auch nicht sein. Statt dessen lieber versuchen die Ruhe zu bewahren (gilt auch für mich) – ist ja wirklich kein Grund zur Panik. :)
