### ISSUE TITLE
Deprecate initvar()

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#201]
See https://cmsimpleforum.com/viewtopic.php?f=29&t=12630.

**Comment by cmb69** [comment]
I suggest to merge PR #221.

**Comment by manu37** [comment]
didnt' we already vote on this?

**Comment by cmb69** [comment]
> didnt' we already vote on this?

No. We voted on issue #21, which is somewhat related but not directly about `initvar()`.
