### ISSUE TITLE
Add API to access page name as plain text

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#203]
Page names as stored in `$h` are formatted as HTML (albeit all tags are stripped, characters may be entity escaped). At least sometimes plain text page names are required, so it would be nice to have an API to retrieve them, e.g. as suggested in https://cmsimpleforum.com/viewtopic.php?t=12602&p=59281#p59279 (even though I would prefer a respective method on XH_Pages).

**Comment by manu37** [comment]
Why not just illustrate, how the page names are stored in array $h? If somebody - by exception - needs to extract the page names in clean text he can do the html_entity_decode($h[$i]) by him/herself. Otherwise we have a function more to illustrate and maintain.

**Comment by manu37** [comment]
Well, after sleeping over it, the API gives us the choice to change the data format of $h without BC break. A good idea.

**Comment by cmb69** [comment]
Fixed with 4272f19.
