### ISSUE TITLE
Improve API for alternative adminmenus

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#205]
See https://cmsimpleforum.com/viewtopic.php?f=16&t=12512&start=140#p59417.

**Comment by frase-git** [comment]
Wäre sehr dafür.
Allerdings müsste ich wissen, welche Version - mit oder ohne FA?
Danach müsste ich noch version.nfo bauen, und den Download besser organisieren.

**Comment by cmb69** [comment]
Ich würde das für 1.7 eigentlich lieber nicht mehr berücksichtigen wollen – ist einfach schon viel zu viel anderes. Danach haben wir mehr Zeit.

**Comment by frase-git** [comment]
Ja, natürlich. Hatte ich nicht ausführlich geschrieben.

**Comment by TN03** [comment]
Das sollten wir nicht überstürzen. Eigentlich gefällt mir das 1.6 er Admin-Menü auch ganz gut. Auf jeden Fall würde ich für 1.7 da nicht weiter drüber nachdenken.
Ein Admin-Menü, zumal wenn es als Plugin vorliegt, lässt sich doch "simpel" nachinstallieren.
Außerdem finde ich, dass zuerst mal eine Art API ausgearbeitet werden müsste. Dazu fällt mir zum Beispiel die Update-Benachrichtigung und das hi_Admin-Plugin ein. Letzteres sollte bei allen Menüvarianten die Möglichkeit haben z.B. einzelne Menüpunkte einzufügen etc.

Und im Bezug zu FA: es macht mir Bauchschmerzen, dass wir uns dadurch von einem weiteren Fremdprojekt abhängig machen. Okay, FA ist etabliert und wird sich wohl noch länger halten. Aber die Sachen müssen auch alle auf Dauer gewartet werden (Stichwort Editor-Plugins etc.).

**Comment by lck-git** [comment]
> Das sollten wir nicht überstürzen. Eigentlich gefällt mir das 1.6 er Admin-Menü auch ganz gut. Auf jeden Fall würde ich für 1.7 da nicht weiter drüber nachdenken.
Ein Admin-Menü, zumal wenn es als Plugin vorliegt, lässt sich doch "simpel" nachinstallieren.

Dem stimme ich 100% zu.
Vielleicht liegt das an meiner geringen praktischen Erfahrung mit CMSimple_XH, aber ich bevorzuge das Standard-Adminmenü, weil man schnell Zugriff auf die Menüpunkte hat und es ist auch übersichtlich.
Wenn integrieren, dann sollte das alte Menü als Standard voreingestellt sein und das fhs_adminmenü als Option.

**Comment by cmb69** [comment]
> Und im Bezug zu FA: es macht mir Bauchschmerzen, dass wir uns dadurch von einem weiteren Fremdprojekt abhängig machen. Okay, FA ist etabliert und wird sich wohl noch länger halten. Aber die Sachen müssen auch alle auf Dauer gewartet werden (Stichwort Editor-Plugins etc.).

Das sind auch meine größten Bedenken. Und ja, die Editor-Plugins sind jetzt schon ein Problem. Das OS CKEditor-Plugin wird ja schon seit ein paar Jahren nicht mehr gepflegt, und beim TinyMCE 4 Plugin passiert wohl auch nicht mehr viel.

**Comment by frase-git** [comment]
Zur Reduzierung der offenen Issues empfehle ich: ablehnen und schließen ;-)
(muss ich meinen "Daumen hoch" von ganz oben entfernen?)

**Comment by cmb69** [comment]
> Zur Reduzierung der offenen Issues empfehle ich: ablehnen und schließen ;-)

Ich habe das Thema jetzt einfach geändert (Holger hat das [weiter oben angesprochen](https://github.com/cmsimple-xh/cmsimple-xh/issues/205#issuecomment-294760454)).

**Comment by frase-git** [comment]
Ein alternatives Adminmenü als Plugin ist ja jetzt jederzeit möglich.
fhs-adminmenu liegt als Plugin vor und jeder kann selbst entscheiden ob er es will oder nicht.
Ich denke, wir können dieses Issue bedenkenlos schließen - und tue es auch gleich ;-)
