### ISSUE TITLE
tinymce4: CDN or full version?

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#206]
Generally two versions are provided: one with full tinymce JS library, one CDN Version without local JS library (but with langs). My proposition is to deliver the CDN Version by default. And put into the Dist documentation a hint where to download the full fledged version. 
Any opinions?

**Comment by frase-git** [comment]
Ich bevorzuge die full-Version (local).
Zum einen, weil ich oft offline entwickle.
Zum anderen, weil die CDN auch schon mal unregelmäßig erreichbar sein kann (auch schon war).
Sorry.

**Comment by cmb69** [comment]
> Zum einen, weil ich oft offline entwickle.

That's a good argument; on the other hand, the CDN only version is supposed to be much smaller (BTW: the downloads on https://sourceforge.net/projects/tinymce4cmsimplexh/files/?source=navbar have equal size).

> Zum anderen, weil die CDN auch schon mal unregelmäßig erreichbar sein kann (auch schon war).

That would be bad.

Anyhow, is it a good idea to use cdn.tinymce.com/4/tinymce.min.js as default? Is relying on the major version number only stable enough, i.e. are they strictly following semver?

**Comment by manu37** [comment]
> (BTW: the downloads on https://sourceforge.net/projects/tinymce4cmsimplexh/files/?source=navbar have equal size). This is a mistake. The CDN Variant should be 1,1MB & 108 files lighter.
> Anyhow, is it a good idea to use cdn.tinymce.com/4/tinymce.min.js as default?
Everytime I visit the tinymce site, there is another way to link the CDN Version..

**Comment by manu37** [comment]
As I read the notice about [tinyMCE Cloud deployment](https://www.tinymce.com/docs/get-started-cloud/editor-and-features/), we better stick to the local variant. As a next step I might make the Cloud Access configurable. Register for an API key is then a matter of the user.

**Comment by cmb69** [comment]
> This is a mistake. The CDN Variant should be 1,1MB & 108 files lighter.

Ah, thanks. This makes, of course, quite a difference.

> As I read the notice about tinyMCE Cloud deployment, we better stick to the local variant.

We might also use https://cdnjs.com/libraries/tinymce, instead.

**Comment by lck-git** [comment]
> [frase-git]Ich bevorzuge die full-Version (local).
Zum einen, weil ich oft offline entwickle.

Ich auch!
Problem: bei voreingestellter CDN-Version und ohne Internetverbindung, der Editor erscheint nicht und es gibt auch keinen Hinweis darauf, dass eine aktive Interverbindung notwendig ist :(

**Comment by cmb69** [comment]
> Problem: bei voreingestellter CDN-Version und ohne Internetverbindung, der Editor erscheint nicht und es gibt auch keinen Hinweis darauf, dass eine aktive Interverbindung notwendig ist :(

Das ist nicht schön, könnte aber relativ leicht gelöst werden, in etwa:
````
if (!tinymce) {
    alert("TinyMCE couldn't be loaded. Are you offline?");
}
````

**Comment by manu37** [comment]
> We might also use https://cdnjs.com/libraries/tinymce, instead.

Nice. This is already configurable in the plugins "alternate CDN Source". 
I think I stay with the two plugin versions and we all decide which variant will be implemented by default.

**Comment by cmb69** [comment]
> I think I stay with the two plugin versions and we all decide which variant will be implemented by default.

I don't mind which variant will be the default – there are good arguments pro and con.

**Comment by manu37** [comment]
Honestly, in regard of the package size (saves 0,5MB) and the fact that the majority works online I would suggest to roll out the CDN Version. The host  https://cdnjs.com/libraries/tinymce is quite up to date. Its easy to illustrate how to install tinyMCE manually and switch to the local variant.

**Comment by manu37** [comment]
I'm working on it. The update is the least, a proper documentation is the effort..

**Comment by cmb69** [comment]
Since PR #264 has been closed, this ticket can be closed as well.
