### ISSUE TITLE
filebrowser deletes files linked in unpublished pages

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#207]
Is there a way to get content $c with unpublished pages included?
Filebrowser offers files/images to delete which are linked in unpublished pages.

**Comment by cmb69** [comment]
> Is there a way to get content $c with unpublished pages included?

That would require to [run the filebrowser in `$edit` mode](https://github.com/cmsimple-xh/cmsimple-xh/blob/50e416ee9554a1c110442d72df817752b5cb86ba/cmsimple/adminfuncs.php#L601), what doesn't appear to introduce other issues.

**Comment by manu37** [comment]
Indeed! Is it that simple? Then let's do it.

**Comment by cmb69** [comment]
> Is it that simple? Then let's do it.

I'm not sure if there won't be issues regarding external filebrowsers, but we can use 1.7.0beta1 to find that out. If this solution works, I suggest to apply the fix to XH 1.6.10, too.

**Comment by cmb69** [comment]
I suggest to apply the respective fix (commit 6393967) to 1.6.10.

**Comment by cmb69** [comment]
Fixed in cb10db5.
