### ISSUE TITLE
Objects are destroyed before XH_finalCleanUp() is called

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#211]
See https://cmsimpleforum.com/viewtopic.php?f=16&t=12669&start=20#p59590.

**Comment by cmb69** [comment]
It seems that the modification posted in https://cmsimpleforum.com/viewtopic.php?f=16&t=12669&p=59594#p59594 would solve the issue (not sure about all implications, though). Anyhow, if we'd do that, we could get rid of XH_CWD as well.

@TN03 Can you please check whether that change would affect the minification routine?

**Comment by TN03** [comment]
> @TN03 Can you please check whether that change would affect the minification routine?

See here:
https://cmsimpleforum.com/viewtopic.php?f=16&t=12669&p=59611#p59611

**Comment by cmb69** [comment]
I suggest to merge PR #222.
