### ISSUE TITLE
TinyMCE 4: missing headings in block_formats

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#214]
If a site has a maximum nesting level of less than 6, some headings are not listed in `block_formats`. See https://cmsimpleforum.com/viewtopic.php?f=16&t=12669&start=90#p59716 for a possible solution.

**Comment by cmb69** [comment]
I suggest to stick to the fix which has already been committed.

**Comment by manu37** [comment]
Is this not a bit overkill? Since the headers arent used for page building anymore, why not just hardcode them in the init files? Ok, for BC reasons just iterate h1-h6. What is `%NAMED_PAGEHEADERS%` for? I don't find it in the _init.js files.

**Comment by cmb69** [comment]
> Is this not a bit overkill?

Yes, it is. :) Of course, hard-coding the headers in the inits is sufficient for XH 1.7, but not for XH 1.6. Not sure if you prefer to have separate versions of TinyMCE for XH 1.6 and 1.7.

**Comment by manu37** [comment]
> Not sure if you prefer to have separate versions of TinyMCE for XH 1.6 and 1.7.

Sure not, good point. So let's state: `%PAGEHEADERS%` and `%NAMED_PAGEHEADERS%` are obsolete from v1.7?

**Comment by cmb69** [comment]
> So let's state: `%PAGEHEADERS%` and `%NAMED_PAGEHEADERS%` are obsolete from v1.7?

Sounds good!
