### ISSUE TITLE
Don't logout after password change

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#225]
IMO it doesn't make sense to log out admins after they've changed their password. While this may be considered a nice confirmation, why not simply keep them logged in and report that the password has been changed?

See also https://cmsimpleforum.com/viewtopic.php?f=16&t=12694#p59901.

**Comment by cmb69** [comment]
I suggest to merge PR #225.

**Comment by manu37** [comment]
I would suggest to force a logout after a password change. 
Why: For all my passwords I use a password manager (which I recommend everybody). Since the password change doesn't happen on the same address/form my password manager doesn't update the formerly changed password. On a new login the pw manager recognizes a pw change.

**Comment by frase-git** [comment]
Mir scheint ein Logout nach einem PW-Wechsel auch logischer.
Ein neues anschließendes Login dient dann zur Überprüfung (wenn auch zu spät  :unamused:)

**Comment by cmb69** [comment]
> Mir scheint ein Logout nach einem PW-Wechsel auch logischer.

Ist das bei anderer Software auch der Fall?

**Comment by frase-git** [comment]
> Ist das bei anderer Software auch der Fall?

Weiß nicht. Da ich exklusiver Nutzer meiner Software (und Geräte) bin, muss ich nur selten Passwörter eintippen.

Vom Ablauf her: Ich habe mich mit einem PW eingeloggt - ändere - was ist jetzt gültig?
Geht das alte noch? Bekomme ich eine Fehlermeldung beim nächsten Speichern?
Ich hatte mich bei XH gerade auf dieses Verhalten "eingeschossen".

**Comment by cmb69** [comment]
> Vom Ablauf her: Ich habe mich mit einem PW eingeloggt - ändere - was ist jetzt gültig?

Nach dem Sichern des geänderten Passworts sieht es so aus:

![change-password](https://cloud.githubusercontent.com/assets/2306138/25862284/d420fff6-34e7-11e7-9f97-493ef2519018.png)

Die Message muss noch internationalisiert werden, aber da sollte doch alles klar sein, oder?

**Comment by frase-git** [comment]
Keine lange Diskussion. Ich komme in jedem Fall damit klar, egal, wie es kommt ...
Nach Manus Argumenten habe ich nur noch ein Bauchgefühl geäußert.
Sicherheits- oder programmiertechnisch ist es nicht relevant.

**Comment by cmb69** [comment]
Hm, that appears to be too controversial, and if in doubt being conservative might be best, so I'm closing as WONTFIX.
