### ISSUE TITLE
Print View

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#24]
[Forum discussion](http://cmsimpleforum.com/viewtopic.php?f=29&t=5344)

cmb: optionally print newsboxes only (nofollow is handled by separate roadmap item)

PS: to clarify: this is about adding a second optional parameter to newsbox, which if set to true, would also emit a link to print the contents of the newsbox only.

**Comment by cmb69** [comment]
I still think this is useful, but the details may warrant some further discussion, and we're short of time, and the feature can easily be offered by a plugin or addon, so I suggest to postpone the decision to a later version.

**Comment by olape-git** [comment]
https://github.com/olape-git/cmsimple-xh/commit/e298c420792139c60f31140e47e304ffc53fae9d
