### ISSUE TITLE
Clean urls

### ISSUE THREAD

**Issue by gvoxcms** [cmsimple-xh/cmsimple-xh#240]
There are still these awsome .&..&  urls which most other systems do not have - the web is stylish and 
cool - these urls are not

**Comment by cmb69** [comment]
Yes, I fully agree, but there is no easy solution regarding plugins. Anyhow, this is a duplicate of #41.

**Comment by gvoxcms** [comment]
Also a chache plugin would be useful which is common in higher class cmssses . 

There are plugins in github which allow to cache single html-files and others.

The site is then more fluently without long pauses
