### ISSUE TITLE
lange Urls

### ISSUE THREAD

**Issue by gvoxcms** [cmsimple-xh/cmsimple-xh#246]
Abgesehen davon dass die neue Oberfläche zwar in Insiderkreisen cool ist, was nicht jedermanns Geschmack ist - man sollte mal eine alternative Adminskin entwickeln - evtl. zur Auswahl mit Bootstrap o.ä. - momentan
hängt die Adminskin vom Template  ab - das ist wohl eher ein Fehler der in 1.69 nicht vorhanden war.

Die Urls gehen ja jetzt bis auf das Fragezeichen - warum letzteres ?
Es gibt noch eine Alternative mit Short url, das es auch für Dokuwiki gibt. 
Untiges Plugin dürfte leicht für Cmsimple anzupassen sein. Typesetter hat auch kurze Urls fest eingebaut
https://dev4me.com/modules-snippets/opensource/shorturl/#

**Comment by cmb69** [comment]
> hängt die Adminskin vom Template ab - das ist wohl eher ein Fehler der in 1.69 nicht vorhanden war.

Bei CMSimple(_XH) wird die Administrationsoberfläche traditionell im gleichen Template angezeigt, wie auch das Front-End der Website. Daran hat sich bei CMSimple_XH 1.7 eigentlich nichts geändert (nur wird nun das Template-Stylesheet ganz am Ende, also nach den Pluginstylsheets, geladen). Es gibt aber das [hi_admin Plugin](https://cmsimpleforum.com/viewtopic.php?f=16&t=7730) mit dem man für die Administration ein anderes Template verwenden kann.

> Die Urls gehen ja jetzt bis auf das Fragezeichen - warum letzteres ?

"Clean URLs" stehen schon lange auf der Roadmap (siehe #41) wurden aber noch nicht umgesetzt, vor allem weil nur wenige Plugins solche URLs erzeugen würden.
