### ISSUE TITLE
Adminmenü

### ISSUE THREAD

**Issue by ghost** [cmsimple-xh/cmsimple-xh#262]
Ich möchte den Vorschlag machen, nachdem das Adminmenu von 1.7 rc1 mit dem Template zerfliesst, 
doch in eines der beiden Csse so etwas wie pure.css(4 Kb) oder mui.css einzubinden(So nobel wie man heute zu sein vorgibt).  Dann stünde auch im ganzen CMS und auch auf den Hilfeseiten eine Minimalklasse  zur Verfügung.
Man könnte auch zusätzlich zwischen 3 Formatierungen umschalten per CMS-Einstellungs-Menü.

**Comment by TN03** [comment]
@gvoxcms : den Request verstehe ich jetzt nicht.

> nachdem das Adminmenu von 1.7 rc1 mit dem Template zerfliesst

Um was für ein Problem geht es denn da?

BTW: pure.css ist in der Zwischenzeit aufgegeben worden, wird also nicht mehr von Yahoo betreut. Eine Übernahme des Projekts durch Kräfte aus der Community ist derzeit auch nicht in Sicht. Schade eigentlich.

**Comment by gvoxcms** [comment]
https://purecss.io/**** lebt und wird entwickelt - es gibt auch andere

Im 1.7 rc1 fliessen die Layouts und das Adminmenu (Hintergrund) ineinander (Firefox 53) - ganz abgesehn von den Templates, die nicht so ganz attraktiv sind. Falls die RC nicht vor September herauskommt werde ich ein paar moderne entwicklen.
Ein Adminmenü könnte man mit blau-weiss und schwarz über einen einfachen CSS-switch umschalten.

**Comment by cmb69** [comment]
> Im 1.7 rc1 fliessen die Layouts und das Adminmenu (Hintergrund) ineinander (Firefox 53)

Das wäre definitiv ein Bug, denn am Adminmenü sollte sich vom Aussehen gegenüber XH 1.6 eigentlich nichts geändert haben. Ein Screenshot oder besser eine Demo-/Test-Installation, in der dieser Fehler auftritt, wären fürs Debuggen hilfreich.

> […] ganz abgesehn von den Templates, die nicht so ganz attraktiv sind.

Ich denke, das ist immer auch Geschmackssache. Auf jeden Fall sind die ausgelieferten Templates ja nur Beispiele, und Anwender können sich ja leicht ein anderes Template installieren. :)

**Comment by frase-git** [comment]
@gvoxcms
zu Adminmenü: Schon probiert -> "fhs_adminmenu-without-fa"
https://cmsimpleforum.com/viewtopic.php?f=16&t=12512&start=130#p59213

**Comment by gvoxcms** [comment]
Mit dem Selbststricken von Templates ist das so eine Sache : Die meisten User sehen ein CMS und prüfen es auf leichte Administrierbarkeit, Sicherheit  und vorhandene Templates, denn beim Selbstbasteln kommt zwar etwas raus, aber zumeist nichts Elegantes und damit wenig Präsentatives - das haben Wordpress und Joomla verstanden verstanden !

**Comment by cmb69** [comment]
> Das Adminmenu verschwimmt nicht sondern hat wenig Kontrast zum Template. Das könnte man verbessern. Jemand sollte mal ein alternatives Menü mit Mui-css entwerfen.

Ah, verstehe! Zumindest dafür braucht es IMO aber kein CSS-Framework, sondern man sollte einfach die überflüssigen Definitionen entfernen (z.B. wird `background-color: #2e3436` sowohl für [`#xh_adminmenu`](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.0rc1/assets/css/core.css#L19), [`#xh_adminmenu ul`](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.0rc1/assets/css/core.css#L36) als auch für [`#xh_adminmenu li`](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.0rc1/assets/css/core.css#L44) definiert, obgleich sich `background-color` vererbt). Danach sollte es sehr einfach sein, die Hintergrund- und Vordergrundfarbe des Adminmenüs nach Wunsch anzupassen. 

Ich finde abe schonr, dass die Voreinstellung auch mit einem dunklem Template wie lck_overlay_02 recht gut passt.

**Comment by gvoxcms** [comment]
Ich würde das Adminmenu irgendwie über eine css-Box abheben.

**Comment by cmb69** [comment]
> Ich würde das Adminmenu irgendwie über eine css-Box abheben.

Ich weiß nicht genau was du meinst, aber wenn du `box-shadow` oder ähnliches im Sinn hast, bin ich nicht grundsätzlich dagegen, aber es wäre gut, wenn das jemand mal konkret ausarbeitet. Im allgemeinen bin ich allerdings der Meinung, dass das Standard-Adminmenü möglichst einfach und platzsparend gehalten werden sollte.

**Comment by frase-git** [comment]
@gvoxcms 

> Zum "fhs_adminmenu-without-fa" rechts. Es ist etwas schmal und die Farben sind etwas reichlich bunt. Es hat allerdings Potentiale.

In der Pluginkonfiguration kannst du hell oder dunkel und auch Die Breite einstellen.
Wenn es dir zu bunt ist: Im Plugin-CSS-Ordner liegen die beiden Dateien zum Ändern.

**Comment by cmb69** [comment]
Gibt's hier nun **konkret** was zu verbessern? Ansonsten sollte das Ticket geschlossen werden.

**Comment by TN03** [comment]
> Gibt's hier nun konkret was zu verbessern?

Ich wüsste jetzt nicht was.

**Comment by cmb69** [comment]
Dann schließe ich das Ticket.
