### ISSUE TITLE
Help-Folder in Rootdirectory

### ISSUE THREAD

**Issue by TN03** [cmsimple-xh/cmsimple-xh#266]
It seems to me that the help-folder at this position https://github.com/cmsimple-xh/cmsimple-xh/tree/1.7.0/help is incorrect.

**Comment by TN03** [comment]
Ups: Release already out https://github.com/cmsimple-xh/cmsimple-xh/releases/tag/1.7.0 :( .
So the full- and the update-ZIP contain this additional Folder.

**Comment by cmb69** [comment]
Indeed, this help/ folder isn't supposed to be there. @manu37 can you please have a look at this.

And yes, the help/ folder is contained in 1.7.0, but that's not a real issue, I think. No need to push out 1.7.1 right away.

**Comment by TN03** [comment]
> No need to push out 1.7.1 right away.

Of course not.

**Comment by manu37** [comment]
No idea how this went there. Is there a way to delete it online? I don't have an actual working directory. Otherwise I'll do it on late monday.

**Comment by cmb69** [comment]
> Is there a way to delete it online? I don't have an actual working directory. 

Never mind; I'm at it anyway, so I'm going to remove the folder. :)
