### ISSUE TITLE
Add config type for numbers

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#269]
This would simply map to `<input type="number">` and should at least allow to specify the `step` value (otherwise it could be used for integers only) ; maybe also `min` and `max` should be supported.

**Comment by frase-git** [comment]
> maybe also min and max should be supported.
Unbedingt.

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/issues/396
