### ISSUE TITLE
tinyMCE: Toolbar Configuration in Back-End

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#27]
[Forum discussion](http://cmsimpleforum.com/viewtopic.php?f=29&t=5584)

**Comment by cmb69** [comment]
Besides that TinyMCE is most likely going to be replaced by a contemporary editor, I don't think there's enough time to resolve this for 1.7, so I suggest to postpone to 1.8.

**Comment by manu37** [comment]
I suggest to discard this feature request. Developement & maintaince & spending help to misleaded configs is immense in regard of the effort we have. Somone who has fun has the possibility to write a plugin.
