### ISSUE TITLE
Empty path segments in an URL

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#282]
This is about URLs such as `http://example.com///?Page`. It seems that servers interpret that as `http://example.com/?Page`, even though it appears that RFC 3986 doesn't specify in which way such URIs should be resolved.

Anyhow, this can lead to problems with second languages. Consider someone requests `http://example.com/de//?Page`. In this case CMSimple_XH will deliver the desired page contents, but most (if not all) URLs to assets are broken, e.g. `../assets/css/xhstyles.css` will look for `http://example.com/de/assets/css/xhstyles.css` which does not exist.

I'm not sure if we should handle such cases, or whether we should regard this as Webserver issue, which we ignore. Note that Wikipedia claims that folding multiple adjacent slashes in the path is a normalization that [changes semantics](https://en.wikipedia.org/wiki/URL_normalization#Normalizations_that_change_semantics).

**Comment by gtbu** [comment]
Another solution would be to solve this with 'short'urls.

**Comment by cmb69** [comment]
> Another solution would be to solve this with 'short'urls.

I fail to see how this would affect the URL path.

**Comment by cmb69** [comment]
I suggest to close this as WONTFIX.

**Comment by olape-git** [comment]
/cmsimple/cms.php
nach rfc(); // Here content is loaded

`// remove Empty path segments in an URL - https://github.com/cmsimple-xh/cmsimple-xh/issues/282
function XH_remove_empty_path() {
	$url_parts = parse_url(CMSIMPLE_URL);
	$url_scheme = $url_parts['scheme'];
	$url_host = $url_parts['host'];
	$url_path = $url_parts['path'];
	$url_query_str = $_SERVER['QUERY_STRING'];
	$prre_count = 0;

	$url_path = preg_replace('#(/){2,}#s', '/', $url_path, -1, $prre_count);

	if($prre_count > 0) {
		$url_tmp = $url_scheme . '://' . $url_host . $url_path . (($url_query_str != '') ? ('?' . $url_query_str) : (''));
		header("Location: $url_tmp", true, 302);
		exit;
	}
}
XH_remove_empty_path();`

**Comment by olape-git** [comment]
#401
https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/7bfa1e04dad1b702b2e6998ff3213cc5888bed05

**Comment by manu37** [comment]
#417
