### ISSUE TITLE
Mailform should use fixed From address

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#283]
The built-in mailform sends the email using the visitor's address as `From`. This does not necessarily work on shared hosting services, because these may require to whitelist allowed `From` adresses for spam prevention. Therefore it appears to be preferable to use `$cf['mailform']['email']` as `From` address, and to set the visitor's email address as `Reply-To`.

See also https://cmsimpleforum.com/viewtopic.php?f=16&t=12998.

**Comment by cmb69** [comment]
I suggest to treat this issue as bug, and to merge PR #317 into XH 1.7.2

**Comment by olape-git** [comment]
/cmsimple/classes/Mailform.php
Zeile 160
`          $this->mail->addHeader('From', $this->sender);`
zu
`        $this->mail->addHeader('From', $cf['mailform']['email']);`
`        $this->mail->addHeader('Reply-To', $this->sender);`

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/pull/392/commits/60aace411604ef6b6dd2e88457ad428bb61bdb27

**Comment by TN03** [comment]
@olape-git Das Issue ist geschlossen, aber ich finde weder einen Commit noch einen Pullrequest -- weder im 1.7er, noch im Master-Branch

**Comment by olape-git** [comment]
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/cfa03f8f6f9574c9f1086c2eabc72385b86af560

**Comment by manu37** [comment]
60aace4
