### ISSUE TITLE
Remove prev/next <link>s

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#285]
CMSimple traditionally emits `<link>` elements in the `<head>` which refer to the previous and the next page. This concept doesn't necessarily apply to any CMSimple_XH website, however. Even worse, such prev/next links could be more reasonable used by plugins which use some kind of pagination (lb_Gallery, Forum_XH, Calendar_XH). See also https://support.google.com/webmasters/answer/1663744?hl=en, which states:

> Use rel="next" and rel="prev" links to indicate the relationship between component URLs. This markup provides a strong hint to Google that you would like us to treat these pages as a logical sequence, thus consolidating their linking properties and usually sending searchers to the first page.

Therefore I suggest to drop the prev/next `<link>` elements in the `<head>` or to make them configurable.

**Comment by cmb69** [comment]
But see <https://cmsimpleforum.com/viewtopic.php?f=13&t=14271>. For such use cases the head-links make sense (perhaps make that configurable?)

**Comment by olape-git** [comment]
If it's to be kept in, then configurable. For plugins like Realblog these links are wrong. Here Realblog should create, if, then even some.

**Comment by frase-git** [comment]
> If it's to be kept in, then configurable.

I agree with that. Standard should be "off".
