### ISSUE TITLE
login page: "back" link

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#290]
Aufruf händisch: `... /index.php?login`
Kein Passwort eintragen, sondern auf "Back" klicken ->
Man landet immer wieder auf der Login-Seite.

**Comment by cmb69** [comment]
Indeed. While `/?&login` works as expected, `/?login` does not. Simply [using `$su`](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.0/cmsimple/functions.php#L1584) is obviously insufficent in this case.

**Comment by cmb69** [comment]
Fixed in c525742.
