### ISSUE TITLE
Improve handling of errors in template.htm

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#298]
See also the [related forum discussion](https://cmsimpleforum.com/viewtopic.php?f=16&t=13030).

Severe errors (such as calling an undefined function or even syntax errors) in `template.htm` cause an immediate shutdown of the script, giving some kind of error message depending on the debug mode, which can easily be overlooked, especially if the error happens late in the template. This is a problem, since we allow to edit the template in the back-end, but if the admins screw up, they might not be able to fix the error without resorting to FTP. There has been the idea to check the template on form submission, and to reject the changes if they would cause such an error. However, we never managed to integrate this.

Anyhow, the situation has changed as of PHP 7.0.0 where it is possible to catch many of these errors, so I suggest to make use of this feature. Of course, that wouldn't be an improvement for users who are still on PHP 5, but IMO we should look forward, particularly since catching these errors wouldn't even require special casing (PHP 5 vs. 7).

A rough outline of what might be done:
````diff
 cmsimple/cms.php | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/cmsimple/cms.php b/cmsimple/cms.php
index 2c2ba46e..91480f00 100644
--- a/cmsimple/cms.php
+++ b/cmsimple/cms.php
@@ -1340,7 +1340,12 @@ $i = false;
 $temp = fopen($pth['file']['template'], 'r');
 if ($temp) {
     if (XH_lockFile($temp, LOCK_SH)) {
-        $i = include $pth['file']['template'];
+        try {
+            $i = include $pth['file']['template'];
+        } catch (Error $ex) {
+            // take some action
+            $i = true; // to avoid loading the emergency template later
+        }
         XH_lockFile($temp, LOCK_UN);
     }
     fclose($temp);
````
Especially the "take some action" comment would have to be replaced (with what?), and maybe we should not only catch `Error`s but generally `Throwable`s.

Thoughts?

**Comment by olape-git** [comment]
> ```diff
> +            // take some action
> +            $i = true; // to avoid loading the emergency template later
> ```

            $o .= '<div style="border: 2px solid #ff0000; margin: 20px; padding: 10px;">'
                . 'Error-Message: ' . $ex->getMessage() . '<br>' . PHP_EOL
                . 'File: ' . $ex->getFile() . '<br>' . PHP_EOL
                . 'Line: ' . $ex->getLine() . PHP_EOL
                . '</div>';
