### ISSUE TITLE
Remove Site/CMS Info

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#315]
The implicit page "CMS/Site Info" which has been introduced in CMSimple_XH 1.7.0 might not have been the best idea, since it gives rather detailed information regarding which software (CMS, plugins, templates) is installed for anybody requesting this page. This might be regarded as information leakage.

Note that the closely related issue #7 has been accepted, and consequently we should handle CMS/Site Info accordingly. Since it would defy the purpose of the page to only show it if debug mode is enabled, we should consider to remove it altogether. This would render #304 obsolete.

**Comment by cmb69** [comment]
I suggest to merge #319.

**Comment by olape-git** [comment]
Weiß denn jemand, warum hier die Tests fehlschlagen?

https://github.com/cmsimple-xh/cmsimple-xh/pull/319

**Comment by manu37** [comment]
Eigentlich sollten die Tests jetzt laufen. Können wiederholt werden.

**Comment by cmb69** [comment]
Mergekonflikte gelöst; CI ist grün. :)
