### ISSUE TITLE
typo in de.php

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#322]
`$tx['help']['meta_robots']="Standarteinstellung für alle Seiten. \"index,follow\" weist Suchroboter an, die Seite in den Suchindex aufzunehmen und allen Links zu folgen. \"noindex,nofollow\" weist das Gegenteil an.";`

Ein Ding, was auch mir ab und zu passiert: `Standard`einstellungen !

**Comment by cmb69** [comment]
Wow! Das ist wohl in über 4 Jahren niemandem aufgefallen.
