### ISSUE TITLE
Add reqcheck.php script

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#325]
See https://cmsimpleforum.com/viewtopic.php?f=29&t=6015.

**Comment by manu37** [comment]
no bug, feature -> 1.8. The script could be posted in the forum.

**Comment by frase-git** [comment]
Eine neue reqcheck.php ist [hier verfügbar](https://cmsimpleforum.com/viewtopic.php?f=29&t=6015#p70640).
Wenn diese Datei mit ausgeliefert wird, sollten auch die README-Dateien aktualisiert werden, die u.a. eine Erklärung dazu enthalten.
Die neuen README-Dateien (nur EN und DE) sind [hier einzusehen](http://fhs.bplaced.net/cmsxh-distro-173/?Download). Wenn weitere Übersetzungen vorliegen, könnten diese in 1.8 eingefügt werden.
Bitte abstimmen, ob die reqcheck.php und die beiden README-Dateien so wie hier beschrieben in XH Version 1.7.3 enthaltensein sollen.

**Comment by cmb69** [comment]
Ah, sehr schön! Das `get_magic_quotes_runtime()` sollte bzgl. PHP 7.4 noch abgesichert werden, so wie in #423 (`(float)` cast geht natürlich auch).

**Comment by manu37** [comment]
Du hast/Ihr habt Euch wohl schon überlegt ob die XH_systemCheck() Funktion eingebunden werden könnte? Dann müssten die zwei Systemanforderungskataloge nicht separat gepflegt werden.
Dran denken: Beim build muss die @CMSIMPLE_XH_VERSION@ eingebunden werden.

**Comment by cmb69** [comment]
reqcheck.php muss minimalistisch bleiben, damit es nicht schon Dinge benötigt, auf die es eigentlich erst testen soll. Daher wird man dort `XH_systemCheck()` nicht verwenden können, da es zumindest Teile des CMSimple_XH "Frameworks" verwendet. Was vielleicht möglich wäre, wäre die relevanten Prüfungen als Daten (im weitesten Sinn) sowohl von reqcheck.php als auch `XH_systemCheck()` zu verwenden. Aber zur Not (sprich, aus Zeitgründen) kann man mit der Code-Duplizierung wohl erst einmal leben.

**Comment by manu37** [comment]
@cmb69 Wäre es hier nicht angesagt, in der reqcheck.php den @CMSIMPLE_XH_VERSION@ token zu setzen und in der build.xml dann mit der aktuellen Versionsnummer zu ersetzen (im übrigen ist dort auch ./plugins/tinymce/admin.php erwähnt. Überflüssig, weil tinymce3 Überbleibsel?)?

**Comment by cmb69** [comment]
@manu37, ah richtig, siehe PR #434.
