### ISSUE TITLE
cmsimple-xh backed bug

### ISSUE THREAD

**Issue by zaydharith** [cmsimple-xh/cmsimple-xh#326]
Hello every body,
after  installation of cmsimple-xh 1.7.1 
i have have a problem to access the backend 
when i login and try to click to a page or to plugin, the backen disapear and return to the fontend and i am  disconnected .
please , can someone help me?

**Comment by cmb69** [comment]
I assume that the login actually didn't work. I suggest that you enable [debug mode](http://www.cmsimple-xh.org/wiki/doku.php/troubleshooting), which likely shows something like "Cannot send headers; headers already sent in …"

**Comment by zaydharith** [comment]
Please how can I do (enable debug mode,) it? I am a big biginner.
I have  a file in userfiles/download/XHdebug.txt  and wen I download it, I find only the digit 6 in this file.

**Comment by cmb69** [comment]
> I have a file in userfiles/download/XHdebug.txt

Just rename this file to userfiles/donwloads/_XHdebug.txt (i.e. add an underscore to the filename) to enable debug mode.

**Comment by zaydharith** [comment]
OK thank you very ,much I do it 
and I have this:
```
**WARNING: get_headers(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0
/var/www/vhosts/7/109994/webspace/....../domain.org/cmsimple/adminfuncs.php:196
WARNING: get_headers(): This function may only be used against URLs
/var/www/vhosts/7/109994/webspace/......./domain.org/cmsimple/adminfuncs.php:196
XH-DEPRECATED: Function editmenu() is deprecated
/var/www/vhosts/7/109994/webspace/......../domain.org/templates/h5000/template.htm:119
XH-DEPRECATED: Function editmenu() is deprecated
/var/www/vhosts/7/109994/webspace/..../domain.org/templates/h5000/template.htm:119**
```

**Comment by zaydharith** [comment]
please does some one have alraedy met this and fix it, i need your help

**Comment by zaydharith** [comment]
Please does some one had already met this poblem and fixt it ? I need your help

**Comment by zaydharith** [comment]
I have this secon d problem too:
```
WARNING: session_start(): open(/tmp/sess_6cfca4a9a3034420f, O_RDWR) failed: Permission denied (13)
/var/www/vhosts/7/109994/webspace/httpdocs/fdomain.org/cmsimple/functions.php:2678
```
**```
function XH_startSession()
{
    global $pth;

    if (session_id() == '') {
        $sessionName = 'XH_' . bin2hex(CMSIMPLE_ROOT);
        file_put_contents("{$pth['folder']['cmsimple']}.sessionname", $sessionName);
        session_name($sessionName);
        session_start();
    }
}
```**

**Comment by cmb69** [comment]
> WARNING: session_start(): open(/tmp/sess_6cfca4a9a3034420f, O_RDWR) failed: Permission denied (13)
/var/www/vhosts/7/109994/webspace/httpdocs/fdomain.org/cmsimple/functions.php:2678

Ah, that's the real problem. Apparently, the configured [session.save_path](http://de2.php.net/manual/en/session.configuration.php#ini.session.save-path) is not writable. If you're not the server admin, you have to contact them to fix this.

The other warnings are minor issues. I suggest to fix the session storage problem first.

**Comment by cmb69** [comment]
Seems this poblem has been solved (one way or another) – closing.

**Comment by zaydharith** [comment]
I fix the session storage problem and every thing is ok now thank you

**Comment by cmb69** [comment]
Great!
