### ISSUE TITLE
Page "Password forgotten" needs a <div> tag with class for styling

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#329]
https://github.com/cmsimple-xh/cmsimple-xh/blob/5d57a7a2af233e477ead1465cc627a74095d300d/cmsimple/classes/PasswordForgotten.php#L47-L48
Sollte so wie hier sein, am besten die selbe Klasse:
https://github.com/cmsimple-xh/cmsimple-xh/blob/5d57a7a2af233e477ead1465cc627a74095d300d/cmsimple/functions.php#L1459-L1461

**Comment by cmb69** [comment]
Stimmt! Ich sehe hier auch kein wirkliches BC-Problem, so dass wir das wohl für 1.7.2 machen sollten.
