### ISSUE TITLE
help-text for "content" is missing

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#335]
help-text for `$cf['folders']['content']="content/";` is missing

**Comment by cmb69** [comment]
Indeed. 

I wonder, however, whether we should hide all folder config options (or even remove them sometime). I can't see the need to configure these folders, and it makes documentation harder to understand. Consider: "the subfolder `images/` of the configured content folder" vs. "`content/images/`".

Thoughts?

**Comment by frase-git** [comment]
> hide all folder config options

**+1**

> (or even remove them sometime)

**-1**
In specally cases is this needed. (Only for Nerds ;-) )
