### ISSUE TITLE
Update links to plugin documentation

### ISSUE THREAD

**Issue by Hartmut63** [cmsimple-xh/cmsimple-xh#336]
URL  ?Plugins
A pretty current and detailed list of available plugins:
OLD: CMSimple_XH-Dokumentation [http://cmsimplexh.webdesign-keil.de/?CMSimple_XH_Referenzlisten/Plugins]
NEW: CMSimple_XH-Dokumentation [http://cmsimplexh.webdesign-keil.de/?Erweiterungen_-_Plugins_und_anderes]

URL  ?Plugins/Plugins-%5Bde%5D
Eine ziemlich aktuelle und ausführliche Liste verfügbarer Plugins:
OLD: CMSimple_XH-Dokumentation [http://cmsimplexh.webdesign-keil.de/?CMSimple_XH_Referenzlisten/Plugins]
NEW: CMSimple_XH-Dokumentation [http://cmsimplexh.webdesign-keil.de/?Erweiterungen_-_Plugins_und_anderes]

**Comment by cmb69** [comment]
Thanks, Hartmut. I'm labelling this as bug, even though the old URLs still work, but the link checker would trigger warnings.
