### ISSUE TITLE
Improve page URLs

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#337]
It might be nice to have options to exclude certains words from page URLs (such as "and" and "or") and to convert the page URLs to lower case. See https://cmsimpleforum.com/viewtopic.php?t=12940&p=63109#p63105.

**Comment by olape-git** [comment]
lower case

https://github.com/cmsimple-xh/cmsimple-xh/commit/7c045d54521dc806e8d1e2f4d76a731f2bb8e659

https://github.com/cmsimple-xh/cmsimple-xh/compare/master...olape-git:cmsimple-xh:transliteration

**Comment by olape-git** [comment]
https://github.com/olape-git/cmsimple-xh/commit/f0319f5ce9777137cf789a51e622127f9ea872ab
