### ISSUE TITLE
Hide all folder configuration options

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#342]
It is possible to configure the content and the userfiles folder (including its three subfolders for images, downloads and media). This is rarely necessary, but still might be useful for very advanced users for whatever reason. However, presently these config options are marked as advanced, so that they can be changed from the back-end. I suggest to change them to be hidden, so the only way to change them would be by manually editing `config.php`.

See also https://github.com/cmsimple-xh/cmsimple-xh/issues/335#issuecomment-346011924.

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/commit/bd7d5b84172cd4a3f2fe9f7244bafe18eef29244
