### ISSUE TITLE
Remove superfluous type attributes from script elements

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#351]
Acccording to the [HTML 5.1 2nd Edition specification](https://www.w3.org/TR/html51/semantics-scripting.html#the-script-element): "Authors should omit the attribute, instead of redundantly giving a JavaScript MIME type." Accordingly, the W3C Nu Html Checker [triggers warnings](https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.cmsimple-xh.org%2F), if these type attributes are present. Since, to my knowledge, even rather old browsers are doing fine if the attribute is ommitted, I suggest to remove them.

**Comment by manu37** [comment]
see #408
