### ISSUE TITLE
Replace reserved characters in page URLs

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#357]
According to [RFC 3986](https://tools.ietf.org/html/rfc3986) several characters are reserved characters, which basically means that these may or not be percent encoded in an URL without changing the meaning. However, CMSimple_XH cannot necessarily deal with both representations.

Reproducer: navigate to the start page of a clean XH 1.7.2 installation, then navigate to "Start [de]", what requests http://localhost/xh/?Start/Start-%5Bde%5D, but in the address line of FF 58.0 is shown as http://localhost/xh/?Start/Start-[de]. Then focus the address line and hit enter; the result is "404 Not found".

Most likely, the simplest and cleanest solution would be to replace all reserved characters with `$cf['uri']['word_separator']`. This would, however, constitute a small BC break. Maybe it's better to simply add respective replacement rules to urichar_org/new.

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/compare/master...olape-git:cmsimple-xh:transliteration

**Comment by olape-git** [comment]
https://github.com/olape-git/cmsimple-xh/commit/f0319f5ce9777137cf789a51e622127f9ea872ab
