### ISSUE TITLE
Modify info and help links in the backend

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#358]
[cmsimple-xh.org/wiki/](http://www.cmsimple-xh.org/wiki/) --> [wiki.cmsimple-xh.org/](http://wiki.cmsimple-xh.org)

[cmsimple-xh.org/de/?Alles_auf_einen_Blick](http://www.cmsimple-xh.org/de/?Alles_auf_einen_Blick) --> [cmsimple-xh.org/de/?Wichtige-Links](http://www.cmsimple-xh.org/de/?Wichtige-Links) or [cmsimple-xh.org/?Important-Links](http://www.cmsimple-xh.org/?Important-Links)

**Comment by cmb69** [comment]
Wenn ich mich nicht irre, dann hast du dafür bereits Redirects angelegt, so dass es sich hier nicht um einen Bug(fix) handelt, und auf 1.8 warten kann.

**Comment by olape-git** [comment]
Du irrst dich nicht.
Ist mehr ein optisches Problem

**Comment by olape-git** [comment]
Vielleicht kann man das zukünftig die Linktexte vereinfachen, wenn man z.B. nur **Wiki** als Linktext nimmt.
Dann fällt es erst mal nicht auf, falls sich der mal Link ändert.
Natürlich dann bei allen Links auf diese Weise.

**Comment by olape-git** [comment]
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/2c29168a9236fc68ec53a41fef0d29432f640e0b

**Comment by cmb69** [comment]
> Vielleicht kann man zukünftig die Linktexte vereinfachen, wenn man z.B. nur Wiki als Linktext nimmt.
Dann fällt es erst mal nicht auf, falls sich der mal Link ändert.

Fände ich *sehr* gut!

**Comment by olape-git** [comment]
Hm, ich auch, nur gemacht habe ich es selber nicht. :-(

**Comment by frase-git** [comment]
Ich denke, seit XH 1.7.3 ist der Content geändert und dieses Problem erledigt - oder?
Ich schließe dieses Issue.
