### ISSUE TITLE
Integrate ADC plugin functionality

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#361]
See https://cmsimpleforum.com/viewtopic.php?f=16&t=9986&p=51385#p51385.

**Comment by olape-git** [comment]
#401 https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/7bfa1e04dad1b702b2e6998ff3213cc5888bed05
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/afd0e9d18f9aab64754cd6866815bdf58f26d642
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/2c93a9fa2a2315af565ddb061e5e7fc6e018ee0d
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/751d1d77eccf77e8ba44c314fe06e7768b78a9a8
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/a714fb7c6d28473cb8f9955879d0b31c6b123dca
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/a84250ccb8bef933a48e11672d6b55a354c3db7d
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/1471f8ba4a052d0a064a53c3c22ca05e7d519ffe
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/ef766fd1411d8dc8c014a28ade852ee7d359887d

**Comment by cmb69** [comment]
As I understand it, the suitable parts of the ADC plugin have been integrated for CMSimple_XH 1.7.3. Am I right?

**Comment by olape-git** [comment]
No, not quite. We had it inside. Unfortunately, the majority decided against it. Now it has ended up in a plugin, which will be included ahead of time.

https://github.com/olape-git/cmsimple-xh/tree/remove-fuction-from-SEO-Betterments

https://cmsimpleforum.com/viewtopic.php?f=42&t=16172&start=10#p75513

**Comment by olape-git** [comment]
This point is actually settled. It has just become a plugin.
Di majority had decided against building it directly into XH (then 1.7.3).

https://olaf.penschke.net/?CMSimple_XH/Plugins/ADC-Core_XH

It is missing actually only the implementation, "The integration of the plugin" variable to make, so that also alternatives can be used, if perhaps times available.

**Comment by cmb69** [comment]
Okay, closing this ticket then.
