### ISSUE TITLE
core.css - add style for xh_adminmenu

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#362]
https://github.com/cmsimple-xh/cmsimple-xh/blob/0a9123f925d05c5aa5a6fa10e9f67d9f96350407/assets/css/core.css#L56
Add for vertical alignment.
`line-height: normal;`

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/issues/412
