### ISSUE TITLE
adminfuncs.php: target="blank"

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#364]
https://github.com/cmsimple-xh/cmsimple-xh/blob/0a9123f925d05c5aa5a6fa10e9f67d9f96350407/cmsimple/adminfuncs.php#L228

Da fehlt der Unterstrich bei target="blank". Sollte target="_blank" lauten.
Ansonsten kann es passieren, das phpinfo nicht in einer neuen Seite geöffnet wird.

**Comment by cmb69** [comment]
Thanks!
