### ISSUE TITLE
German: incorrect translation: "userfiles"

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#369]
in ... \cmsimple\languages\default.php
$tx['title']['userfiles']="Userfiles";`

in ... \cmsimple\languages\de.php
$tx['title']['userfiles']="Andere";`

This translation is incorrect.
Better?
$tx['title']['userfiles']="Benutzer-Dateien";`

Example: In filebrowser, the first (main) folder in German:
"Andere Ordner" ???
Better:
"Benutzer-Dateien Ordner"

What about: `$tx['editmenu']['userfiles']` ?

**Comment by cmb69** [comment]
Indeed, a bad translation. (This is not properly internationalized, anyway, see https://cmsimpleforum.com/viewtopic.php?f=29&t=6076).

> What about: $tx['editmenu']['userfiles'] ?

Apparently, a [relict of XH 1.5](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.5.10/cmsimple/cms.php#L1287). I'm uneasy to rid it in a revision, so I'm going to remove it for master only.
