### ISSUE TITLE
First published page should suppress page URL

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#375]
The first published page (aka. start page) can be requested with or without its “page URL” (for instance, http://example.com/ vs. http://example.com/?Start), what is fine. However, it is usually linked with the “page URL” in the menu, and that may create duplicate content. Therefore, it would be preferable to suppress the “page URL” of the first published page whenever it is linked.

**Comment by olape-git** [comment]
#402 
https://github.com/cmsimple-xh/cmsimple-xh/pull/402/commits/afd0e9d18f9aab64754cd6866815bdf58f26d642

**Comment by TN03** [comment]
Sorry, aber ich weiß jetzt nicht genau auf was hier abgestimmt werden soll. Hier sind einige commits aufgeführt. Um welchen Code genau geht es hier???

**Comment by olape-git** [comment]
Ja, ist etwas durcheinander. Tut mir leid.
Hauptsächlich geht es darum
https://github.com/cmsimple-xh/cmsimple-xh/pull/398/commits/afd0e9d18f9aab64754cd6866815bdf58f26d642
und Teile daraus:
https://github.com/cmsimple-xh/cmsimple-xh/pull/403/commits/a84250ccb8bef933a48e11672d6b55a354c3db7d
die nichts mit www. https oder index.php zu tun haben.

Oder wollen wir wenigstens das Remove index.php drin lassen?

**Comment by TN03** [comment]
@olape-git Okay, diese beiden PRs schauen gut aus. 
Was den ganzen Rest von seofuncs.php angeht: ich sehe das kritisch. Bei all den Argumenten (simpel für User etc.) sehe ich das inzwischen so, dass es den "Simplen" User wohl kaum interessieren wird. Der ambitionierte User kann sich ein Plugin installieren, oder .htaccess verwenden. Die Nachteile eines Plugins hast Du ja deutlich herausgestellt und da stimme ich Dir auch zu. Ein Vorschlag, um diese Nachteile zu umgehen: was hälst Du davon, wenn wir anstatt dem statischen include() von seofuncs.php einen Hook, ähnlich wie userprelude.php / userfuncs.php oder custom_404() etablieren. All die gute Arbeit könnte dann in ein konfigurierbares Plugin wandern und trotzdem die Vorteile einer frühen Einbindung ausnutzen. Ich glaube, auf diese Weise würden wir uns vermeintlich aufkommenden Stress ersparen können.

**Comment by olape-git** [comment]
ein Teil der seofuncs.php wird aber benötigt.  eben für "First published page" "empty path" und dann hatten wir noch den "Bug" mit dem Pagemanager, das ist momentan auch drin.
Eine Art vorgezogene Schnittstele für das Plugin adc hatte ich auch schon vorgeschlagen.
Ich glaube, das wäre eine gute Alternative.

**Comment by olape-git** [comment]
Es gäbe natürlich noch eine andere Möglichkeit.
Wir lassen alles drin wie es ist, als verstecktes Feature und bieten nur die Möglichkeit, die Konfiguration nachzurüsten.
Dann wäre, für den Fall, falls in 1.8 doch, weil zur Zeit im Plan vorgesorgt. Und wenn nicht, dann bleibt es in 1.8 eben auch so. Für 1.8 ist auch Canonicial Link vorgesehen, der ja auch gut in seofuncs.php passen würde.

**Comment by manu37** [comment]
getestet mit #417, alles i.O. Danke Olaf.
Kann das noch jemand bestätigen?
