### ISSUE TITLE
Locator: position belongs to ListItem, not WebPage

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#378]
See <https://cmsimpleforum.com/viewtopic.php?f=16&t=14260#p68977>ff.

**Comment by cmb69** [comment]
See also https://cmsimpleforum.com/viewtopic.php?f=5&t=15499

**Comment by olape-git** [comment]
The solution from the forum (https://gist.github.com/cmb69/786ece8c527bfe160ad158bf43427898) is not compatible with og tags or Twittercard. It doesn't matter if you write them manually into the template or generate them via OGra_XH. Also not with hreflang links.

**Comment by olape-git** [comment]
This solution works for me seemingly correctly
[https://cmsimpleforum.com/viewtopic.php?f=5&t=15499&p=73253#p73253](url)

**Comment by olape-git** [comment]
This solution works for me seemingly correctly.
[https://cmsimpleforum.com/viewtopic.php?f=5&t=15499&p=73253#p73253](url)

**Comment by olape-git** [comment]
Oje, schliessen wollte ich gar nicht, kann ich das rückgängig machen?

**Comment by olape-git** [comment]
This solution works for me seemingly correctly.
[https://cmsimpleforum.com/viewtopic.php?f=5&t=15499&p=73253#p73253](url)

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/commit/a9ec9806cc4184b2e6861875a1e273e0ad802f9a
