### ISSUE TITLE
Password reset may leave empty hash in config.php

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#381]
We're failing to check [whether `password_hash()` has succeeded](https://github.com/cmsimple-xh/cmsimple-xh/blob/0a9123f925d05c5aa5a6fa10e9f67d9f96350407/cmsimple/classes/PasswordForgotten.php#L144), which may result in an empty hash stored in config.php. This is not a security issue, since a following `password_verify()` will always fail, but still erroneous behavior.

**Comment by olape-git** [comment]
[https://www.php.net/manual/de/function.password-hash.php](url)

> Returns the hashed password, Im Fehlerfall wird FALSE zurückgegeben.

if($hash !== false)

**Comment by olape-git** [comment]
https://github.com/olape-git/cmsimple-xh/commit/76eeac4be197f655052cbc01cfff083b9868e823

**Comment by olape-git** [comment]
#401 
https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/76eeac4be197f655052cbc01cfff083b9868e823

**Comment by manu37** [comment]
76eeac4
