### ISSUE TITLE
Allow to toggle debug mode via button

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#384]
See <https://cmsimpleforum.com/viewtopic.php?t=5962&p=70084#p70070>.

**Comment by frase-git** [comment]
Das es inzwischen das Plugin [Switchdebug_XH](https://olaf.penschke.net/?CMSimple_XH/Plugins/Switchdebug_XH) gibt, scheint mir, dass dieses Issue geschlossen werden kann - was ich auch gleich tun werde.
