### ISSUE TITLE
locator separator shouldn't be hard-coded

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#385]
See <https://cmsimpleforum.com/viewtopic.php?f=16&t=14518>.

**Comment by manu37** [comment]
how about setting the seperator in a (optional) parameter in locator()?

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/commit/a9ec9806cc4184b2e6861875a1e273e0ad802f9a
