### ISSUE TITLE
Remove unnecessary type="text/javascript" in <script>-Tags

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#393]
Currently applies to the plugin jQuery and the template fhs-simple.
[See Example, CMSimple_XH Demo](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdemo.cmsimple-xh.dk%2F)

**Comment by olape-git** [comment]
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/0a1527059f80038e0214ca1d609ba45e9dfd365a

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/pull/403/commits/0a1527059f80038e0214ca1d609ba45e9dfd365a
