### ISSUE TITLE
Plugin jquery - update config.php settings to latest versions

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#394]
https://github.com/cmsimple-xh/cmsimple-xh/blob/62cffd36799c51abc9ba72732b9d9e3ad24de15e/plugins/jquery/config/config.php#L3
https://github.com/cmsimple-xh/cmsimple-xh/blob/62cffd36799c51abc9ba72732b9d9e3ad24de15e/plugins/jquery/config/config.php#L4
https://github.com/cmsimple-xh/cmsimple-xh/blob/62cffd36799c51abc9ba72732b9d9e3ad24de15e/plugins/jquery/config/config.php#L5

**Comment by TN03** [comment]
Fixed with https://github.com/cmsimple-xh/cmsimple-xh/pull/440
