### ISSUE TITLE
Update to Pagemanager_XH 3.3

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#395]

**Comment by olape-git** [comment]
:+1:
mindestens aber mit diesen Anpassungen

https://github.com/cmb69/pagemanager_xh/pull/62
https://github.com/cmb69/pagemanager_xh/pull/61

**Comment by cmb69** [comment]
Diese Anpassung sind durchgeführt; wenn noch Zeit bleibt, würde ich wohl noch auf das aktuellste jsTree aktualisieren. Habt ihr eine konkrete Vorstellung, wann XH 1.7.3 freigegeben werden soll?

**Comment by olape-git** [comment]
Wäre schön, wenn du das noch machst.
Meines Wissens nach, gibt es noch keinen Termin.
Es hängt momentan hauptsächlich an GitHub, denke ich.
Ihr seit ja fleissig dran, wie man sieht. Da kann ich aber Aufwand und Zeitrahmen nicht abschätzen. Das müsste hauptsächlich erst mal mit manu und Holger abgesprochen werden.

**Comment by manu37** [comment]
09b34cce0c96f7cf707d11c91ce4b1dd2e531b32
