### ISSUE TITLE
more options for form fields in metaconfig.php

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#396]
at the moment are possible:
text --> textarea, 
bool -- checkbox, 
enum --> select, 
xenum --> text with datalist, 
random  hidden --> hidden 
all other --> text-field

I propose the following extension:
number
range
color
email

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/issues/269

**Comment by cmb69** [comment]
I'm generally in favor of this, but I'm not sure about number and range; aren't these basically the same (number with min and max), but only with different presentation?

**Comment by olape-git** [comment]
Basically, it's the same. But this way you can play a little with the optics.

**Comment by Tata55** [comment]
Very useful would be also a datepicker. Instead of adding date manually, they would be inserted in proper format right from the datepicker.
