### ISSUE TITLE
Deliver jQuery4CMSimple config.php in update packages

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#4]
See the [forum discussion](http://cmsimpleforum.com/viewtopic.php?f=16&t=12106&start=10#p56190).

**Comment by cmb69** [comment]
I suggest not to change this for the (supposedly) last update for XH 1.6, because that may cause more confusion than be helpful. We may reevaluate this issue for XH 1.7, though.

**Comment by manu37** [comment]
My proposal for 1.7.3: provide the latest libraries, leave config.php as it is. Stick to the actual settings for a new 1.7.3 install. With this we can test the latest libraries with the core. Remove old libraries on a major update with announcement.

**Comment by frase-git** [comment]
In the worst case, I'd even plead to leave everything as it is.
Despite many objections, we cannot yet do without jQuery.

**Comment by TN03** [comment]
> My proposal for 1.7.3: provide the latest libraries, leave config.php as it is. Stick to the actual settings for a new 1.7.3 install. With this we can test the latest libraries with the core. Remove old libraries on a major update with announcement.

Done with https://github.com/cmsimple-xh/cmsimple-xh/pull/440 as proposed.
Can we close this issue for now?
