### ISSUE TITLE
PHP 7.4.x

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#400]
The time is ripe.
PHP 7.4.x will be up-to-date and we should incorporate the proposed changes as soon as possible:
https://cmsimpleforum.com/viewtopic.php?f=16&t=15976#p74445

**Comment by olape-git** [comment]
#https://github.com/cmsimple-xh/cmsimple-xh/pull/401/commits/799b4a27816df78063b6011c5936d6502251b3b2
