### ISSUE TITLE
SEO Betterments

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#404]
https://github.com/cmsimple-xh/cmsimple-xh/pull/403/commits/7bfa1e04dad1b702b2e6998ff3213cc5888bed05
one part of:
First published page should suppress page URL #375
#375

Empty path segments in an URL #282
#282

brings the functionality of the plugin acd (Holger Irmler)

**Comment by manu37** [comment]
Ist ein ambitionierter Ansatz, aber ich bin der Meinung, dass das nicht in den core gehört. Vorausgegangene Diskussionen: https://github.com/olape-git/cmsimple-xh/issues/2.
Link im cmsimpleforum folgt.

**Comment by frase-git** [comment]
Was mache ich, wenn ich  #375 und #282 zustimmen möchte?

**Comment by manu37** [comment]
Das kannst Du doch. Siehe mein obiger Post. Ich habe mich im Forum das Thema detaillierter angesprochen.

**Comment by olape-git** [comment]
Na, ihr seht es mir nach, aber ich stimme selbstverständlich für alles, sonst hätte ich das nicht angefangen. Es lässt sich, aus meiner Sicht, eben auch schwer oder wenigstens nich wirklich sinnvoll trennen.
👍

**Comment by TN03** [comment]
Sorry, aber ich gehe da mit Manu. Die Sache mit den Umleitungen sehe ich kritisch als Core-Lösung.

**Comment by TN03** [comment]
Hmm, aber wie ich jetzt sehe, ist der Code für die Umleitungen ja bereits im 1.7er branch enthalten, siehe: https://github.com/cmsimple-xh/cmsimple-xh/commit/e26d7a8318b81f7588669d149ab423632ece6fb0 ???
Sorry, aber ich hab', nach etwas Pause, Probleme den Überblick zu bekommen...

**Comment by olape-git** [comment]
Ich war es nicht (glaube ich).
Aber so schlimm ist das ja auch nicht. Wir streichen einfach raus, was ihr nicht möchtet.
Also www. und https, vielleicht noch index.php.
Ich hatte auch im Forum dazu geschrieben.
https://cmsimpleforum.com/viewtopic.php?f=42&t=16172&p=75319#p75319

**Comment by manu37** [comment]
#417 Alles ok? Oder braucht es hier noch einen Test?

**Comment by manu37** [comment]
#417
