### ISSUE TITLE
Remove unnecessary type="text/javascript"

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#408]
Remove unnecessary type="text/javascript" in <script>-Tags …
0a15270
#393

**Comment by frase-git** [comment]
Ist damit https://github.com/cmsimple-xh/cmsimple-xh/issues/351 erledigt?
Kann also #351 geschlossen werden?

**Comment by manu37** [comment]
genau, habe #351 geschlossen

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/pull/403/commits/0a1527059f80038e0214ca1d609ba45e9dfd365a
