### ISSUE TITLE
Updating the content.htm

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#411]
Die Inhalts-Datei (content.htm) muss aktualisiert werden.
Im Wesentlichen handelt es sich um Aktualisierungen der Links zu CMSimple_XH-Seiten (Projektseite, Wiki usw.) sowie um Anpassungen wegen [aktualisierter Standard-Templates](https://github.com/cmsimple-xh/cmsimple-xh/issues/410).
[Demo hier](http://fhs.bplaced.net/cmsxh-distro-173/).

**Bitte abstimmen**, ob das so in 1.7.3 übernommen werden soll.

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/pull/414
