### ISSUE TITLE
New assets-Folder

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#412]
In der dev7 hatte es eine neue assets/css/core.css mit den fancy switches/checkboxen. Ist diese mit Absicht hier nicht implementiert?

**Comment by frase-git** [comment]
Zum neuen Assets-Ordner wird es demnächst ein extra-Issue geben.
Da muss aber vorher noch ein Frage geklärt werden. Siehe [im Forum](https://cmsimpleforum.com/viewtopic.php?f=42&t=16132&start=10#p75296).

**Comment by frase-git** [comment]
Soooo.
Warum nicht gleich hier? Die Überschrift stimmt schonmal und die Frage im Forum wurde geklärt.

Es gibt also den Vorschlag, den alten assets-Ordner aus v1.7.2 mit einem neuen auszutauschen.
Was soll das bewirken?
1. Das Aussehen der xhPages und der PD-Tabs soll etwas aufgehübscht aber auch standardisiert werden. Bisher hatten z.B. Template-spezifische Style-Angaben hier Einfluss - und in manchen Fällen (sehr große oder Schreibschriften) war kaum noch etwas lesbar (in Formularfeldern oder Listen usw.).
1. Es wurde versucht, System-Schriftarten für alle (die meisten, soweit möglich) xhPages einzusetzen.
1. Das Menü für Plugins (Config, Language, Help usw.) wurde ausschließlich mit CSS auf Buttons "umgestrickt".
1. Debug-Meldungen wurden gestyled.
1. Alle Systemmeldungen wurden gestyled (inkl. SVG statt PNG).
1. Der Systemcheck (Info) wurde gestyled.
1. Alle Formular-Elemente (auch in PD-Tabs) wurden gestyled (inkl. animierter Checkboxen).
1. Bei Focus auf ein Eingabefeld oder Textarea wird der Hintergrund farblich hervorgehoben - Übersichtlichkeit - auch bei "Template" oder "Stylesheet".
1. Help-Symbol (?) mit SVG ersetz (nur soweit beeinflussbar, bei Plugins klappt das mitunter nicht wenn eigene Bilder verwendet wurden).
1. Tooltip beim Help-Symbol übersichtlicher gestaltet.
1. "Passwort ändern" umgestaltet.
1. Login-Formular umgestaltet.
1. Linkchecker (minimal) umgestaltet.
1. und weitere minimale Änderungen.

Weiterhin wurde das Standard-Adminmenü umgestaltet. Verschiebungen durch falsche Zeilenhöhen sollten nicht mehr auftreten.
Außerdem wurde die Breite der einzelnen Menüpunkte minimal vergrößert - von 125px auf 150px.
Diese Änderung erfordert allerdings zwei winzige Änderungen in der adminfuncs.php:
1. In [dieser Zeile](https://github.com/cmsimple-xh/cmsimple-xh/blob/62cffd36799c51abc9ba72732b9d9e3ad24de15e/cmsimple/adminfuncs.php#L644) muss die Zahl "125" mit "150" ersetzt werden.
1. In [dieser Zeile](https://github.com/cmsimple-xh/cmsimple-xh/blob/62cffd36799c51abc9ba72732b9d9e3ad24de15e/cmsimple/adminfuncs.php#L645) muss die Zahl "250" in "300" geändert werden.

Habe fertig.

Wichtig: Alle alten Formatierungen und auch die PNGs sind weiterhin im Ordner enthalten - damit evtl. Zugriffe von Plugins oder sonstwoher auch weiterhin funktionieren.

**Bitte abstimmen**, ob der neue assets-Ordner mit XH 1.7.3 ausgeliefert werden soll.

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/pull/415

**Comment by manu37** [comment]
Sieht sehr gut aus!
Gemäss Pt. 7 müsste jetzt im Pagedata Tab die "Show in Menü" checkbox auch neu gestylt sein?
Ist aber nicht.

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/issues/362

Wie sieht es damit aus, ist das noch nötig?

**Comment by frase-git** [comment]
> Gemäss Pt. 7 müsste jetzt im Pagedata Tab die "Show in Menü" checkbox auch neu gestylt sein?
> Ist aber nicht.

Ja leider. Das hatte ich damals nicht hinbekommen. Weiß nicht mehr warum.

> #362 Wie sieht es damit aus, ist das noch nötig?

Kann geschlossen werden. Wurde [hier mit Ludwig](https://cmsimpleforum.com/viewtopic.php?f=42&start=10&t=16132#p75318) geklärt.

**Comment by TN03** [comment]
Ich enthalte mich hier ;-). Die animierten Checkboxen braucht's in meinen Augen nicht, aber ich werde mich dran gewöhnen.
Wie schaut es mit dem UpdateCheck aus? Könnte man den nicht auch entsprechend anpassen?

**Comment by frase-git** [comment]
>  Wie schaut es mit dem UpdateCheck aus? Könnte man den nicht auch entsprechend anpassen?

[Siehe hier.](https://cmsimpleforum.com/viewtopic.php?f=42&t=16183&p=75393#p75393)

**Comment by cmb69** [comment]
Gefällt mir insgesamt sehr gut. Danke!

Ein bisschen bedenken hätte ich dies in einer Revision zu veröffentlichen, aber nach der langen Zeit vielleicht einfach auch überfällig. :)

**Comment by frase-git** [comment]
> Ein bisschen bedenken hätte ich dies in einer Revision zu veröffentlichen, aber nach der langen Zeit vielleicht einfach auch überfällig. :)

Da hast du wohl recht - nützt aber nix. Ist jetzt so ;-)

BTW: Kann - wenn der assets-Ordner in 1.7.3 kommt - nicht https://github.com/cmsimple-xh/cmsimple-xh/issues/324 geschlossen werden - als erledigt?

**Comment by manu37** [comment]
> BTW: Kann - wenn der assets-Ordner in 1.7.3 kommt - nicht #324 geschlossen werden - als erledigt?

#415 ist gemerged. Die obige Frage ist noch offen. Können das die Spezialisten klären?

**Comment by cmb69** [comment]
> BTW: Kann - wenn der assets-Ordner in 1.7.3 kommt - nicht #324 geschlossen werden - als erledigt?

Hmm, sieht so aus, als ob das Plugineditmenü noch immer eine Tabelle ist, so dass z.B. bei Realblog_XH noch immer zwei Zeilen (`<tr>`) verwendet würden. Mittelfristig würde ich mir da ein anderes Markup wünschen.

**Comment by manu37** [comment]
Dann lassen wir #324 offen und schliessen dieses Issue #412.

**Comment by frase-git** [comment]
> Hmm, sieht so aus, als ob das Plugineditmenü noch immer eine Tabelle ist, so dass z.B. bei Realblog_XH noch immer zwei Zeilen (<tr>) verwendet würden. Mittelfristig würde ich mir da ein anderes Markup wünschen.

Ja. Am Code wurde bisher absolut nichts geändert - nur die Tabellenzellen wurden mit reinem CSS in "Pseudo-Buttons" umgewandelt.
Bei Realblog oder auch bei xhShop entsteht eine zweite Zeile, die dann die Buttons enthält.

Je nachdem wie man es sehen will - https://github.com/cmsimple-xh/cmsimple-xh/issues/324 ist damit eigentlich erledigt.

Ich vermisse den neuen assets-Ordner im Master. Verstehe ich da was falsch?

**Comment by manu37** [comment]
> Ich vermisse den neuen assets-Ordner im Master. Verstehe ich da was falsch?

Kommt schon noch. Ich wollte zuerst Eure Reaktion abwarten. Ich lege das Augenmerk erstmals auf den 1.7er Branch. Das ist ja der, den wir zeitnah herausgeben wollen und daher getestet sein soll.

**Comment by cmb69** [comment]
> Wenn wir da etwas ändern, müssten dann nicht auch die Plugins geändert werden?

Tendenziell wohl schon. Aber es betrifft nur sehr wenige Plugins, und ich finde eine Tabelle für dieses Menü einfach einen völlig falschen Ansatz. Aber wie gesagt, das ist nichts, was ich jetzt gleich gelöst haben wollte – kann ruhig warten. :)
