### ISSUE TITLE
replace reserved characters in url

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#413]
https://cmsimpleforum.com/viewtopic.php?f=16&t=16079&start=20#p74826

https://cmsimpleforum.com/viewtopic.php?f=16&t=12886&p=61859&hilit=reservierte+zeichen#p61855

https://cmsimpleforum.com/viewtopic.php?f=16&t=8945&p=48722&hilit=reservierte+zeichen#p48726

...
Many problems because reserved characters are not excluded or replaced.
In case of an update it does not come into effect, so it does not cause any problems and in case of a new installation it would be possible.

default.php, en.php
`$tx['urichar']['new']="-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-";`
`$tx['urichar']['org']="&amp;| |'|§|%|:|/|?|#|[|]|@|!|$|&|'|(|)|*|+|,|;|=|\"";`

de.php
`$tx['urichar']['new']="-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|ae|oe|ue|ss|Ae|Oe|Ue";`
`$tx['urichar']['org']="&amp;| |'|§|%|:|/|?|#|[|]|@|!|$|&|'|(|)|*|+|,|;|=|\"|ä|ö|ü|ß|Ä|Ö|Ü";`

Update:
Ich habe es doch noch gefunden https://github.com/cmsimple-xh/cmsimple-xh/issues/357

**Comment by frase-git** [comment]
In the hope that all this is right, I gave my "thumb up".
Looks good to me.

**Comment by lck-git** [comment]
Hm, bitte mal gegenprüfen.
Aus & sollte in der URL - werden. Bei mir wird das zu zu amp und &&& wird zu amp-amp-amp

**Comment by frase-git** [comment]
> Aus & sollte in der URL - werden. Bei mir wird das zu amp und &&& wird zu amp-amp-amp

Kann ich nicht **nur teilweise** bestätigen.
1.7.3 Version Olape 7
PHP 7.4.2
neue Seite angelegt: "test &&& test"
Dann sofort einen Inhalt **auf der Seite eingefügt und gespeichert!**
taucht in der Adressleiste auf als: "?test-test"
im Menü als: "test &&& test"
Eigentlich alles so, wie erwartet.

Du hast aber recht: Solange die Seite nicht gespeichert wird (bearbeitet), erscheinen die 3 "amp".
Da sollte Olaf nochmal drüberschauen.

**Comment by olape-git** [comment]
Das kann ich zwar auch bestätigen. Wenn die Seite nur angelegt wird, aber noch keinen Inhalt hat, dann wir aus &&& - -amp-amp-amp-. Da ich aber nun gerade mit einer ganz sauberen 1.7.2 teste, sehe ich mich vollkommen schuldfrei. Erklären kann ich das aber jetzt auch nicht.

Das Ganze ist so eh nur ein erste, wenn auch wichtiger Schritt (in meinen Augen). Für die 1.8 sollten wir planen, den Teil reservierte Zeichen nicht mehr konfigurierbar zu machen.
Warum?
Ich habe jetzt als Ersetzung den **-** gewählt. Solange in der Konfiguration der Word-Separator auch auf dem **-** steht, werden mehrere aufeinanderfolgende auf einen gekürzt. Weicht die beiden voneinander ab, sieht das Ganze Sch... aus.
Wenn man das für die 1.8 irgendwo fest verankert, dann kann man bei beiden Varianten den Word-Separator nutzen, und es wäre egal, wie der aussieht, oder wenn dieser geändert würde.

**Comment by lck-git** [comment]
> Du hast aber recht: Solange die Seite nicht gespeichert wird (bearbeitet), erscheinen die 3 "amp".
Da sollte Olaf nochmal drüberschauen.

Das stimmt, ich hatte nur die Seite angelegt. Aber, es kommt noch "besser".

Zum Nachtesten (WICHTIG! Vorher eine Sicherungskopie des contents anlegen!) und ich habe hier zum Testen auch mal nur die neuen Ersetzungen eingefügt.
`-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-`
`:|/|?|#|[|]|@|!|$|&|'|(|)|*|+|,|;|=`


1) Pagemanger eine neue Seite anlegen mit dem Namen
`test:test/test?test#test[test]test@test!test$test&test'test(test)test*test+test,test;test=`

2) Speichern
-bisher alles normal

3) Nochmals speichern (BTW: Wieso kann man das eigentlich, wenn keine Änderungen gemacht sind. Normal sollte das Speichern-Icon dann gar nicht aktiv sein).
-"Laden..." erscheint und das Rädchen dreht sich und dreht sich ...

-Blick in die Browser-Console meldet:
> Uncaught SyntaxError: Invalid regular expression: /:|/|?|#|[|]|@|!|$|&|'|(|)|*|+|,|;|=/: Nothing to repeat
    at new RegExp (<anonymous>)
    at HTMLLIElement.<anonymous> (pagemanager.js:22)
    at Function.each (jquery.min.js:2)
    at a.fn.init.each (jquery.min.js:2)
    at markDuplicates (pagemanager.js:22)
    at HTMLDivElement.<anonymous> (pagemanager.js:26)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:3)
    at Object.a.event.trigger (jquery-migrate-1.4.1.min.js:2)

4) Speichere ich nun (Rädchen dreht sich immer noch) ein **drittes** mal und reloade nun die Webseite, so wird der ganze content gelöscht und es erscheint im Pagemanager nur eine Seite mit den Namen "NEUE SEITE".:astonished:

**Comment by olape-git** [comment]
also ich habe bei mir schon seit wenigstens 1.6.4:
`| |&amp;|(|)|/|.|` zusätzlich zu den Umlauten drin.
Ich hatte damit noch nie Probleme.
Die URL ist ja nun auch wirklich etwas speziell. ;-)

Was mich darauf bringt, Ich habe in der Liste das Leerzeichen vergessen.

**Comment by lck-git** [comment]
> Die URL ist ja nun auch wirklich etwas speziell. ;-)

Ja stimmt, aber das tut nichts zur Sache.

Also Test, normale Seitennamen ohne Schnickschnack und diese spezielle.
In der Sprachdatei nur bei "Original" eingetragen,
`:|/|#|[|]|@|!|$|&|'|,|;|=`
 "Ersetzung" ist komplett leer, nichts eingetragen:
--> Ergebnis: keine Probleme.

Aber, sobald ich **eins dieser Zeichen** hinzufüge, oder **nur eins von denen** bei "Original" einfüge:
`? * ( ) +`
--> Ergebnis, wie weiter oben beschrieben

Problemverursacher sind also : `? * ( ) +`
Ok sind : `:|/|#|[|]|@|!|$|&|'|,|;|=`

Testet das bitte mal mit XH 1.7.3 DEV7.
Ich vermute es liegt am Pagemanager 3.3 oder an der PHP-Version 7.3.16 (?)

**Comment by lck-git** [comment]
Test bei bplaced.net mit **XH 1.7.3 DEV7** und **PHP 7.4.2** === **Gleiches Ergebnis/Problem**.

**Comment by olape-git** [comment]
Ja, nu, die Möglichkeit der Ersetzungszeichen ist nun aber gerade dafür gedacht.
Das scheint es braucht hier eher ein JS-Profi.
Und es scheint, du hast einen Bug im Pagemanager gefunden.

In der 1.7.2 ist noch die 3.2 drin. Es liegt also nicht an der 3.3.

**Comment by lck-git** [comment]
> In der 1.7.2 ist noch die 3.2 drin. Es liegt also nicht an der 3.3.

Stimmt. Getestet mit XH 1.7.2 und Pagemanger 3.2, gleiches Problem!

**Comment by frase-git** [comment]
Vorschlag:
**Milestone ändern zu 1.8**

Wir werden das jetzt nicht "auf die Schnelle" lösen können.
Das bedarf noch genauerer Untersuchungen.

Vielleicht liegt das alles nur an einem Tipp-Fehler im CMS?
Zum Beispiel: Warum heißt es einmal sep**E**rator und einmal sep**A**rator ???
https://github.com/cmsimple-xh/cmsimple-xh/blob/62a9f1fc23912c41cebfd580037718b5aebe7b15/cmsimple/config.php#L41
https://github.com/cmsimple-xh/cmsimple-xh/blob/62a9f1fc23912c41cebfd580037718b5aebe7b15/cmsimple/config.php#L42
Also, was meint ihr? Verschieben nach 1.8 und erstmal alles lassen wie es ist (auch wenn es das Problem nicht behebt)?

**Comment by olape-git** [comment]
Wenn uns nichts einfällt dazu, wird es wohl nicht anders werden.

**Comment by lck-git** [comment]
`Problemverursacher sind also : ? * ( ) +`
Eventuell müsste man diese Zeichen maskieren?

> Wenn uns nichts einfällt dazu, wird es wohl nicht anders werden.
Man müsste das mehrfache speichern im Pagemanager verhindern, somit wäre das Problem zwar nicht gelöst , aber umgangen (Dirty Fix).

**Comment by olape-git** [comment]
**Bitte mal Testen!** Also nicht nur, ob es jetzt durchläuft, sondern auch, ob es denn immer noch tut was es soll. Bitte in den Sprachdateien auch noch das Leerzeichen in die Ersetzung aufnehmen!
Ist jetzt erst mal in der 3.2, aber ich glaube, 3.3 ist in dem Punkt identisch.

https://github.com/olape-git/pagemanager_xh/blob/3.2/classes/MainAdminController.php#L176

zu

`            'uriCharOrg' => explode(XH_URICHAR_SEPARATOR, str_replace(array('?', '*', '+', '(', ')'),
                                                                      array('\?', '\*', '\+', '\(', '\)'),
                                                                      $tx['urichar']['org'])),`
Leider gehen hier die Code-Formatierungen verloren.

**Comment by frase-git** [comment]
Bevor ich jetzt stundenlang mit ungewissem Ausgang experimentiere, frage ich lieber nochmal nach:
Was und womit sollen wir testen?
XH 1.7.2 mit Pagemanager 3.2? Alles auf Standard?

> Leider gehen hier die Code-Formatierungen verloren.

Welche? Wie kann ich das nachvollziehen?

**Comment by olape-git** [comment]
Ich habe das jetzt erst mal mit der originalen 1.7.2 und Pagemanger 3.2 gemacht.
Testen? Die Funktionen des Pagemanagers halt. Das was hier gestern nicht funktioniert hatte, bzw. natürlich auch das was schon immer und hoffentlich auch weiterhin funktioniert, also bitte auch ÄÖÜäöüß mit reinnehmen!
Die Code-Formatierungen hier auf GitHub, also Zeilenumbrüche und Einrückungen. Erst mal nicht von Belang.

**Comment by frase-git** [comment]
> Die Code-Formatierungen hier auf GitHub, also Zeilenumbrüche und Einrückungen. Erst mal nicht von Belang.

https://guides.github.com/features/mastering-markdown/
oder
https://www.heise.de/tipps-tricks/GitHub-Seiten-mit-Markdown-gestalten-4575536.html

**Comment by frase-git** [comment]
# Testbericht
XH 1.7.2 unberührt
Pagemanager 3.2 unberührt

Änderungen [von hier](https://github.com/cmsimple-xh/cmsimple-xh/issues/413#issuecomment-623110669) eingearbeitet - mit Leerzeichen

2 Seiten angelegt:
Titel 1 = "Test &&& Test"
Titel 2 = "test:test/test?test#test[test]test@test!test$test&test'test(test)test*test+test,test;test="

Solange die Seiten nicht bearbeitet sind (leer) kommt in der Adresse immer noch das "amp" an den entsprechenden Stellen.

Bearbeitet man und speichert, dann sind die "amp"s weg.

Jeder weitere Speichervorgang im Pagemanager  bringt aber die "amp"s wieder an die Adressen zurück. Man muss dann die Seiten wieder speichern (bearbeiten), damit es wieder OK ist.

Mit anderen Worten: Es funktioniert noch nicht sauber.
Und: Es **scheint** am Pagemanager zu liegen!

Sollten wir das nicht vorläufig zurückstellen (lassen, wie es war) und erstmal 1.7.3 fertig machen?

**Comment by olape-git** [comment]
Zurückstellen können wir immer (noch).
Ich habe (oben) die Zeilen für die Sprachdateien angepasst.
Bei mir funktioniert es.

**Comment by frase-git** [comment]
> Ich habe (oben) die Zeilen für die Sprachdateien angepasst.

Du Schlingel, du! Einfach den Code oben ändern ... ts, ts, ts.

Aber gut. Mit den jetzigen Änderungen scheint es zu funktionieren. Die "amp"s tauchen nicht mehr auf und es ändert sich beim Speichern auch nichts mehr.

Jetz warten wir noch Ludwigs Tests ab.
Dann simmer dorsch dadormit.

**Comment by lck-git** [comment]
> Ist jetzt erst mal in der 3.2, aber ich glaube, 3.3 ist in dem Punkt identisch.

Ja ist es. Habe mit Pagemanager 3.3 verglichen und auch gestestet.

Also, das ist noch nicht ausgestanden.
Testet mal den Seitennamen "Notepad ++" oder "C++" oder "C++ Kurs".
Ergebnis in der URL "?Notepad", "?C" und "?C-Kurs".
Sollte eigentlich nach urichar sein "?Notepad---", "?C--" und "?C---Kurs".

Und, die Leerzeichen werden von XH oder durch die Browser(?) sowieso nicht angezeigt. Somit ist die Ersetzung in urichar gar nicht nötig.

**Comment by olape-git** [comment]
Doch, das ist, wenn sonst nix ist, ausgestanden. Du musst nur eine Differenz zwischen der Ersetzung und dem Word_Separator schaffen, dann hast du, was du willst.
Ich hatte es hier https://github.com/cmsimple-xh/cmsimple-xh/issues/413#issuecomment-622982558 schon erklärt.
Du kannst nämlich auch eine Seite C----- anlegen und bekommst nur C.
Der Separator wird auf max. 1 reduziert, steht er am Ende fällt er weg.
Das ist aber schon lange so. 

Leerzeichen sollte der Browser mit %20 quittieren.

**Comment by frase-git** [comment]
> Testet mal den Seitennamen "Notepad ++" oder "C++" oder "C++ Kurs".

Man, du bist aber sehr einfallsreich bei deinen Tests.
UND DAS IST GUT SO!
Ich denke allerdings, dass es Seitennamen "Notepad ++" sowieso gar nicht geben kann/dürfte. Der User sollte ohnehin in solchen Fallen "Notpad pluplus" schreiben. Oder eine eigene Ersetzung "+ => plus" verwenden.

**Comment by lck-git** [comment]
> [olape-git wrote:]
Ich hatte es hier [#413 (comment)](https://github.com/cmsimple-xh/cmsimple-xh/issues/413#issuecomment-622982558) schon erklärt.
> Du kannst nämlich auch eine Seite C----- anlegen und bekommst nur C.
> Der Separator wird auf max. 1 reduziert, steht er am Ende fällt er weg.

Ok, ja dann, sollte es so passen.

> [olape-git wrote:]
Leerzeichen sollte der Browser mit %20 quittieren.

Eigentlich nicht, weil in der Konfiguration bei Worttrennzeichen ja "-" eingestellt ist.

**Comment by lck-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/issues/413#issue-611183402
> default.php, en.php
> `$tx['urichar']['org']="&amp;| |'|§|%|:|/|?|#|[|]|@|!|$|&|'|(|)|*|+|,|;|=|\"";`

Da ist am Ende ein Gänsefüßchen bei `|\""` zu viel und auch hier bei `|\"|`

> de.php
> `$tx['urichar']['org']="&amp;| |'|§|%|:|/|?|#|[|]|@|!|$|&|'|(|)|*|+|,|;|=|\"|ä|ö|ü|ß|Ä|Ö|Ü";`

**Comment by olape-git** [comment]
> [#413 (comment)](https://github.com/cmsimple-xh/cmsimple-xh/issues/413#issue-611183402)
> 
> > default.php, en.php
> > `$tx['urichar']['org']="&amp;| |'|§|%|:|/|?|#|[|]|@|!|$|&|'|(|)|*|+|,|;|=|\"";`
> 
> Da ist am Ende ein Gänsefüßchen bei `|\""` zu viel und auch in de.php bei `|\"|`
> 
> > de.php
> > `$tx['urichar']['org']="&amp;| |'|§|%|:|/|?|#|[|]|@|!|$|&|'|(|)|*|+|,|;|=|\"|ä|ö|ü|ß|Ä|Ö|Ü";`

Nein, das ist korrekt so, das soll genau das " treffen

**Comment by olape-git** [comment]
> > [olape-git wrote:]
> > Ich hatte es hier [#413 (comment)](https://github.com/cmsimple-xh/cmsimple-xh/issues/413#issuecomment-622982558) schon erklärt.
> > Du kannst nämlich auch eine Seite C----- anlegen und bekommst nur C.
> > Der Separator wird auf max. 1 reduziert, steht er am Ende fällt er weg.
> 
> Ok, ja dann, sollte es so passen.
> 
> > [olape-git wrote:]
> > Leerzeichen sollte der Browser mit %20 quittieren.
> 
> Eigentlich nicht, weil in der Konfiguration bei Worttrennzeichen ja "-" eingestellt ist.

Ja, da hast du recht, deswegen ist das Leerzeichen in der Ersetzung tatsächlich auf überflüssig, aber auch nicht falsch.

**Comment by lck-git** [comment]
> > [#413 (comment)](https://github.com/cmsimple-xh/cmsimple-xh/issues/413#issue-611183402)
> > > default.php, en.php
> > > `$tx['urichar']['org']="&amp;| |'|§|%|:|/|?|#|[|]|@|!|$|&|'|(|)|*|+|,|;|=|\"";`
> > 
> > 
> > Da ist am Ende ein Gänsefüßchen bei `|\""` zu viel und auch in de.php bei `|\"|`
> > > de.php
> > > `$tx['urichar']['org']="&amp;| |'|§|%|:|/|?|#|[|]|@|!|$|&|'|(|)|*|+|,|;|=|\"|ä|ö|ü|ß|Ä|Ö|Ü";`
> 
> Nein, das ist korrekt so, das soll genau das " treffen

Ok, dann ist der Backslash \ zuviel. `|\"` (oder sehe ich das falsch?).
Ergibt dann gespeichert in der de.php `|\\\"` und das `"` wird in der URL nicht ersetzt, zumindest bei mir.

Getestet habe ich mit Seitennamen `Test start"end Test`.
Bei Pagemanager Vorschau gibts dann auch wieder Probleme mit %.. in der URL und nach dem Bearbeiten der Seite und speichern wird aus dem Seitennamen `Test start`.

**Comment by olape-git** [comment]
> Getestet habe ich mit Seitennamen `Test start"end Test`.
> Bei Pagemanager Vorschau gibts dann auch wieder Probleme mit %.. in der URL und nach dem Bearbeiten der Seite und speichern wird aus dem Seitennamen `Test start`.

Ah..., jetzt kommen wir der Sache näher. Ich habe oben die gesamte Variable angegeben. Und die muss so aussehen. Wenn du das übers Backend eingibst, dann natürlich ohne den Backslash, denn den setzt XH automatisch davor.

**Comment by lck-git** [comment]
> Wenn du das übers Backend eingibst, dann natürlich ohne den Backslash, denn den setzt XH automatisch davor.

Mein Fehler. Nun scheint es zu passen!

**Comment by olape-git** [comment]
> Mein Fehler. Nun scheint es zu passen!

Wieso Fehler? Man muss nur darüber reden.

Es passt, das ist gut. 

Alles in allem macht es aber deutlich, wie Fehleranfällig die Sache ist.
Da sind unter anderem Reihenfolgen zu beachten, bei mehr als 5 Zeichen oder gar Zeichenfolgen  ist die Übersichtlichkeit dahin.
Es ist also, wichtig, dann im nächsten Schritt (1.8), die Sache so zu gestallten, dass diese Dinge automatisch abgehandelt werden, ohne das der User Fehler einbauen kann.

**Comment by lck-git** [comment]
> Alles in allem macht es aber deutlich, wie Fehleranfällig die Sache ist.
> Da sind unter anderem Reihenfolgen zu beachten, bei mehr als 5 Zeichen oder gar Zeichenfolgen ist die Übersichtlichkeit dahin.
> Es ist also, wichtig, dann im nächsten Schritt (1.8), die Sache so zu gestallten, dass diese Dinge automatisch abgehandelt werden, ohne das der User Fehler einbauen kann.

**+1**

**Comment by cmb69** [comment]
> Problemverursacher sind also : ? * ( ) +
> Eventuell müsste man diese Zeichen maskieren?

Ich denke, da fehlt eigentlich ein [`preg_quote()`](https://www.php.net/preg_quote), also im Prinzip das, was [Olafs Patch](https://github.com/cmsimple-xh/cmsimple-xh/issues/413#issuecomment-623110669) per `str_replace()` macht, aber eben nach dem "exploden". Schau ich mir im Lauf des Tages noch genauer an.

> Es ist also, wichtig, dann im nächsten Schritt (1.8), die Sache so zu gestallten, dass diese Dinge automatisch abgehandelt werden, ohne das der User Fehler einbauen kann.

Ja, unbedingt. Das ganze urichar_(old|new) ist schon eine ziemliche Krücke. Leider sind die in PHP eingebauten Lösungen nicht unbedingt verfügbar (`//TRANSLIT` mit [`iconv()`](https://www.php.net/manual/en/function.iconv.php), oder [`Transliterator`](https://www.php.net/manual/en/class.transliterator.php)).

**Comment by cmb69** [comment]
> Schau ich mir im Lauf des Tages noch genauer an.

[Erledigt](https://github.com/cmb69/pagemanager_xh/issues/63).

**Comment by manu37** [comment]
> 
> Update:
> Ich habe es doch noch gefunden #357

Ohne die ganze Bibel gelesen und verstanden zu haben, gehe ich davon aus, das damit genau dieser Fehler in #357 behoben ist. Dazu stimme ich ja

**Comment by manu37** [comment]
Naja, seis drum. Es ist ein gewisser Informationsverlust. ?Start/Start [de] neben ?Start/Start (de) ist nicht mehr möglich. Als patch reicht es. In der Hoffung, in 1.8 eine optimierte Lösung zu haben.

**Comment by cmb69** [comment]
````.php
$cf['urichar']['org'] = "…|[|]|(|)|…";
$cf['urichar']['new'] = "…|eckige Klammer auf|eckige Klammer zu|runde Klammer auf|runde Klammer zu";
````
:p

**Comment by olape-git** [comment]
> Als patch reicht es. In der Hoffung, in 1.8 eine optimierte Lösung zu haben.

Aber daran, dass die reservierten Zeichen aus der URI verschwinden (müssen) wird auch ein optimierter Patch nichts ändern.
Hauptsächlich geht es in der 1.8 darum, die reservierten Zeichen aus org und new raus zu bekommen, um irgendwie eine Übersichtlichkeit zu bewahren und Fehler bei diesen Zeichen zu vermeiden (denke ich).
Christoph hatte auch schon mal einen [Vorschlag](https://cmsimpleforum.com/viewtopic.php?f=16&t=12940&hilit=urlify&start=40#p63080) gemacht. 
Ich finde die Idee nach wie vor gut.

**Comment by manu37** [comment]
Ist diese Diskussion angeschlossen, der PR schlüssig? Ich habe etwas den Überblick verloren. Abgestimmt haben wir ja.

**Comment by olape-git** [comment]
Es sind ja nur Ersetzungen, also nix Dramatisches. Ich denke, da gibt es keine Probleme, da es ja auch nur Neuinstallationen betrifft. Christoph behebt den Bug im Pagemanager, dann passt das alles.

**Comment by manu37** [comment]
#432

**Comment by frase-git** [comment]
A little side note:
I just had a project where I had page names like:
"General Terms and Conditions (GTC)"
or
"Logistics / Dates / Order processing"
and some other exotic things.
And at least in these cases the character substitution worked very well and was very convenient.
Again, "Thanks" to everyone involved for this feature.
Special thanks to @olape-git for his persistence.

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/commit/c655510f98555a98aae5373ce9adba9c903f1e19
