### ISSUE TITLE
Where have all the Travis CI checks gone?

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#418]
Der letzte ausgeführte Travis CI Check war hier: 117986e5fc7b96095ab9d4cff6a763f42c9368a6.
Seither keine Checks mehr. @TN03 Holger, kennst Du Dich aus?

**Comment by cmb69** [comment]
Laut [Projektübersicht](https://travis-ci.org/github/cmsimple-xh/cmsimple-xh/branches) lief die CI zuletzt gestern.

**Comment by manu37** [comment]
Hallo Christoph
Schön von Dir zu hören.
Dass die Tests laufen (scheitern) habe ich auch bemerkt, aber sie werden auf GitHub nicht mehr angezeigt. Wahrscheinlich weil sie schon in der pre_script phase scheitern. Kannst Du mir einen Tipp geben?
Gruss
manu

**Comment by TN03** [comment]
Hmm, trat zuerst bei diesem Job auf: https://travis-ci.org/github/cmsimple-xh/cmsimple-xh/jobs/687091006 ???
Keine Ahnung, warum mit PHP 7.3 kein Output kommt. 
Und was ist eigentlich mit PHP 7.4? Das hatte ich doch bereits integriert...

**Comment by manu37** [comment]
Ist es hier nicht der composer install, der ins Nirvana läuft? Stimmt evtl. etwas mit der [composer.json](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7/composer.json) nicht (evtl. Versionen)?

**Comment by cmb69** [comment]
> Keine Ahnung, warum mit PHP 7.3 kein Output kommt.

Könnte ein allgemeines [Problem bzgl. Xdebug und uopz](https://github.com/krakjoe/uopz/issues/122) sein. Ich denke, dass es keine gute Idee ist beide Extensions gleichzeitig zu nutzen. Xdebug wird für CI eigentlich nicht benötigt (wenn ich mich nicht irre), aber von Travis bereit gestellt. Ich wüsste nicht, wie man Xdebug deaktivieren kann; vermutlich müsste die php.ini angepasst werden. /S

> Und was ist eigentlich mit PHP 7.4? Das hatte ich doch bereits integriert...

In der [build matrix](https://github.com/cmsimple-xh/cmsimple-xh/blob/master/.travis.yml) fehlt es aber aus irgendeinem Grund.

**Comment by cmb69** [comment]
> Ich wüsste nicht, wie man Xdebug deaktivieren kann; […]

Gerade gefunden: https://docs.travis-ci.com/user/languages/php/#disabling-preinstalled-php-extensions

**Comment by manu37** [comment]
Danke für den PR, Christoph.
Wie gehen wir weiter vor? Gibt es eine Möglichkeit, bei den PRs, bei denen die Travis CI Tests gescheitert sind, die Tests zu wiederholen? @TN03 Holger, könntest Du den PHP 7.4 Test nochmals ergänzen?
merci und Gruss manu

**Comment by TN03** [comment]
> Danke für den PR, Christoph.
Wie gehen wir weiter vor? Gibt es eine Möglichkeit, bei den PRs, bei denen die Travis CI Tests gescheitert sind, die Tests zu wiederholen?

Es ist doch so konfiguriert, dass die Tests nach einem commit automatisch im Buildprozess ausgeführt werden. Manuelles anstoßen eines Builds geht natürlich auch.

> In der build matrix fehlt es aber aus irgendeinem Grund.

Ja. Fehlinfo meinerseits.
PHP 7.4 könnten wir aber mal testweise mit aufnehmen, wenn wieder alles funktioniert.

**Comment by TN03** [comment]
Ich habe den PR https://github.com/cmsimple-xh/cmsimple-xh/pull/419 jetzt mal übernommen. Die Tests laufen nun alle wieder durch.

**Comment by TN03** [comment]
> PHP 7.4 könnten wir aber mal testweise mit aufnehmen, wenn wieder alles funktioniert.

Die Doku sagt:

> PHP` 7.4(.x) onwards support is available on Trusty, Xenial and Bionic only

Wir laufen auf Xenial. Sollte also funktionieren :).

**Comment by cmb69** [comment]
> Wir laufen auf Xenial. Sollte also funktionieren :).

Leider nicht von unserer Seite her. PHPUnit 5.7 selbst löst unter PHP 7.4 Deprecation-Hinweise aus (`ReflectionType::__toString()`); verstehe zwar nicht, warum nicht unter PHP 7.3, da die Methode schon seit 7.1 deprecated ist, aber erst mal egal. Neuere PHPUnit-Versionen sind aber nicht mehr mit PHP 5.6 kompatibel, und ich wüsste nicht wie man das mit einem einzigen composer.json handhaben könnte. Auch erst mal egal; einfach mal PHPUnit 6.5 probiert: "PHPUnitTask requires PHPUnit to be installed". Da scheint Phing 2.16 wohl nicht kompatibel zu PHPUnit 6.5. Also mit den Änderungen aus PR #424 probiert: "Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found". Also PR #426. Nun können die unit-tests immerhin ausgeführt werden, aber: "There were 59 errors:" :(

Angesichts der zügigen Entwicklung von PHP und PHPUnit ist es vielleicht das beste, für den 1.7 Branch auf PHP 7.4 Jobs zu verzichten, und statt dessen zu überlegen, ob es für master nicht sinnvoll ist, auf PHP 5 zu verzichten (zumindest auf die CI-Jobs).

**Comment by manu37** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/commit/98d065204d7971ebd7c2deba011a4dbd1b7782de
