### ISSUE TITLE
xh_styles.css

### ISSUE THREAD

**Issue by g7sim** [cmsimple-xh/cmsimple-xh#435]
XH_styles.css is 18.9 KB big and also loaded if not logged in. It should be possible to load it under condition : if adm{ $o .= ..}  in tplfuncs.php line 93-94 (may cause problems if some plugin-csses are needed in the template - better forget the proposal - too complicated)

**Comment by lck-git** [comment]
See discussion here: https://cmsimpleforum.com/viewtopic.php?t=13242
