### ISSUE TITLE
final tests 1.7.3

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#438]
https://github.com/cmsimple-xh/cmsimple-xh/commit/c80a7cab642f238df88c798dedadaca7ccbb4947#r40665102

**Comment by cmb69** [comment]
Was machen wir mit jQuery? Die Versionen im 1.7 Branch sind furchtbar alt.

**Comment by olape-git** [comment]
Ja, das ist Mist. 
Wäre ja eigentlich Holgers Part. Aber der scheint momentan keine Zeit zu haben.

**Comment by manu37** [comment]
Ja eben. Mir ist kein Problem bekannt, das die alte Version verursachen würde. Darum habe ich die Aktualisierung in einen zukünftigen Release verschoben.

**Comment by TN03** [comment]
Ich bin ab kommenden Donnerstag wieder Zuhause. Dann könnte ich das erledigen.
Vorher geht leider nicht :(

**Comment by cmb69** [comment]
Können wir nicht einfach die neuste jQuery-Version (3.5.1) mit ausliefern, und in der Release-Ankündingung darauf hinweisen, dass diese verwendet werden sollte (nach vorherigen Tests), weil ältere Versionen möglicherweise relevante [Sicherheitslücken enthalten](https://snyk.io/vuln/npm:jquery) (und vielleicht auch sonstige Probleme mit neueren Browserversionen).

> Ich bin ab kommenden Donnerstag wieder Zuhause. Dann könnte ich das erledigen.
Vorher geht leider nicht :(

Na, das klingt noch besser. :)

**Comment by manu37** [comment]
@cmb69 Könntest Du einen PR von https://github.com/cmb69/cmsimple-xh/tree/filebrowser-look-and-feel machen?
https://cmsimpleforum.com/viewtopic.php?f=42&t=15876&p=76052#p76048
merci

**Comment by cmb69** [comment]
Ah, ja gemacht: https://github.com/cmsimple-xh/cmsimple-xh/pull/439

**Comment by frase-git** [comment]
> Ah, ja gemacht: #439 

Ein dickes "Dankeschön" speziell von mir und höchstwahrscheinlich auch von den andern ;-)

**Comment by cmb69** [comment]
Das dickere Dankeschön gebührt @manu37 ohne den 1.7.3 wohl noch lange auf sich warten lassen müsste. :)

**Comment by manu37** [comment]
> 
> 
> Können wir nicht einfach die neuste jQuery-Version (3.5.1) mit ausliefern, und in der Release-Ankündingung darauf hinweisen, dass diese verwendet werden sollte (nach vorherigen Tests), weil ältere Versionen möglicherweise relevante [Sicherheitslücken enthalten](https://snyk.io/vuln/npm:jquery) (und vielleicht auch sonstige Probleme mit neueren Browserversionen).
> 
> > Ich bin ab kommenden Donnerstag wieder Zuhause. Dann könnte ich das erledigen.
> > Vorher geht leider nicht :(
> 
> Na, das klingt noch besser. :)

Für mich ist es ok, wenn jQuery mit eingeschaltetem Migrate ausgeliefert wird. Es sollte aber hingewiesen werden, dass diese Einstellung nur für Testzwecke sinnvoll ist. Die Console Meldungen sollten dann berücksichtigt und dann nach Erfolg die Migrate Einstellung ausgeschaltet werden.

**Comment by manu37** [comment]
Um der Anleitung für den [Rollout ](https://wiki.cmsimple-xh.org/doku.php/release_a_new_version)zu folgen, stellt sich die Frage, wer die www.cmsimple-xh.org aktualisiert. Wer hat den Zugang zu www.heise.de, etc.?

**Comment by lck-git** [comment]
[heise.de](https://www.heise.de/download/product/cmsimple-xh-91863?hg=1&hgi=3&hgf=false) das machte svasti (siehe [Forum](https://cmsimpleforum.com/viewtopic.php?f=16&t=13246&p=64479&hilit=Heise#p64486)), er hat aber damals schon auf Anfragen von Hartmut nicht reagiert. Das müsste dringend geändert werden, zum Dowload wird zwar  XH 1.7.2 beschrieben, aber der Download selber beinhaltet XH 1.6.9. Ausserdem sind die Bilder nicht aktuell, entsprechen nicht XH 1.7.2.

[http://www.cmsimple-xh.org/](http://www.cmsimple-xh.org/) macht Olaf. Christoph macht [opensourcecms, cmsmatrix und hotscripts](https://cmsimpleforum.com/viewtopic.php?f=16&t=8894#p48507).

**Comment by lck-git** [comment]
> [cmb69 wrote:] Das dickere Dankeschön gebührt @manu37 ohne den 1.7.3 wohl noch lange auf sich warten lassen müsste. :)

**+1** und Olaf nicht vergessen, der viel Zeit investiert hat und immer die Sache vorangetrieben hat! Auch Frank war fleißig und hat viel beigesteuert. Aber, wir sind noch nicht am Ende angelangt. Heben wir uns den Applaus für die Veröffentlichung von XH 1.7.3 auf.

**Comment by olape-git** [comment]
> wer die [www.cmsimple-xh.org](http://www.cmsimple-xh.org) aktualisiert.
Du meinst die Downloads, oder die Seite selbst? Beides würde ich machen. Allerdings erst nach Veröffentlichung auf Git.
Bei der Seite selbst sind zwei drei Anpassungen nötig. Muss ich selber erst wieder schauen.

Ansonsten habe ich bisher nur kurz antesten können, bisher ohne Probleme.

**Comment by lck-git** [comment]
Test. Ok, neuer Filebrowser ist drin :+1:. Sollte man hier nicht auch mal eine version.nfo hinzufügen?

Problem:
Updatecheck schlägt bei mir bei **jQuery** und **hi_updatecheck** fehl. Kann das jemand bestätigen?

**Comment by cmb69** [comment]
> Sollte man hier nicht auch mal eine version.nfo hinzufügen?

Da der Filebrowser nicht separat ausgeliefert wird, macht das eigentlich keinen Sinn.

> Updatecheck schlägt bei mir bei jQuery und hi_updatecheck fehl. Kann das jemand bestätigen?

Ja, da http://cmsimple.holgerirmler.de/downloads/versioninfo/hi_updatecheck_version.nfo.

**Comment by frase-git** [comment]
www.holgerirmler.de scheint komplett offline zu sein.

**Comment by lck-git** [comment]
Test Filebrowser > Donloads > Datei hochladen.
Problem bei sehr kleinen Dateien mit nur ein paar Zahlen drin. Der Debug-Mode meldet beim Upload:

> NOTICE: getimagesize(): Read error!
D:\xampp\htdocs\cmsimplexh173_master\plugins\filebrowser\classes\Controller.php:455

**Comment by frase-git** [comment]
> www.holgerirmler.de scheint komplett offline zu sein.

War offensichtlich nur ein Aussetzer ;-)
Dafür ist meine Seite gerade nicht erreichbar :(
Internet - rrrrrrrrrrrrrr!

**Comment by lck-git** [comment]
> War offensichtlich nur ein Aussetzer ;-)

Stimmt, jetzt geht's! Gut das mehrere testen.

**Comment by lck-git** [comment]
**Template fhs-simple-2019**

Vorschlag für Backend Info-Seite (sysinfo)
Um das übersichtlicher zu machen, könnte man die p-Tags und evtl. die ul speziell auf dieser Seite anders gestalten per:
Einfach vor dem `</head>` einfügen.
> <?php
if (XH_ADM && $sysinfo) {
    echo '<style>.maincont p {margin: 1.5em 0 0} ul {list-style: none}</style>';
}
?>

**Comment by cmb69** [comment]
> Problem bei sehr kleinen Dateien mit nur ein paar Zahlen drin.

Ah, nicht unbekannt. Könnte man als PHP-Fehler einstufen ([`php_getimagetype`](https://github.com/php/php-src/blob/php-7.3.20/ext/standard/image.c#L1301) erzeugt eine Notice, wenn nicht genügend Daten gelesen werden konnten). Wir könnten das abfangen, indem wir prüfen, ob die Datei wenigstens 12 Byte groß ist (nur WBMP, das nicht Windows BMP ist, und XPM können kleiner sein, aber die spielen für uns keine Rolle).

**Comment by frase-git** [comment]
> Vorschlag für Backend Info-Seite (sysinfo)
> Um das übersichtlicher zu machen, könnte man die p-Tags und evtl. die ul speziell auf dieser Seite anders gestalten per:
> Einfach vor dem </head> einfügen.

Ja, guud, äähh ...
Wenn schon, dann aber auch für "settings", also:
```
<?php
if (XH_ADM && $sysinfo || XH_ADM && $settings) {
echo '<style>.maincont p {margin: 1.5em 0 0} ul {list-style: none}</style>';
}
?>
```
Aber: Bitte jetzt keine PRs mehr !!!
Wir leben mit so vielen Kompromissen, da kommt es auf die paar "Listen-Punkte" auch nicht mehr an.
Irgendwann - vielleicht bei Version 2.0 (falls es die je geben wird) - müssen wir uns wirklich mal ernsthaft mit der Trennung von CMS-Settings und Page-Layout  beschäftigen. Auf diese (neuerliche) Diskussion freue ich mich jetzt schon ;-)

**Comment by cmb69** [comment]
> Irgendwann - vielleicht bei Version 2.0 (falls es die je geben wird) - müssen wir uns wirklich mal ernsthaft mit der Trennung von CMS-Settings und Page-Layout beschäftigen. Auf diese (neuerliche) Diskussion freue ich mich jetzt schon ;-)

https://caniuse.com/#feat=shadowdomv1 :)

**Comment by manu37** [comment]
> 
> 
> **Template fhs-simple-2019**
> 
> Vorschlag für Backend Info-Seite (sysinfo)
> Um das übersichtlicher zu machen, könnte man die p-Tags und evtl. die ul speziell auf dieser Seite anders gestalten per:
> Einfach vor dem `</head>` einfügen.
> 
> > if (XH_ADM && $sysinfo) {
> > echo '<style>.maincont p {margin: 1.5em 0 0} ul {list-style: none}</style>';
> > }
> > ?>

finde ich jetzt etwas gewurstelt um 5vor12. Wieso nicht in den adminfuncs eine Klasse zuweisen und das css anpassen?

**Comment by frase-git** [comment]
> finde ich jetzt etwas gewurstelt um 5vor12.

Genau. Deshalb schrieb ich ja: "Bitte jetzt keine PRs mehr !!!"
Soll heißen: Keine Änderungen für 1.7.3

**Comment by lck-git** [comment]
> finde ich jetzt etwas gewurstelt um 5vor12. Wieso nicht in den adminfuncs eine Klasse zuweisen und das css anpassen?

Weil das in dem Fall der einfachste Weg ist. Eine Änderung in adminfuncs könnte zu einem BC-Breack führen, das sollten wir auf 2.0 verschieben.



> Genau. Deshalb schrieb ich ja: "Bitte jetzt keine PRs mehr !!!"

Das ist kein PR, "... Vorschlag ... könnte ...."

**Comment by TN03** [comment]
Das jQuery-Plugin ist hier im Master aktualisiert: https://github.com/TN03/jQuery_XH
Bitte mal testen, wenn nötig / möglich.
Welche Version soll denn nun voreingestellt werden?
Wenn das klar ist, mache ich dann ein Release welches dann integriert werden kann.

**Comment by lck-git** [comment]
:thumbsup:
Getestet, keine Probleme bisher festgestellt.

> Welche Version soll denn nun voreingestellt werden?

IMHO mindestens Core 3.2.1, das sollte bei den meisten Usern passen.

**Comment by manu37** [comment]
getestet mit Core 3.5.1 und migrate 3.3.0: Da gibt es wenige deprecated meldungen - eher kosmetisch. Er meckert eher über seinen eigenen jquery UI (wieso ist der überhaupt eingeschaltet?).
Meine Bedenken sind eher: bisher war bisher war Core 1.12.4 mit eingeschaltetem migrate 1.4.1min. Wenn also jemand schon mit dieser Einstellung deprecated warnungen erhalten hat, hat er's wohl gar nicht mitbekommen.
Auf keinen Fall ist in diesem release ein BC Break erwünscht. Daher würde ich IHMO die neuen libs ausliefern, aber die alten Einstellungen belassen. Irgenwo sollten wir aber einen Aufruf an die jQuery User machen, den aktuelle core mit migrate (ohne min, damit die warnings auch ins log geschrieben werden) zu testen und zu aktualisieren. Wir im core natürlich auch (zwei kleine kosmetische warnings im template).

**Comment by cmb69** [comment]
> Auf keinen Fall ist in diesem release ein BC Break erwünscht.

Sehe ich auch so, auch wenn es bedauerlich ist, dass wir dann eine nicht länger gewartete Version als default ausliefern.

**Comment by frase-git** [comment]
@manu37 wrote:
> Auf keinen Fall ist in diesem release ein BC Break erwünscht. Daher würde ich IHMO die neuen libs ausliefern, aber die alten Einstellungen belassen.

Auch, wenn das einigermaßen "schizo" ist, dem stimme ich zu.
Der Normalfall wäre, die neuesten Versionen als Standard in die Config zu schreiben.
Dann gäbe es allerdings ziemlich viele Probleme (aus eigener Erfahrung weiß ich, dass es manchmal sogar eine 2er Version braucht).

Und übrigens: Auch hier ein besonderes Dankeschön an @TN03 Holger - mir ist echt ein Stein vom Herzen gefallen, weil du weiterhin dabei bist. Ich hatte schon schlimme Dinge befürchtet.

Lassen wir unser liebes, gutes, altes XH nicht sterben. Das Ding hat so viel Potenzial, dass es viele andere CMSse einfach im Schatten stehen lässt. Das verdanken wir _uns allen - selbst_!

**Comment by TN03** [comment]
Ich sehe das auch so und hab das Update dann erledigt. Merge von 1.7 -> Master habe ich gleich mit erledigt, siehe https://github.com/cmsimple-xh/cmsimple-xh/pull/440 .

BTW: ich habe die Releases und Versions-Infos für das Plugin komplett nach GitHub verschoben. 
Wer hat denn hier Zugriff: https://wiki.cmsimple-xh.org/doku.php/extend:jquery4cmsimple ?
Dort müsste der Download-Link entsprechend auf https://github.com/TN03/jQuery_XH/releases angepasst werden.

**Comment by TN03** [comment]
> Er meckert eher über seinen eigenen jquery UI (wieso ist der überhaupt eingeschaltet?).

Hmm. Das ist per Default nicht eingeschaltet???

**Comment by manu37** [comment]
> 
> 
> > Er meckert eher über seinen eigenen jquery UI (wieso ist der überhaupt eingeschaltet?).
> 
> Hmm. Das ist per Default nicht eingeschaltet???

https://github.com/cmsimple-xh/cmsimple-xh/blob/badad81f517508031a8fb62f7d7935e9f1741c0f/plugins/jquery/admin.php#L71
;-)

**Comment by manu37** [comment]
Meiner meinung nach sind wir durch. Wenn jetzt nichts mehr reinschneit, beginne ich mal mit dem [release a new version](https://wiki.cmsimple-xh.org/doku.php/release_a_new_version). ok so?

**Comment by lck-git** [comment]
Sorry Leute 🤕, hatte vergessen reqcheck.php zu testen. Dieser meldet unter Xampp mit PHP 7.4.4 folgendes:

> Deprecated: Function get_magic_quotes_runtime() is deprecated in D:\xampp\htdocs\cmsimplexh173_master\reqcheck.php on line 36

**Comment by lck-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/blob/8d548cc9142bfe96d6f558204cc3c4d54c254f0d/reqcheck.php#L36

Müsste wohl geändert werden zu

`$checks['magic_quotes_runtime is off'] = !ini_get('get_magic_quotes_runtime()') ? 'okay' : 'warn';`

**Comment by cmb69** [comment]
Danke, sehr gut, @lck-git! Mach ich gleich.

Aber grundsätzlich müssen wir reqcheck.php noch überdenken. Wenn das vor/nach der eigentlichen Installation nicht gelöscht wird, dann gibt es ein permanentes Information-Leak (phpinfo kann von jedermann eingesehen werden). Nicht sicher, ob es genügt, dass prominent zu dokumentieren.

**Comment by lck-git** [comment]
> Mach ich gleich. (erledigt: [f2f5b64](https://github.com/cmsimple-xh/cmsimple-xh/commit/f2f5b644aab00f13c34ef40a0ae19a1aac050597))

Super! Getestet, passt.

**Comment by cmb69** [comment]
> Wer hat denn hier Zugriff: https://wiki.cmsimple-xh.org/doku.php/extend:jquery4cmsimple ?

U.a. ein gewisser "holger". Falls du das Passwort vergessen hast, siehe https://wiki.cmsimple-xh.org/doku.php/extend:jquery4cmsimple?do=resendpwd

Ich habe den Download-Link aktualisiert.

**Comment by manu37** [comment]
> 
> 
> Danke, sehr gut, @lck-git! Mach ich gleich. (erledigt: [f2f5b64](https://github.com/cmsimple-xh/cmsimple-xh/commit/f2f5b644aab00f13c34ef40a0ae19a1aac050597))
> 
> Aber grundsätzlich müssen wir reqcheck.php noch überdenken. Wenn das vor/nach der eigentlichen Installation nicht gelöscht wird, dann gibt es ein permanentes Information-Leak (phpinfo kann von jedermann eingesehen werden). Nicht sicher, ob es genügt, dass prominent zu dokumentieren.

Das heisst, PR #434 sollte noch rein, oder?

**Comment by cmb69** [comment]
> Das heisst, PR #434 sollte noch rein, oder?

Oh ja, auf jeden Fall. Aber damit allein ist es nicht getan; für eine Neuinstallation soll ja reqcheck.php hochgeladen werden, um zu prüfen, ob CMSimple_XH überhaupt auf dem Webspace laufen kann. Nach dieser Prüfung muss die Datei aber gelöscht werden, was durch einen Upload von CMSimple_XH nicht passiert (wir könnten natürlich eine leere reqcheck.php im cmsimplexh/ Ordner belassen, die die "gefährliche" echte reqcheck.php überschreiben würde).

**Comment by manu37** [comment]
Ich nehme diesem issue mal den Milestone weg, sonst erscheint unser Gemurmel in den release infos.

**Comment by cmb69** [comment]
Und ich mache das Issue mal zu; hat seinen Zweck erfüllt. :)
