### ISSUE TITLE
new startpage - strange behaviour

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#443]
Im eingeloggten Modus (View Mode) habe ich folgende Links zur Startseite:

- im Menü: "Start" > "?Start"
hier erscheint die Startseite

- im breadcrumb "Home" > ""
hier erscheint eine leere Seite ?!

Ist das ein alter Fehler/Wein in neuen Schläuchen?

im ausgeloggten Modus

- im Menü: "Start" > ""
hier erscheint die Startseite

- im breadcrumb "Home" > ""
hier erscheint die Startseite

Hier greift die neue Weiterleitung, alles ist ok.

Fragen:
Sollte die breadcrumb funktion nicht auch entsprechend angepasst werden: 
Wenn eingeloggt: Startseite explizit verlinken?

**Comment by frase-git** [comment]
Stimmt. Kann ich nachvollziehen.
Sollte korrigiert werden.

**Comment by cmb69** [comment]
Hmm, bei einer ganz frischen XH 1.7.3 Installation (ohne irgendwelche Änderungen), verhält sich das bei mir gleich (egal ob ausgeloggt oder eingeloggt im View- oder Editmode): im Locator "Start" bzw. "Home > Content". Liegt es vielleicht daran, dass bei IIS das index.php immer explizit erscheint?

**Comment by lck-git** [comment]
> [frase-git] Stimmt. Kann ich nachvollziehen.

Ich auch. Getestet mit Xampp und einem frischen XH 1.7.3.

> [manu37] Ist das ein alter Fehler/Wein in neuen Schläuchen?

In XH 1.7.2 war das nicht so.

**Comment by manu37** [comment]
Ich frage mich, wieso wir die neue XH_getPageUrl() nicht auch in [functions.php a()](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7/cmsimple/functions.php#L881) anwenden. Dann hätten wir die Korrekturen nur an einem Ort.

**Comment by olape-git** [comment]
also, wenn ich mich nicht vertan habe, dann wird XH_getPageUrl() derzeit nur von den XH_getLocatorModel(), XH_renderPrevLink(), XH_renderNextLink(), previouspage(), nextpage() genutzt. Wobei XH_renderPrevLink() und XH_renderNextLink() ja eh wegfallen sollen. prev und next jeweils beide sind auch erst in der 1.7.3 auf XH_getPageUrl() umgestellt.
Die notwendigen Änderungen sollten überschaubar sein, denke ich.
Das würde die Suche, Loginlink, ich glaube auch die Sitemap, möglicherweise sogar Submenu und Editor betreffen. Letzter zwei sind nur Bauchgefühl. Es ist also schnell wieder was vergessen oder versa...t

**Comment by olape-git** [comment]
`function a($i, $x)
{
    return '<a href="' . XH_getPageURL($i) . ($x ? ($x[$i] != '"' ? '?' . $x : $x) : '') . '">';
}`

**Comment by olape-git** [comment]
tja, aber die Suche funktioniert so nicht mehr :-(

**Comment by manu37** [comment]
Wir könnten das Pferd auch einmal andersrum aufzäumen und uns fragen:
Wieso wird die erste Seite im ausgeloggten Zustand mit leerem query angezeigt und im eingeloggten XH_ADM Zustand nicht?

**Comment by olape-git** [comment]
Darüber gab es längere Diskussionen. Herausgekommen ist, dass es aus SEO-Sicht besser ist, die erste Seite ohne Get-Parameter anzuzeigen. Das ging ja nun aber schon immer, nur es ging eben auch mit und das ist DC. Also musste "mit" weg.
Leider funktioniert das im Backend nicht so, wie du ja selber am Locator festgestellt hast. Deswegen der Umstand, dass das im Backend genau andersherum gehandhabt wird.
Warum das im Backend nicht funktioniert, dass kann ich dir gar nicht erklären. Christoph hatte mal versucht das rüber zu bringen, ich weiß es nicht mehr genau. Es kann jedenfalls nicht so einfach zu korrigieren sein, denn sonst hätten wir damals schon an diese Möglichkeit gedacht.

**Comment by cmb69** [comment]
Wenn `$su` (der 1. Query-Parameter, falls ohne Wertzuweisung) leer ist, dann weiß CMSimple_XH nicht, was es machen soll. Also werden alle Plugins geladen, und wenn dann [`$o` nicht leer ist](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.3/cmsimple/cms.php#L1255-L1258), geht das System davon aus, dass es nicht die erste Seite anzeigen soll. Im Adminmodus wird aber immer nach `$o` geschrieben, so dass die gewünschte Seite dort explizit angegeben werden muss.

**Comment by olape-git** [comment]
`function a($i, $x)
{
    $a_href = XH_getPageURL($i);

    if (stripos($a_href, '?') === false) {
        ($x ? $x = '?' . $x : '');
    }
    return '<a href="' . $a_href . $x . '">';
}`

So scheint es zu funktionieren. Allerdings nur 1.7.3 Grundinstallation. Ich weiß nicht, ob irgendwelche Plugins darauf vielleicht allergisch reagieren.

**Comment by manu37** [comment]
> So scheint es zu funktionieren. Allerdings nur 1.7.3 Grundinstallation. Ich weiß nicht, ob irgendwelche Plugins darauf vielleicht allergisch reagieren.

Wieso? Am Aufruf von a() ändert sich ja nichts.

**Comment by olape-git** [comment]
> Wieso? Am Aufruf von a() ändert sich ja nichts.
Da hast du sicher Recht
Das würde ich trotzdem gern noch etwas ausführlicher Testen.

**Comment by manu37** [comment]
Vielleicht ist es zu heiss, aber kann mir jemand den $x Parameter erklären? "Arbitrary appendix of the URL". Müsste da im else Fall nicht ein "&" vorangestellt werden?

**Comment by olape-git** [comment]
mal am Beispiel der Suche:
`$o .= '    <li>' . a($i, '&amp;search=' . urlencode($words)) . $title . '</a>';`

Das& ist also schon da.

**Comment by cmb69** [comment]
Genau; `a()` ist grausig, wird aber vermutlich auch von Plugins verwendet, so dass wir es nicht einfach ändern/entfernen können.

In https://github.com/cmsimple-xh/cmsimple-xh/issues/443#issuecomment-672807982 sieht der Body des if-Statement seltsam aus. Soll das einfach nur `if ($x) $x = "?$x";` sein?

**Comment by olape-git** [comment]
> In [#443 (comment)](https://github.com/cmsimple-xh/cmsimple-xh/issues/443#issuecomment-672807982) sieht der Body des if-Statement seltsam aus. Soll das einfach nur `if ($x) $x = "?$x";` sein?

Ja, das ist der Plan

**Comment by manu37** [comment]
> 
> 
> Wenn `$su` (der 1. Query-Parameter, falls ohne Wertzuweisung) leer ist, dann weiß CMSimple_XH nicht, was es machen soll. Also werden alle Plugins geladen, und wenn dann [`$o` nicht leer ist](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.3/cmsimple/cms.php#L1255-L1258), geht das System davon aus, dass es nicht die erste Seite anzeigen soll. Im Adminmodus wird aber immer nach `$o` geschrieben, so dass die gewünschte Seite dort explizit angegeben werden muss.

Richtig zum Einrahmen und an die Wand hängen! Könnte man so in die Dokumentation übernehmen.

**Comment by manu37** [comment]
> 
> 
> also, wenn ich mich nicht vertan habe, dann wird XH_getPageUrl() derzeit nur von den XH_getLocatorModel(), XH_renderPrevLink(), XH_renderNextLink(), previouspage(), nextpage() genutzt. Wobei XH_renderPrevLink() und XH_renderNextLink() ja eh wegfallen sollen. prev und next jeweils beide sind auch erst in der 1.7.3 auf XH_getPageUrl() umgestellt.
> Die notwendigen Änderungen sollten überschaubar sein, denke ich.
> Das würde die Suche, Loginlink, ich glaube auch die Sitemap, möglicherweise sogar Submenu und Editor betreffen. Letzter zwei sind nur Bauchgefühl. Es ist also schnell wieder was vergessen oder versa...t
> 
> Ah, ich glaub ich habe das schon wieder falsch verstanden. Nicht statt, sonder in.
> Auf die Idee hätten wir damals eigentlich auch schon kommen können.
> [cmb69@8864e33#commitcomment-27003965](https://github.com/cmb69/cmsimple-xh/commit/8864e336163471af27827e433aee597a22c5c786#commitcomment-27003965)

- submenu: IMO keine Anpassung nötig.
- search: geht über a(), gelöst.
- sitemap: geht über a(), gelöst.
- loginlink(): einziger Spezialfall, der aber jetzt schon die erste Seite explizit im query ausgibt. Gelöst.

**Comment by olape-git** [comment]
Wie wollen wir das nun machen?
Nur den Fix https://github.com/olape-git/cmsimple-xh/commit/7dee0b432bcc55b3dfacebaf3371a3c68e6dfbf9?

Oder die Änderung für fuction a() auch?

**Comment by manu37** [comment]
> 
> 
> Wie wollen wir das nun machen?
> Nur den Fix [olape-git@7dee0b4](https://github.com/olape-git/cmsimple-xh/commit/7dee0b432bcc55b3dfacebaf3371a3c68e6dfbf9)?
> 
> Oder die Änderung für fuction a() auch?

Ich würde a() anpassen, wie Du [hier ](https://github.com/cmsimple-xh/cmsimple-xh/issues/443#issuecomment-672807982)erwähnt hast.

**Comment by cmb69** [comment]
Ich habe grundsätzlich nichts dagegen auch `a()` anzupassen, aber wir sollten sicher sein, dass sich funktionell nichts ändert.

**Comment by lck-git** [comment]
BTW:
Im Backend beim Wechsel in eine andere Sprache wird ja auch keine Seite geladen, sondern es erscheint der Hinweis "Keine Seite ausgewählt" bzw. "No page selected", zumindest im Edit-Mode. Im View-Mode gibt's nur eine leere Seite.

Irgendwie nervt mich das immer etwas. Könnte man das auch mal mit anpacken, oder ist das eine größere Sache?

**Comment by olape-git** [comment]
Das ist aber auch schon in der 1.7.2 und sehr wahrscheinlich wenigstens runter bis min. 1.7.0 so.
Ich glaube, das wäre nicht wirklich kompliziert. Eine abfrage mehr.
Aber es wäre natürlich so, man würde immer auf der ersten Seite landen.
Das sieht vielleicht etwas besser aus, bring aber auch nicht wirklich Vorteile.

**Comment by olape-git** [comment]
Vielleicht könnte man besser immer auf `?&normal&xhpages` wechseln?

**Comment by frase-git** [comment]
Gibt man `?Seite-XYZ&login` ein, dann landet man richtig.

"Keine Seite ausgewählt" erhält man nur bei `example.com/?login` oder `example.com/?&login`.
Und das nervt mich auch manchmal.
Ist explizit keine Seite angegeben, dann sollte man eigentlich auf der FirstPublishedPage landen.
Oddr?

**Comment by olape-git** [comment]
Aber die erste veröffentlichte Seite ist ja wahrscheinlich auch nicht immer richtig. Wenn es auch, wie schon geschrieben, besser aussehen würde als jetzt.
Nur beim Login per Login-Link macht er das eigentlich selbstständig, wenn man auf der ersten Seite ist, oder auf Sitemap, eigentlich überall, wo keine Seite gewählt ist.
Natürlich nicht, wenn man die URL manuell rein tippelt.

**Comment by cmb69** [comment]
Das ist wieder das leidige `$s` Problem (CMSimple_XH weiß eben nicht, wo es hin soll). Und was immer wir hier ändern, könnte Plugins/Addons/Anpassungen betreffen. Aber irgendwann müsste das mal sauber gelöst werden.

Für jetzt: da nun die kanonische URL zur Startseite diese nicht mehr explizit enthält, sollte man wohl schon nachbessern, wo das möglich ist.

**Comment by frase-git** [comment]
Many customers do not want to have a login link on their site.
Therefore: Type it in!

**Comment by olape-git** [comment]
> Und was immer wir hier ändern, könnte Plugins/Addons/Anpassungen betreffen.

Wie wäre es, wenn wir erst dort einhaken, wo die Meldung generiert wird und statt dieser eine 302 setzen? Von mir aus auf FirstPublicPage.
An dieser Stelle sollte es keine Auswirkungen mehr auf andere Dinge haben.

**Comment by cmb69** [comment]
> Wie wäre es, wenn wir erst dort einhaken, wo die Meldung generiert wird und statt dieser eine 302 setzen? Von mir aus auf FirstPublicPage.

Das könnte passen. :)
