### ISSUE TITLE
Error in index.php in meta-tags plugin

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#444]
CMSimple_XH Version 1.7.3:
The following information is not transmitted:
- robots
- keywords
- description

Also the designation in the page tab of the browser is disturbed.
This is of course a bug.
There is already a [patch (bugfix) available for this problem](https://cmsimpleforum.com/viewtopic.php?p=76343#p76343), where only one file has to be exchanged.

**Comment by cmb69** [comment]
Tipp: wenn man in der Commit-Message etwas wie "fix #444" oder "closes #444" schreibt, dann wird das Issue bei Mergen automatisch geschlossen.
