### ISSUE TITLE
tinymce4 - avoid missing language files in plugins

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#449]
Im plugin "xhplugincall" wird bei fehlender Sprachdatei in https://github.com/cmsimple-xh/cmsimple-xh/tree/1.7/plugins/tinymce4/tinymce/plugins/xhplugincall/langs eine Fehlermeldung ausgegeben. Das plugin arbeitet aber.
Lösung: für alle verfügbaren [Sprachen ](https://github.com/cmsimple-xh/cmsimple-xh/tree/1.7/plugins/tinymce4/tinymce/langs)eine [lang].js anlegen. Bei fehlender Übersetzung kann diese auch leer sein.

**Comment by manu37** [comment]
Die [fall back language](https://github.com/cmsimple-xh/cmsimple-xh/blob/c4ffbbb79c6dc00ac96b8bd27c0f20840d94d8f1/plugins/tinymce4/tinymce/plugins/xhplugincall/plugin.min.js#L4) ist hier wirkungslos und kann entfernt werden.

**Comment by lck-git** [comment]
> Im plugin "xhplugincall" wird bei fehlender Sprachdatei in https://github.com/cmsimple-xh/cmsimple-xh/tree/1.7/plugins/tinymce4/tinymce/plugins/xhplugincall/langs eine Fehlermeldung ausgegeben. Das plugin arbeitet aber.
> Lösung: für alle verfügbaren [Sprachen ](https://github.com/cmsimple-xh/cmsimple-xh/tree/1.7/plugins/tinymce4/tinymce/langs)eine [lang].js anlegen. Bei fehlender Übersetzung kann diese auch leer sein.

Diese Fehleranzeige tritt auch bei der init-Einstellung "fontawesome-codemirror" und "full" auf. Ist das dann mit dieser Lösung auch dies behoben?

**Comment by manu37** [comment]
> 
> 
> > Im plugin "xhplugincall" wird bei fehlender Sprachdatei in https://github.com/cmsimple-xh/cmsimple-xh/tree/1.7/plugins/tinymce4/tinymce/plugins/xhplugincall/langs eine Fehlermeldung ausgegeben. Das plugin arbeitet aber.
> > Lösung: für alle verfügbaren [Sprachen ](https://github.com/cmsimple-xh/cmsimple-xh/tree/1.7/plugins/tinymce4/tinymce/langs)eine [lang].js anlegen. Bei fehlender Übersetzung kann diese auch leer sein.
> 
> Diese Fehleranzeige tritt auch bei der init-Einstellung "fontawesome-codemirror" und "full" auf. Ist das dann mit dieser Lösung auch behoben?

Die Fehlermeldung für xhplugincall sollte damit behoben sein. In "fontawesome-codemirror" ist der xhplugincall zur Zeit nicht implementiert und sollte auch keine Fehlermeldung machen. Oder ist es ein anderes Plugin, das diese Fehlermeldung generiert?
