### ISSUE TITLE
email servers block emails with multiple senders

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#450]
If you enter more than one e-mail address, the receipt may not work. It seems that some email servers block emails with multiple senders.

https://cmsimpleforum.com/viewtopic.php?f=16&t=16389&sid=f073f173b807fb1e99dee166234d5707&start=10#p76455

https://cmsimpleforum.com/viewtopic.php?f=16&t=16389&sid=f073f173b807fb1e99dee166234d5707&start=10#p76461

https://cmsimpleforum.com/viewtopic.php?f=16&t=16389&sid=0ff061d3b17b6bef1703bd8edd29157a&start=20#p76467

https://cmsimpleforum.com/viewtopic.php?f=16&t=16389&sid=6b4646772c79185191879b5d0dbc990b&start=30#p76492

**Comment by olape-git** [comment]
Das kommt heraus, wenn man mehrere Adressen für das E-Mail-Formular einträgt und wenigstens eine davon gmail ist

`<xxxxxx@gmail.com>
74.xxx.xxx.27 failed after I sent the message.
Remote host said: 550-5.7.1 [188.xx.xx.203      13] Messages with multiple addresses in From:
550 5.7.1 header are not accepted. v17si21707689wro.198 - gsmtp:`

**Comment by manu37** [comment]
> 
> 
> Das kommt heraus, wenn man mehrere Adressen für das E-Mail-Formular einträgt und wenigstens eine davon gmail ist
> 
> `<xxxxxx@gmail.com> 74.xxx.xxx.27 failed after I sent the message. Remote host said: 550-5.7.1 [188.xx.xx.203 13] Messages with multiple addresses in From: 550 5.7.1 header are not accepted. v17si21707689wro.198 - gsmtp:`



> 
> 
> Das kommt heraus, wenn man mehrere Adressen für das E-Mail-Formular einträgt und wenigstens eine davon gmail ist
> 
> `<xxxxxx@gmail.com> 74.xxx.xxx.27 failed after I sent the message. Remote host said: 550-5.7.1 [188.xx.xx.203 13] Messages with multiple addresses in From: 550 5.7.1 header are not accepted. v17si21707689wro.198 - gsmtp:`

Kann diese Fehlermeldung abgefangen und ausgegeben werden?

**Comment by olape-git** [comment]
> Kann diese Fehlermeldung abgefangen und ausgegeben werden?

Hm, diese Meldung habe ich per E-Mail vom Websebver, auf meine im Account hinterlegt E-Mail-Adresse bekommen. Ob man die Meldung auch irgendwie im PHP bekäme, das weiss ich nicht.

**Comment by cmb69** [comment]
> Ob man die Meldung auch irgendwie im PHP bekäme, das weiss ich nicht.

Nein, das geht nicht. PHP ruft i.d.R. ein externes Programm auf, und das schiebt die Email in eine Warteschlange. Bis der Versand erfolgt, ist das PHP Script meist schon beendet. Siehe auch https://www.php.net/manual/en/function.mail.php#refsect1-function.mail-returnvalues

Mir scheint, dass PR #452 das Problem löst: es wird einfach nur die 1. konfigurierte Adresse als Absender verwendet.

Ich denke wir müssen über dieses Issue nicht abstimmen; es ist letztlich ein Bug, denn auch wenn gemäß [RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.6.2) (ja, nicht mehr wirklich aktuell, aber ich denke da hat sich nichts geändert) `From` eine Liste akzeptiert, tut das `Sender:` nicht.
