### ISSUE TITLE
A typo and superfluous code in core.css

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#453]
The typo:
https://github.com/cmsimple-xh/cmsimple-xh/blob/195d35e40d94330b35c521aecdd83cfc96faa625/assets/css/core.css#L629-L632

must be
```
#xh_mailform .text,
.xh_mailform textarea {
	width: 100%;
}
```
And:
The superfluous (already commented out) lines 633 to 666 can be removed.

**Comment by lck-git** [comment]
> The typo:
> https://github.com/cmsimple-xh/cmsimple-xh/blob/195d35e40d94330b35c521aecdd83cfc96faa625/assets/css/core.css#L629-L632
> 
> must be
> 
> ```
> #xh_mailform .text,
> .xh_mailform textarea {
> 	width: 100%;
> }
> ```
> 
> And:
> The superfluous (already commented out) lines 633 to 666 can be removed.

Wie ich das sehe, ist das aber noch nicht behoben.

**Comment by cmb69** [comment]
> Wie ich das sehe, ist das aber noch nicht behoben.

Sollte nun passen (1.7 und master). Danke für die Erinnerung!
