### ISSUE TITLE
No page selected" after login or language change in the backend

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#458]
Language change in backend or login with domain.tld/?&login ends with "No page selected"

https://github.com/cmsimple-xh/cmsimple-xh/issues/443#issuecomment-678799045

https://github.com/cmsimple-xh/cmsimple-xh/issues/443#issuecomment-678803576

https://github.com/cmsimple-xh/cmsimple-xh/issues/443#issuecomment-678809105

**Comment by olape-git** [comment]
Als Vorschlag: https://github.com/olape-git/cmsimple-xh/commit/35e9285a9dbcd14d4d0a912e2e010f2d88aad3f7

**Comment by manu37** [comment]
> 
> 
> Als Vorschlag: [olape-git@35e9285](https://github.com/olape-git/cmsimple-xh/commit/35e9285a9dbcd14d4d0a912e2e010f2d88aad3f7)

Was machen wir mit diesem da? Scheint noch nicht den Weg in 1.7 gefunden zu haben.
PR erstellen und mergen?

**Comment by cmb69** [comment]
Der Umweg über ein PR ist eigentlich nicht nötig. Man kann einfach [den formatierten Patch](https://github.com/olape-git/cmsimple-xh/commit/35e9285a9dbcd14d4d0a912e2e010f2d88aad3f7.patch) herunter laden, auf den Repo-Clone anwenden, und direkt pushen.

Für meinen Geschmack ändern wir (und haben wir bereits geändert) viel zu viel an 1.7. Was spricht gegen 1.8 oder gar 2.0?

**Comment by frase-git** [comment]
> Für meinen Geschmack ändern wir (und haben wir bereits geändert) viel zu viel an 1.7. Was spricht gegen 1.8 oder gar 2.0?

Da hast du sicher recht.
Ich stelle mir für 1.8 aber ein paar "richtige" Änderungen vor.
Z.B.:
https://github.com/cmsimple-xh/cmsimple-xh/pull/441
oder
https://github.com/cmsimple-xh/cmsimple-xh/pull/341

Über das eine  muss man noch gründlich nachdenken - das andere passt schon ganz gut.

Das wäre dann wirklich "was Neues" und rechtfertigte eine neue Versionsnummer. Meinetwegen auch 2.0
In 1.7.x sollten wir die ganzen "kleinen" bekannten Bugs noch abarbeiten und ausgiebig testen.

**Comment by manu37** [comment]
> 
> 
> Der Umweg über ein PR ist eigentlich nicht nötig. Man kann einfach [den formatierten Patch](https://github.com/olape-git/cmsimple-xh/commit/35e9285a9dbcd14d4d0a912e2e010f2d88aad3f7.patch) herunter laden, auf den Repo-Clone anwenden, und direkt pushen.
> 
> Für meinen Geschmack ändern wir (und haben wir bereits geändert) viel zu viel an 1.7. Was spricht gegen 1.8 oder gar 2.0?

Wenn ich das online über den PR mache, dann ist nachher nachvollziehbar, woher der commit kam. Wenn ich das lokal patche, dann kommt der commit von mir :-). Es gibt schon zuviel von mir, woran ich mich nicht mehr erinnere.
Was machen wir? Wollen wir den noch reinnehmen?

**Comment by cmb69** [comment]
> Wenn ich das lokal patche, dann kommt der commit von mir :-).

Nicht bei [`git am`](https://git-scm.com/docs/git-am).

**Comment by olape-git** [comment]
> Was machen wir mit diesem da? Scheint noch nicht den Weg in 1.7 gefunden zu haben.
> PR erstellen und mergen?

Soll ich nochmal einen neuen PR machen?

> Für meinen Geschmack ändern wir (und haben wir bereits geändert) viel zu viel an 1.7. Was spricht gegen 1.8 oder gar 2.0?

Das stimmt, aber es hat seeeehhhhr sich lange gar nichts getan. Nur mit ein wenig "nerven" ist es überhaupt in Gang gekommen. ;-)
Und da so lange nichts passiert ist, fand ich und ich hoffe nicht nur ich allein, dass ein einfaches Bug-Release etwas wenig ist.

Für die 1.8 ist aber noch reichlich offen und jetzt, wo du auch wieder mitspielst, sehe ich das auch etwas positiver.

**Comment by cmb69** [comment]
> Und da so lange nichts passiert ist, fand ich und ich hoffe nicht nur ich allein, dass ein einfaches Bug-Release etwas wenig ist.

Das finde ich diesbezüglich nicht so wichtig. Viel wichtiger ist meiner Meinung nach, dass wir in Revisions möglichst keine Regressionen einführen. Solche kleinen Updates sollte ein User ohne viel Überlegen, Lesen und gar Anpassungen einspielen können (insofern keine Code-Dateien angepasst wurden). Natürlich toll wenn dabei möglichst viele Bugs behoben werden (falls es viele gibt). Aber 1.7.3 hatte zumindest auch Design-Updates (das neue Styling sieht super aus, kann aber eben mit bestehenden Anpassungen kollidieren). Und in diesem PR geht es eigentlich auch um die Behebung eines uralten Problemchens. Für mich als Anwender gilt im Zweifel, wenn ich 1.7.2 im Einsatz habe: "ah, 1.7.3 ist da; kann ich schnell mal zwischendurch updaten. Oh, 1.8.0 ist da; besser mal genau prüfen, ob ich nach dem Update noch nachbessern muss."

Und sekundär geht es mir auch um das Abschneiden alter Zöpfe. Wir haben 1.7 vor gut drei Jahren freigegeben, und diese Version unterstützte PHP 5.3.7 aufwärts. Okay, das konservative CentOS 6 (das noch bis Ende November unterstützt wird) liefert standardmäßig PHP 5.3, aber ist das in der Praxis wirklich noch relevant? Hätte man nicht wenigstens PHP 5.4 fordern können? Das hätte selbst ohne Nutzung von PHP 5.4 Features verhindern können, dass man sich im Jahre 2020 möglicherweise mit PHP 5.3 herumschlagen muss. Und man hätte vielleicht sogar PHP 5.5 fordern können, so dass man den password_hash() Fallback nicht mehr bräuchte.

Kurzum, ich finde wir sollten XH 1.7 in den Security-Fix-Only-Modus versetzen (zumindest möglichst bald), und uns um Wesentlichen 1.8 zuwenden. PHP 8.0.0 steht vor der Tür, und ich würde in spätestens einem Jahr eher auf PHP 5.6 Support verzichten, als auf PHP 8.0 Support – und PHP 5.6 bis 8.0 Support könnte vielleicht unschön werden.

**Comment by olape-git** [comment]
### Da gebe ich dir in allem Recht. Aber

vergiss bitte nicht, dass wir recht „schmerzhaft“ herausfinden mussten, jedenfalls ich sehe das so, wie viel Arbeit ausserhalb PHP da noch dranhängt, was GitHub betrifft. Dass keiner von uns wirklich einen Plan hatte, was du in den vergangenen Jahren hier geleistet hast. Und so haben wir versucht hier irgendwie einen Kompromiss zu finden. Und mal abgesehen von der Panne mit Meta-Tags, ist uns das ganz gut gelungen, finde ich. Grösstenteils ist das manu und auch Holger zu verdanken. Ich hätte bei GitHub aufgegeben.
So haben sich Frank, Ludwig und ich darauf beschränkt, so gut es geht Lösungen zu finden und zu testen.

Und, **das ist keine Kritik, es wird Gründe geben**, wir haben mehrfach darum gebeten, dass du dich wieder aktiv beteiligst. Und das ist anfangs, nach meiner Kenntnis, einfach nicht passiert.

Also jetzt noch die 1.7.4 und dann auf zur 1.8! Ich bin dabei.

**Comment by manu37** [comment]
> 
> 
> Als Vorschlag: [olape-git@35e9285](https://github.com/olape-git/cmsimple-xh/commit/35e9285a9dbcd14d4d0a912e2e010f2d88aad3f7)

Beim Login ohne spezifische Seite gibts einen 302er auf die Startseite, ok. (Die XH_Message ist da dann wohl überflüssig).
Beim Wechseln der Sprache im Backend gehts auf den Pagemanager. Wieso nicht auch einfach auf die Startseite, wie im Frontend?
Dann wäre das Verhalten für den Benutzer gleich: Admin/Backend wie im Frontend.
Die Idee ist wohl gut, gehört aber IHMO mit seiner Änderung des Verhaltens nicht in einen Bug Release sondern 1.8 aufwärts.

**Comment by olape-git** [comment]
> Die XH_Message ist da dann wohl überflüssig

Ja, ist sie, ich habe sie aber absichtlich erst mal drin gelassen. Stören tut sie auch nicht.

> Beim Wechseln der Sprache im Backend gehts auf den Pagemanager. Wieso nicht auch einfach auf die Startseite, wie im Frontend?

Ganz ehrlich. Weil ich nicht wirklich wusste, wie ich die erste veröffentlichte Seite der jeweils gewählten Sprache mit einfachen Mitteln rausbekomme.

**Comment by cmb69** [comment]
@olape-git, bitte meine Kommentare nicht als Meckerei oder gar Vorwurf verstehen; das soll einfach nur (hoffentlich) konstruktive Kritik sein. :)

Und alles in allem finde ich XH 1.7.3 doch sehr gelungen. Ein guter Beleg, dass der [Bus-Factor](https://en.wikipedia.org/wiki/Bus_factor) bei CMSimple_XH doch deutlich größer als eins ist!

> Weil ich nicht wirklich wusste, wie ich die erste veröffentlichte Seite der jeweils gewählten Sprache mit einfachen Mitteln rausbekomme.

Muss man das denn überhaupt? Würde man die Änderungen in languagemenu() rückgängig machen, wäre dann nicht alles korrekt (sprich, griffe dann nicht die Weiterleitung)?

**Comment by olape-git** [comment]
> @olape-git, bitte meine Kommentare nicht als Meckerei oder gar Vorwurf verstehen; das soll einfach nur (hoffentlich) konstruktive Kritik sein. :)

Nein, das tue ich eigentlich nie, da gibt es nur ganz wenige Ausnahmen.

> Und alles in allem finde ich XH 1.7.3 doch sehr gelungen. Ein guter Beleg, dass der [Bus-Factor](https://en.wikipedia.org/wiki/Bus_factor) bei CMSimple_XH doch deutlich größer als eins ist!

Ich auch. 
Deutlich? Zum Glück liegt er darüber. Leider nicht so deutlich. Wohl ein Beleg dafür, dass wir uns zu lange darauf verlassen haben, dass du das erledigst. Ich bin wirklich froh, dass Manu das übernommen hat. Ich hoffe zukünftig geht da mehr gemeinsam.

> Muss man das denn überhaupt? Würde man die Änderungen in languagemenu() rückgängig machen, wäre dann nicht alles korrekt (sprich, griffe dann nicht die Weiterleitung)?

Ich glaube, gerade das hat eben nicht gegriffen. So richtig weiß ich das gar nicht mehr. Aber ich glaube die Option "Sitemanager" kam erst als zweites ins Spiel.

**Comment by olape-git** [comment]
Dann wäre eine Option, die eigentlich die anderen beiden ersetzen sollte und zusätzlich den Link auf `./` wie er in manchen Templates drin ist abfängt: 
nach
https://github.com/cmsimple-xh/cmsimple-xh/blob/eae190362b30f0293f8a6193c4fd6a3a94206627/cmsimple/cms.php#L1014

`if (XH_ADM && ($_SERVER['QUERY_STRING'] == '')) {
    header('Location:' . CMSIMPLE_URL 
                       . '?'
                       . $u[$xh_publisher->getFirstPublishedPage()],
    true, 302);
    exit;`

Könnte man auch mit in dei seofuncs.php reinnehmen, passt da aber vom namen her nicht so richtig rein.

**Comment by manu37** [comment]
Aber ws. gehört es genau dahin auch wenn der Name nicht passt. Wie es für die firstpage im frontend eine Umleitung auf "./" braucht, braucht es im ADM Modus bei der first page eine Umleitung auf auf die firstpage mit explizitem querystring. Ich weiss jetzt nicht genau, wie das abgefragt werden muss ($su==''?).

**Comment by cmb69** [comment]
> Ich glaube, gerade das hat eben nicht gegriffen. So richtig weiß ich das gar nicht mehr. Aber ich glaube die Option "Sitemanager" kam erst als zweites ins Spiel.

Gerade ausprobiert:
````.diff
 www/cmsimple/classes/Controller.php | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/www/cmsimple/classes/Controller.php b/www/cmsimple/classes/Controller.php
index cdea6be..23c2c20 100644
--- a/www/cmsimple/classes/Controller.php
+++ b/www/cmsimple/classes/Controller.php
@@ -529,12 +529,17 @@ EOT;
      */
     public function outputEditContents()
     {
-        global $s, $tx, $o;
+        global $s, $tx, $o, $u, $xh_publisher;
 
         if ($s > -1) {
             $o .= XH_contentEditor();
         } else {
             $o .= XH_message('info', $tx['error']['cntlocateheading']) . "\n";
+            header('Location:' . CMSIMPLE_URL 
+                               . '?'
+                               . $u[$xh_publisher->getFirstPublishedPage()],
+            true, 302);
+            exit;
         }
     }
 ````
Konnte keine Problem feststellen.

> Aber ws. gehört es genau dahin auch wenn der Name nicht passt.

Da stimme ich tendentiell zu, aber zur Zeit wird seofuncs.php eingebunden, bevor $edit gesetzt wird, und wir sollten nur weiterleiten, wenn `$edit === true`. Im View-Modus gibt es ja das Problem nicht. Der obige Code hat dieses Problem nicht.

Insgesamt sollten wir mit den Weiterleitungen aber vorsichtig sein; da schleichen sich leicht Fehlerchen ein. Mir ist gerade aufgefallen, dass die Weiterleitung durch `XH_URI_Cleaning()` den Port vergisst,

**Comment by cmb69** [comment]
Gerade fällt mir auf, dass die Startseite in seofuncs nicht richtig erkannt wird, wenn die erste Seite z.B. per Register geschützt ist. Das liegt daran, dass `::getFirstPublishedPage()` erst dann zuverlässige Ergebnisse liefert, nachdem alle Plugins geladen wurden (hätte besser dokumentiert werden sollen). Ist in der Praxis aber vermutlich kein Problem, da es wohl keinen Sinn macht, die Startseite per Register zu schützen.

**Comment by olape-git** [comment]
> Konnte keine Problem feststellen.

Also bei mir reicht das nur für das blanke Login. Beim Sprachwechsel geht das bei mir nicht. Ich kann das nicht recht glauben, denn dann müsste ja ohne Änderungen beim Sprachwechsel die Meldung kommen "keine Seite gewählt". Und die kommt bei mir auch nicht. Auch nicht in einer 1.7.2.



> Mir ist gerade aufgefallen, dass die Weiterleitung durch `XH_URI_Cleaning()` den Port vergisst,

???

> Aber ws. gehört es genau dahin auch wenn der Name nicht passt.

Passt vom Namen nicht war bezogen auf die seofuncs.php. Denn mit SEO hat das ja nichts zu tun.
Ansonsten, umso eher, um so schneller.



> braucht es im ADM Modus bei der first page eine Umleitung auf auf die firstpage mit explizitem querystring.

Genau das tut die Umleitung.

**Comment by cmb69** [comment]
> Also bei mir reicht das nur für das blanke Login. Beim Sprachwechsel geht das bei mir nicht. Ich kann das nicht recht glauben, denn dann müsste ja ohne Änderungen beim Sprachwechsel die Meldung kommen "keine Seite gewählt". Und die kommt bei mir auch nicht. Auch nicht in einer 1.7.2.

Hast du vielleicht ein Polyglott (oder eine entsprechende Anpassung) aktiviert?

> ???

Beim Aufruf von http://example.com:8080/?Start wird auf http://example.com/ weitergeleitet.

**Comment by olape-git** [comment]
> Hast du vielleicht ein Polyglott (oder eine entsprechende Anpassung) aktiviert?

Ne, original 1.7.2 bzw. .3., lokal, Xamp mit 7.4.
Einzige Änderungen sind die hier beschriebenen.

**Comment by olape-git** [comment]
> Beim Aufruf von http://example.com:8080/?Start wird auf http://example.com/ weitergeleitet.

Hm, das wird doch aber auch von anderen Weiterleitung nicht explizit behandelt. 
Ich muss aber gestehen, das hatte ich auch nicht auf dem Schirm.

**Comment by lck-git** [comment]
> Also bei mir reicht das nur für das blanke Login. Beim Sprachwechsel geht das bei mir nicht. Ich kann das nicht recht glauben, denn dann müsste ja ohne Änderungen beim Sprachwechsel die Meldung kommen "keine Seite gewählt". Und die kommt bei mir auch nicht.

Ich habe das mal mit Portable_XH 2.1 getestet mit frischem XH 1.7.3 und der Änderung in [classes/Controller.php](https://github.com/cmsimple-xh/cmsimple-xh/issues/458#issuecomment-683421941) (oder muss da noch etwas geändert weden?).
Beim Login per www.example.com/?login wird die Startseite im Edit-Mode aufgerufen, ebenso beim Sprachwechsel, gut. Das funktioniert aber nicht im View-Mode und es kommt auch keine Meldung "No page selected".

> Beim Aufruf von http://example.com:8080/?Start wird auf http://example.com/ weitergeleitet.

Tatsächlich :(, aber nur im Frontend, nicht im Backend.

**Comment by olape-git** [comment]
> Ich habe das mal mit Portable_XH 2.1 getestet mit frischem XH 1.7.3 und der Änderung in [classes/Controller.php](https://github.com/cmsimple-xh/cmsimple-xh/issues/458#issuecomment-683421941) (oder muss da noch etwas geändert weden?).

Das war die erste Änderung, laut Christoph würde das reichen. Meine Erfahrung ist wie bei dir, es reicht nicht. Auch nicht, wenn ich (Templae fsh-simple-2019) das XH als Link zur Startseite anklicke.

**Comment by manu37** [comment]
Muss jetzt da noch was in die 1.7.4 rein?

**Comment by lck-git** [comment]
Ich bin dafür, das auf 1.8 zu schieben.

**Comment by olape-git** [comment]
Ich denke auch, bis wir geklärt haben, was wir tun müssen, damit es in allen Situationen funktioniert, sollten wir das verschieben.
Also 1.8

**Comment by frase-git** [comment]
Schweren Herzens habe ich mein "Daumen hoch" dazu gegeben.
Wäre schon besser, wenn das sauber und überall funktioniert.
