### ISSUE TITLE
XH_URI_Cleaning(): when forwarding, the port is not considered.

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#461]
https://github.com/cmsimple-xh/cmsimple-xh/issues/458#issuecomment-683421941

XH_URI_Cleaning(): when forwarding, the port is not considered.

http://example.com:8080/?Start is forwarded to http://example.com/.

**Comment by manu37** [comment]
Kommt dieser noch in die 1.7.4 rein oder erst 1.8?

**Comment by cmb69** [comment]
PR #462 würde ich noch in die 1.7.4 nehmen.
