### ISSUE TITLE
final tests 1.7.4

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#464]
Die 1.7.4 issues scheinen abgearbeitet zu sein.
Wie testen wir diese Version am effektivsten? Da sind ja auch sprach-spezifische Dinge zu testen.
Einfach den 1.7er Branch auschecken und dann rückmelden? Oder einen 1.7.4 Release Candidate erstellen?

**Comment by frase-git** [comment]
**1.7.4 Release Candidate** oder ein **Pre Release** - fände ich gut.
Irgendwo (evtl. im Forum) sollte mal jemand in einer Liste zusammenfassen, **was und wie** man unbedingt testen sollte.
Anhand der bloßen Closed-Issues ist das kaum machbar. Da blickt keiner mehr durch.

**Comment by olape-git** [comment]
> ein **Pre Release** - fände ich gut.

Ich auch, ohne zu wissen, welcher Aufwand dahinter steckt.


> Anhand der bloßen Closed-Issues ist das kaum machbar

Aber so viel ist es eigentlich nicht. Bei TinyMCE habe ich allerdings nicht wirklich so genau verfolgt, um was es da ging.
Na ich versuche es mal im Forum "zusammenzuverlinken".


**Denkt noch jemand an LF statt CRLF?**

**Comment by cmb69** [comment]
> Denkt noch jemand an LF statt CRLF?

Oh ja bitte; fände ich wichtig. Höchst wahrscheinlich ein Git-Checkout-Problem; bei Bedarf könnten wir eine entsprechende .gitattributes Datei ins Repo packen.

Ein paar Dinge, die vielleicht noch in 1.7.4 aufgenommen werden könnten:
* jQuery aktualisieren (ich glaube, das ist bei 1.7.3 nicht mehr passiert); @TN03, hättest du dafür Zeit?
* bessere Fehlerprüfung/-meldung bei hi_updatecheck (https://github.com/TN03/hi_updatecheck/pull/4); da möchte ich am Wochenende noch nachbessern
* Prüfung auf OpenSSL-Verfügbarkeit, mit Warnung, falls nicht vorhanden (wird in der Praxis für den Updatecheck gebraucht, und verhindert die Generierung sehr schwacher Zufallswerte unter PHP 5 (falls mcrypt nicht vorhanden ist, und /dev/urandom nicht gelesen werden kann); ich versuche sehr zeitnah einen PR zu machen

**Comment by manu37** [comment]
> 
> 
> > Denkt noch jemand an LF statt CRLF?
> 
> Oh ja bitte; fände ich wichtig. Höchst wahrscheinlich ein Git-Checkout-Problem; bei Bedarf könnten wir eine entsprechende .gitattributes Datei ins Repo packen.
> 

Wie soll es jetzt denn sein? Ich habe die Frage schon verschiedentlich gestellt, aber keine eindeutige Antwort erhalten. Irgendwo in unserem Weltraum wurde das Thema mal angeschnitten, finde es aber nicht mehr. 
Was, glaube ich, zur Zeit feststeht: Der source code hat CRLF (meiner erstellten zip's wohl auch).
Die von Github erstellte source code.zip hat LF.
Also was nun?

Die Zielvorstellung ist wohl simple LF.
Wie ändern wir den source code in einem Zug auf die korrekte Einstellung (ein solcher patch ändert das komplette repository, dann wohl erst bei einem major release)?
Wie lautet die Empfehlung für die Einstellung im Code Editor (sollte dann auf der Developer Page hinterlegt werden, möglichst komplett mit Tabs/LF's etc.)? 

> Ein paar Dinge, die vielleicht noch in 1.7.4 aufgenommen werden könnten:
> 
>     * jQuery aktualisieren (ich glaube, das ist bei 1.7.3 nicht mehr passiert); @TN03, hättest du dafür Zeit?

8d548cc9142bfe96d6f558204cc3c4d54c254f0d

**Comment by frase-git** [comment]
> Denkt noch jemand an LF statt CRLF?

> Oh ja bitte; fände ich wichtig. Höchst wahrscheinlich ein Git-Checkout-Problem; bei Bedarf könnten wir eine entsprechende .gitattributes Datei ins Repo packen.

> Die Zielvorstellung ist wohl simple LF.

Könnte das evtl. helfen?
https://git-scm.com/docs/gitattributes#_effects

**Comment by cmb69** [comment]
> Wie lautet die Empfehlung für die Einstellung im Code Editor (sollte dann auf der Developer Page hinterlegt werden, möglichst komplett mit Tabs/LF's etc.)?

Keine Tabs, und immer nur LF. Letzteres kann aber von Git erledigt werden (siehe [Franks Kommentar](https://github.com/cmsimple-xh/cmsimple-xh/issues/464#issuecomment-686956710)).

Und gut, dass das jQuery Plugin schon aktualisiert wurde.

**Comment by manu37** [comment]
> **Denkt noch jemand an LF statt CRLF?**

#467
