### ISSUE TITLE
Filebrowser: Image preview on mouseover has wrong aspect ratio

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#466]
Tut mir leid - ich habe da noch etwas entdeckt, was ich selbst vermasselt habe.

Im Filebrowser kommt es vor, dass das Bild verzerrt dargestellt wird.

https://github.com/cmsimple-xh/cmsimple-xh/blob/8332713f691e094cdecff9038e4ebd50fa8f8b8e/plugins/filebrowser/css/stylesheet.css#L122-L129

Abilfe schafft das Hinzufügen einer Zeile - evtl. nach Zeile 125:
`width: 100%;`

Es ist kein _schwerer_ Fehler, aber doch einer.
Wäre schön, wenn jemand einen PR erstellt und es noch für 1.7.4 merged.
Falls nicht, dann eben für 1.8

**Comment by cmb69** [comment]
> Abilfe schafft das Hinzufügen einer Zeile - evtl. nach Zeile 125:
width: 100%;

Das ändert bei mir (aktueller Chrome) wohl gar nichts. `width: auto` würde aber die Verzerrung korrigieren, sieht aber nicht wirklich gut aus. Und anscheinend sind [da Regeln dupliziert](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7/plugins/filebrowser/css/stylesheet.css#L122-L144).

**Comment by frase-git** [comment]
> Das ändert bei mir (aktueller Chrome) wohl gar nichts. width: auto würde aber die Verzerrung korrigieren, sieht aber nicht wirklich gut aus. Und anscheinend sind da Regeln dupliziert.

Oh man, das ist alles so lange her.
Aso mit `width: auto` sieht es bei mir in FF und Chromium-Browsern "ordentlich" aus. Ich hatte (weil nebenbei) nur im FF getestet.
Die Doppelung einiger Regeln ist mir auch aufgefallen, wollte aber nicht unnötig Wirbel machen.
Was wäre besser: Händisch die angesprochenen Dinge ändern - oder soll ich ein komplett neues File liefern. Da sind noch andere auskommentierte Abschnitte und Formatierungs-Eigenarten drin. Ich vermute, dass ich damals nur einige wenige Änderungen in der Datei gemacht habe, um keinen BC-Break zu verursachen. So sind wohl die Doppelungen entstanden.

**Comment by cmb69** [comment]
> Aso mit width: auto sieht es bei mir in FF und Chromium-Browsern "ordentlich" aus. Ich hatte (weil nebenbei) nur im FF getestet.

Ah, tatsächlich, im FF funktioniert `width:100%` auch. Aber was ich meine:
![sreenshot](https://user-images.githubusercontent.com/2306138/92306837-7aa32f80-ef92-11ea-9444-7feaf431339b.gif)
Der graue Balken ganz links im Popup ist das Bild. Das ist nicht zentriert. Bei weniger extremen Seitenverhältnissen sieht es nicht so schlimm aus, aber auch da sieht man bisweilen, dass das Bild nach links verrückt ist. Ich wüsste aber nicht, wie man das Bild zentrieren könnte. Im Zweifel vielleicht aber auch egal; Bilder mit so extremen Seitenverhältnissen wird es wohl eher selten geben.

> Was wäre besser: Händisch die angesprochenen Dinge ändern - oder soll ich ein komplett neues File liefern. Da sind noch andere auskommentierte Abschnitte und Formatierungs-Eigenarten drin. Ich vermute, dass ich damals nur einige wenige Änderungen in der Datei gemacht habe, um keinen BC-Break zu verursachen. So sind wohl die Doppelungen entstanden.

Für 1.7.4 sollten besser nur minimale Änderungen durchgeführt werden; im Wesentlichen halt als Bugfixes. Die doppelten Regeln und auskommentierte Bereiche sind ja nicht wirklich ein Problem.

**Comment by frase-git** [comment]
> Ich wüsste aber nicht, wie man das Bild zentrieren könnte. Im Zweifel vielleicht aber auch egal; Bilder mit so extremen Seitenverhältnissen wird es wohl eher selten geben.

> Für 1.7.4 sollten besser nur minimale Änderungen durchgeführt werden; im Wesentlichen halt als Bugfixes. Die doppelten Regeln und auskommentierte Bereiche sind ja nicht wirklich ein Problem.

Okay. Dann nur das `width:100%`. Hoffentlich vergessen wir den Rest später nicht.
Ich habe auf die Schnelle auch keine Möglichkeit gefunden, das Bild zu zentrieren.
Könntest du evtl. die Korrektur ausführen - bitte?

**Comment by cmb69** [comment]
> Könntest du evtl. die Korrektur ausführen - bitte?

Klar, gerne. Aber was nun: `width:100%` oder `width:auto`?

**Comment by frase-git** [comment]
> Klar, gerne. Aber was nun: width:100% oder width:auto?

auto - es soll doch in allen aktuellen Browsern funktionieren ;-)

**Comment by cmb69** [comment]
> auto - es soll doch in allen aktuellen Browsern funktionieren ;-)

Okay, wollte nur sichergehen. :) Erledigt per 8037f04eabcc7b452135808f7b9d47a65ea3a805.

Allerdings stelle ich fest, dass es im IE11 so aussieht:
![screenshot](https://user-images.githubusercontent.com/2306138/92308418-ad9ef080-ef9d-11ea-9109-5b8eebd6de82.gif)

Ist aber wohl verschmerzbar.

**Comment by frase-git** [comment]
IE11? What is it?
(Let's not talk about dead people. There's Edge.)

**Comment by lck-git** [comment]
> Ich habe auf die Schnelle auch keine Möglichkeit gefunden, das Bild zu zentrieren.

Kann es momentan am Handy nicht testen, probiere es mal mit object-fit. https://developer.mozilla.org/de/docs/Web/CSS/object-fit

**Comment by cmb69** [comment]
> (Let's not talk about dead people. There's Edge.)

Well, there is IE 11, Edge Spartan and Edge Anaheim. None of these seems to have a relevant marketshare, and even FF seems to have dropped below 5%. The only two really relevant browsers nowadays appear to be Chrome and Safari. :(

> Kann es momentan am Handy nicht testen, probiere es mal mit object-fit.

Scheint keinen Unterschied zu machen.

**Comment by frase-git** [comment]
> ... probiere es mal mit object-fit

Super Idee!
Prinzipiell geht es so (jetzt wieder mit 100%):
```
width: 100%;
object-fit: scale-down;
```
Wenn es aber z.B. bei den Flaggen eine häufige Verwendung gibt (viel Text), dann sieht es auch wieder komisch aus.
Aber vielleicht wirklich besser als vorher --- Christoph?

**Comment by frase-git** [comment]
> Well, there is IE 11, Edge Spartan and Edge Anaheim. None of these seems to have a relevant marketshare, and even FF seems to have dropped below 5%. The only two really relevant browsers nowadays appear to be Chrome and Safari. :(

We will soon drown in a browser unit soup. But as web designers we will have it much easier. ;-)

**Comment by cmb69** [comment]
> Aber vielleicht wirklich besser als vorher --- Christoph?

Ich glaube, im großen und ganzen schon. `object-fit` scheint auch [hinreichend verbreitet](https://caniuse.com/#search=object-fit). Also schon mal vielen Dank, @lck-git! Ich mach das Issue mal wieder auf; vielleicht hat sonst noch jemand was dazu zu sagen.

**Comment by olape-git** [comment]
> Wenn es aber z.B. bei den Flaggen eine häufige Verwendung gibt (viel Text), dann sieht es auch wieder komisch aus.
> Aber vielleicht wirklich besser als vorher

Ich finde auf jeden Fall besser als vorher. Und wenn man natürlich zu so kleinen Bilder wie die Flaggen viel Text hat, dann sieht es wohl so oder so ein wenig komisch aus.

**Comment by manu37** [comment]
Wie kommen wir hier zu einem Happy End?

**Comment by frase-git** [comment]
Na ja, Ludwigs Tipp hat es ja gebracht.
Die CSS-Datei müsste eigentlich komplett bereinigt werden, aber Christoph meinte ja, dass wir für 1.7.4 nur kleine Fixes machen sollten.
Also:
https://github.com/cmsimple-xh/cmsimple-xh/blob/8332713f691e094cdecff9038e4ebd50fa8f8b8e/plugins/filebrowser/css/stylesheet.css#L122-L129

In diese Regel noch zwei Deklarationen hinzufügen:
```
width: 100%;
object-fit: scale-down;
```
Und ebenfalls nochmal hier:
https://github.com/cmsimple-xh/cmsimple-xh/blob/8332713f691e094cdecff9038e4ebd50fa8f8b8e/plugins/filebrowser/css/stylesheet.css#L135-L143

Damit wäre [das hier](https://github.com/cmsimple-xh/cmsimple-xh/commit/8037f04eabcc7b452135808f7b9d47a65ea3a805) hinfällig.

**Comment by lck-git** [comment]
> Die CSS-Datei müsste eigentlich komplett bereinigt werden, aber Christoph meinte ja, dass wir für 1.7.4 nur kleine Fixes machen sollten.

### +1
Belassen wir es bei dieser Lösung für 1.7.4. Bisher ist das auch noch nie beanstandet worden und wer weiterhin mit dem IE11 (der object-fit nicht kann) seine Seiten bearbeitet, muss eben weiterhin damit leben.
