### ISSUE TITLE
resolve our CRLF problem - set .gitattributes

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#467]
Ausgangslage: 
Eigentlich sollte es mit der git Einstellung core.autocrlf automatisiert sein, dass die eols korrekt gesetzt werden. Als Windows User erstelle ich dann aber mit phing build packages mit CRLF Zeilenumbrüchen. 
Irgendwie sind auch files mit CRLF Umbrüchen auf den Server gelangt (wg. obiger Einstellung kann ich das nicht verifizieren).
[Hier ](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings)habe ich wohl die entsprechende Doku gefunden.

1.[ .gitattributes erstellen](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings#per-repository-settings) und committen:
```
# Set the default behavior to LF, in all cases.
* text eol=lf

# Denote all files that are truly binary and should not be modified.
*.png binary
*.jpg binary
```
@cmb69 muss das in etwa so aussehen? 

2. [Repository aktualisieren](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings) (macht wohl jeder lokal bei sich)

Wenn man keine commits hat, kann man Pt. 1 wohl weglassen.
Also auf der command line ab Pt. 2 ausführen.
@cmb Kannst Du das bestätigen?

**Comment by cmb69** [comment]
Please don't ping Chris Bannon (sorry, Chris!) – my Github handle is @cmb69.

Und ja, so kann man das machen. Ich habe bei mir unter Windows core.autocrlf auf false, und hatte damit allerdings noch nie irgendwelche Problem (selbst aktuelle Notepad-Versionen kommen mit LF prima zurecht). Im anderen Fall (CRLF unter Linux) gibt es viel eher einige Problem (z.B. mit Bash-Scripten).

**Comment by manu37** [comment]
Sorry about mentioning the wrong person..
Ich versuche, die obige Lösung mal durchzuspielen:
Ich stehe aber hier schon an:
```
PS C:\xampp\htdocs\CMSimpleGit> git add --renormalize .
error: unknown option `renormalize'
```
:-(
Ich frage mich, spielt es überhaupt eine Rolle, wie die Dateien auf dem Server abgelegt sind? Ist es nicht eher entscheidend, wie die Dateien beim checkout "normalisiert" werden?

**Comment by cmb69** [comment]
> error: unknown option `renormalize'

`git version` muss wenigstens 2.16 melden, denke ich.

> Ich frage mich, spielt es überhaupt eine Rolle, wie die Dateien auf dem Server abgelegt sind? Ist es nicht eher entscheidend, wie die Dateien beim checkout "normalisiert" werden?

Ja. Allerdings gibt das eben potentiell Probleme wenn der User core.autocrlf auf false hat, oder unter *nix arbeitet, und Dateien CRLF Zeilenenden haben. Wahrscheinlich ist es doch das beste, wenn wir eine .gitattributes anlegen; wir müssen nur aufpassen, dass wir alle Binärdateien auch als solche kennzeichnen. Außer .jpg und .png haben wir auf jeden Fall .gif, .eot, .ttf, .woff und .woff2, und vielleicht noch weitere. Möglicherweise behandelt Git solche Dateien aber schon standardmäßig als binär.

**Comment by manu37** [comment]
> 
> 
> > error: unknown option `renormalize'
> 
> `git version` muss wenigstens 2.16 melden, denke ich.

Die aktuelle TortoiseGit 2.10.0.2 hat git version 2.12.2 und die möchte ich eigentlich so belassen, solange TortoiseGit kein Update anbietet. Ich weiss ja nicht, welche Inkompatibilitäten ich mir da einhandle.

Nach Studium sollte doch `* text eol=lf` reichen, oder? Bis jetzt hat Git ja die Binaries/Nonbinaries richtig interpretiert.
Für [gitattributes lf only](https://www.google.com/search?client=firefox-b-d&q=gitattributes+lf+only) gibt es ja Dutzende Anleitungen. Nur funktioniert bei mir keine. Mir läuft da die Zeit und die Geduld davon. 
An die Spezis: Gibt es einen walk through, wie ich die gittatributes richtig setze und dann mein lokales repository aktualisiere/resette/wasauchimmer, damit ich die CRLF's rausbekomme? Gerade in cmsimple/classes hat es etliche deren Dateien.

**Comment by cmb69** [comment]
>Die aktuelle TortoiseGit 2.10.0.2 hat git version 2.12.2 und die möchte ich eigentlich so belassen, solange TortoiseGit kein Update anbietet. Ich weiss ja nicht, welche Inkompatibilitäten ich mir da einhandle.

Ich nutze auch TortoiseGit 2.10.0.2, aber mache regelmäßig Git Updates (nutzte zur Zeit Git 2.28.0.windows.1). Hatte noch nie ein Problem diesbezüglich, und gemäß https://tortoisegit.org/support/faq/#upgradegit ist das wohl auch so gedacht.

> Nach Studium sollte doch * text eol=lf reichen, oder? Bis jetzt hat Git ja die Binaries/Nonbinaries richtig interpretiert.

Wahrscheinlich hast du recht. Im Zweifel ausprobieren; falls irgendwas schief läuft, wäre zur Not halt ein Force-Push nötig.

> An die Spezis: Gibt es einen walk through, wie ich die gittatributes richtig setze und dann mein lokales repository aktualisiere/resette/wasauchimmer, damit ich die CRLF's rausbekomme? Gerade in cmsimple/classes hat es etliche deren Dateien.

Wenn du .gitattributes gepusht hast, könntest du einen temporären Clone ausprobieren. Und im Zweifel deinen regulären Clone einfach löschen, und erneut clonen (dabei verlierst du natürlich lokale Branches, Commits und Stashes; die vorher sichern).
