### ISSUE TITLE
little bug in #404

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#469]
Wenn ich die Startseite `./?Start` aufrufe, wird sie neuerdings mit #404 mit einem 301er auf `./` umgeleitet. Wenn ich nachher einlogge und im view mode von einer x-beliebigen Seite via Menü auf die Startseite gehe, habe ich eine leere Seite. Grund: die 301er Umleitung ist wohl im (DNS) Cache abgelegt und wird auch im ADM Modus ausgeführt. Daher empfehle ich für die Umleitung 302, damit diese Weiterleitung nicht gecached wird. Ist wohl etwas spitzfindig, aber es ist mir beim Testen tatsächlich passiert.

**Comment by lck-git** [comment]
> Wenn ich die Startseite `./?Start` aufrufe, wird sie neuerdings mit #404 mit einem 301er auf `./` umgeleitet. Wenn ich nachher einlogge und im view mode von einer x-beliebigen Seite via Menü auf die Startseite gehe, habe ich eine leere Seite.

Hm, kann ich nicht nachvollziehen. Bei mir wird `www.example.com/?Start` aufgerufen. Getestet mit Edge, Iron (Chrome) und Firefox.

**Comment by olape-git** [comment]
> Grund: die 301er Umleitung ist wohl im (DNS) Cache abgelegt und wird auch im ADM Modus ausgeführt.

Das hatte ich dazumal auch getestet und bin zu dem gleichen Ergebnis gekommen wie Ludwig. Icvh würde das aber nochmal testen.

**Comment by olape-git** [comment]
Es bleibt dabei, FF und Chrome. Bei beiden passiert was passieren soll. Normal 301 auf ./. Angemeldet wird problemlos ?Start aufgerufen.

**Comment by manu37** [comment]
Ich kann es in allen Browsern reproduzieren. Mach mal step-by-steb wie im 1. Post beschrieben.

**Comment by frase-git** [comment]
Leider kann ich das Problem auch nicht nachvollziehen. Weder lokal mit xampp noch auf einem online-Server.
@manu37 
Kannst du nochmal genau beschreiben, wann und wie das passiert?
Step by Step nach deinem ersten Post - da ist bei meinen Versuchen alles okay.

**Comment by lck-git** [comment]
Ich habe mir gestern auch nochmal einen frischen 1.7er Branch gezogen und getestet, gleiches Ergebnis, passt. Hab sogar mal einen Link in einer Seite erstellt zu ./?Start, auch keine Probleme sichtbar.



> @manu37
> Kannst du nochmal genau beschreiben, wann und wie das passiert?

... und welches System, Plugins, ...

**Comment by cmb69** [comment]
Kann es sein, dass der Browser da einfach sehr aggressiv cached?

**Comment by manu37** [comment]
ist weniger aggressiv wie ein bischen schwanger?

**Comment by manu37** [comment]
> 
> 
> Leider kann ich das Problem auch nicht nachvollziehen. Weder lokal mit xampp noch auf einem online-Server.
> @manu37
> Kannst du nochmal genau beschreiben, wann und wie das passiert?
> Step by Step nach deinem ersten Post - da ist bei meinen Versuchen alles okay.

Meine Installation liegt auf `http://localhost/cmsimplegit/`. Developer Tools ausgeschaltet, Cache aktiv.

- `http://localhost/cmsimplegit/?Start` aufrufen.
- Gehe zu `Templates` (via Menü).
- Login
- Schalte auf view mode/Vorschau
- Gehe zu `Start `(via Menü).

Wie sieht die Startseite aus?

**Comment by lck-git** [comment]
Ah, jetzt erscheint eine leere Seite :(.

**Comment by cmb69** [comment]
Habt ihr die Voreinstellung von https://www.php.net/manual/en/session.configuration.php#ini.session.cache-limiter geändert?

**Comment by manu37** [comment]
Ich glaube, das hat mit der Session nichts zu tun, sondern einfach mit dem 301 "moved permanently", welches gecached wird.

**Comment by lck-git** [comment]
Ich habe mit Portable_XH 2.1 getestet und in der php.ini wurde nichts verändert, dort steht `session.cache_limiter = nocache`

**Comment by lck-git** [comment]
> Ich glaube, das hat mit der Session nichts zu tun, sondern einfach mit dem 301 "moved permanently", welches gecached wird.

Genau. Schaltet man den Cache vorher per Developer-Tools aus, und macht dann das Prozedere wie von Manu beschrieben, so erscheint die Startseite.

**Comment by cmb69** [comment]
Ist session.cache_limiter=nocache, dann sollte ein entsprechender Header gesendet werden, der das Caching verhindert (sieht bei mir so aus: `Cache-Control: no-store, no-cache, must-revalidate`); und das bei jedem Backend-Request. Da dürfte der Browser also eigentlich nichts aus dem Cache holen. Oder sind diese Header nicht mehr unbedingt aktuell (sprich, hat sich was an der Spezifikation geändert)?

**Comment by frase-git** [comment]
Falls da so ist, wie ihr hier beschreibt, wäre das ein Bug.
Aus diesem Grund habe ich jetzt nochmal mit den verschiedensten Konfigurationen getestet.
1.7er- Branch von gestern, keine (anderen) Plugins, Standard-Template
lokal: mit PHP 7.3.1 und 7.4.2
online: mit PHP 7.2
Ich konnte in keinem Fall eine weiße Seite erzeugen.
???

**Comment by cmb69** [comment]
> Ich konnte in keinem Fall eine weiße Seite erzeugen.

Ah, "weiße Seite" ist wohl das Stichwort. Würde einfach aus dem Cache gezogen, dann wäre ja Inhalt da. Sieht also nach einem schweren Fehler aus – vielleicht eine unendliche Umleitung?

**Comment by frase-git** [comment]
>  – vielleicht eine unendliche Umleitung?

Ich glaube, die Chromium-Browser melden neuerdings bei einer unendlichen Weiterleitung so in etwa:
"Die Seite kann momentan nicht verarbeitet werden ..."
Auch so eine Meldung erhielt ich nicht.

**Comment by frase-git** [comment]
Was ist mit Proxy?

**Comment by manu37** [comment]
> 
> 
> > Ich konnte in keinem Fall eine weiße Seite erzeugen.
> 
> Ah, "weiße Seite" ist wohl das Stichwort. Würde einfach aus dem Cache gezogen, dann wäre ja Inhalt da. Sieht also nach einem schweren Fehler aus – vielleicht eine unendliche Umleitung?

Es ist keine "weisse" Seite, sondern ein Aufruf ohne query im Admin. Gab früher "no page selected".
In diesem Fall wird `./?Start` aus dem (DNS)-cache weitergeleitet an `./` , und da hat es im Admin keine Seite.

**Comment by cmb69** [comment]
> In diesem Fall wird ./?Start aus dem (DNS)-cache weitergeleitet an ./ , und da hat es im Admin keine Seite.

Mit dem [DNS-Cache](https://de.wikipedia.org/wiki/DNS-Caching#:~:text=DNS%2DCaching%20h%C3%A4lt%20das%20Ergebnis,zust%C3%A4ndigen%20Nameservern%20anfragen%20zu%20m%C3%BCssen.) hat das auf jeden Fall nichts zu tun. Und das Client-/Proxy-Caching sollte eigentlich verboten worden sein. Ich konnte das auf die schnelle auch nicht reproduzieren; versuche es heute Abend noch einmal.

**Comment by manu37** [comment]
![301](https://user-images.githubusercontent.com/712682/92941019-21cf0d80-f450-11ea-9c39-249e25431937.jpg)

**Comment by cmb69** [comment]
Danke! Aber wo ist der `Cache-Control` Antwortheader?

**Comment by lck-git** [comment]
> Danke! Aber wo ist der `Cache-Control` Antwortheader?

Ich weiß nicht was genau du damit meinst. Ungeachtet dessen hier mal mein Screenshot der Network DevTools beim Aufruf von `www.example.com/?Start` per Menü im Backend im Vorschau-Modus.

![DevTools_Network_Start](https://user-images.githubusercontent.com/22255655/92954311-8182e400-f463-11ea-8076-cb775ebff5ee.gif)

**Comment by lck-git** [comment]
@cmb69: Meintest du das?

![Antwortheader_Cache-Control](https://user-images.githubusercontent.com/22255655/92955700-eb03f200-f465-11ea-85c1-56b4f33d8810.gif)

**Comment by lck-git** [comment]
> Es ist keine "weisse" Seite, sondern ein Aufruf ohne query im Admin. Gab früher "no page selected".

Im Edit-Mode beim Wechsel von der Seite `?Templates` zu `?Start` per Meü erscheint dann schon wieder `No page selected`.


[mau37 wrote:]
> Meine Installation liegt auf `http://localhost/cmsimplegit/`. Developer Tools ausgeschaltet, Cache aktiv.
> 
> * `http://localhost/cmsimplegit/?Start` aufrufen.
> * Gehe zu `Templates` (via Menü).
> * Login
> * Schalte auf view mode/Vorschau
> * Gehe zu `Start `(via Menü).

Wichtig zum Nachvollziehen, Browsercache vorher unbedingt komplett löschen! Und, www.example.com/?Start, das `?Start` händisch in die Adressleiste des Browsers eingeben.

**Comment by cmb69** [comment]
> Meintest du das?

Ja. Also ist "Kann es sein, dass der Browser da einfach sehr aggressiv cached?" wohl mit ja zu beantworten. Er kann schließlich nicht wissen, dass die 301 Response mit anderen Cache-Headern ausgeliefert würde, und ignoriert diese Möglichkeit einfach.

Jedenfalls: wenn wir das 301 zu 302 ändern, haben wir wieder DC, den wir ja gerade verhindern wollten.

Vielleicht im Template ergänzen: "This page is best viewed with IE4" ;)

**Comment by olape-git** [comment]
> * `http://localhost/cmsimplegit/?Start` aufrufen.
> * Gehe zu `Templates` (via Menü).
> * Login
> * Schalte auf view mode/Vorschau
> * Gehe zu `Start `(via Menü).
> 
> Wie sieht die Startseite aus?

Weiß :-(, ok jetzt habe ich es auch.
Aber, warum in aller Welt sollte ich als Admin vor dem Login manuell ?Start aufrufen?
Denn da fängt es ja an.
Die Umleitung soll für den Besucher sein, für vielleicht noch bestehende Verlinkungen usw.
Natürlich kann man nicht ausschließen, dass das mal passieren könnte

> Gab früher "no page selected".

Genau das war eben nicht immer der Fall. Auf das Problem sind wir letztens erst gestoßen und haben es darum auf 1.8 verschoben. Wenn es denn so wäre, das immer "no page selected" gekommen wäre, dann hätte die Umleitung auch in allen Fällen gegriffen. Hat sie aber nicht. https://github.com/cmsimple-xh/cmsimple-xh/issues/458

> Jedenfalls: wenn wir das 301 zu 302 ändern, haben wir wieder DC, den wir ja gerade verhindern wollten.

Genau das ist das Problem

**Comment by lck-git** [comment]
> Also ist "Kann es sein, dass der Browser da einfach sehr aggressiv cached?" wohl mit ja zu beantworten. Er kann schließlich nicht wissen, dass die 301 Response mit anderen Cache-Headern ausgeliefert würde, und ignoriert diese Möglichkeit einfach.

Komisch, in Firefox (neueste Version 80.0.1) kann ich das Problem nicht reproduzieren. In Chrome, Iron, Edge und Opera schon. Cached also Firefox nicht so aggressiv(?).

**Comment by olape-git** [comment]
Also ich habe 80.0.1 (64-Bit) und es ist wie Manu schreibt.

Wer das gleiche mal in der 1.7.2 probiert, aber statt des letzten Schrittes, als zu Start per Menü mal (bei fhs-simple) das XH Logo im Kopf nutzt, also ./ aufruft, wird feststellen, dass das auch hier schon nur eine "weisse" Seite gibt, keine "no Page selected".

**Comment by cmb69** [comment]
Ich habe noch mal darüber nachgedacht: eigentlich liegt das Problem bei CMSimple_XH; der Adminbereich sollte besser eigene URLs haben. Aber das ist definitiv nicht auf die Schnelle lösbar.

Aber das 301 ist sowieso nicht richtig (auch ohne Adminbereich). Wenn index.php?Start immer auf index.php weiter leitet, dann gibt es Probleme, wenn eine neue Startseite eingefügt wird, da die alte Startseite gar nicht mehr aufgerufen werden könnte. Ein 302 (oder eher 307) wäre hier wohl richtiger. Den DC kann man so wohl nicht vermeiden.

**Comment by lck-git** [comment]
> Wer das gleiche mal in der 1.7.2 probiert, aber statt des letzten Schrittes, als zu Start per Menü mal (bei fhs-simple) das XH Logo im Kopf nutzt, also ./ aufruft, wird feststellen, dass das auch hier schon nur eine "weisse" Seite gibt, keine "no Page selected".

Richtig und ist auch immer noch so. Ist das gleiche Problem wie bei einem Sprachwechsel https://github.com/cmsimple-xh/cmsimple-xh/issues/458.

**Comment by frase-git** [comment]
Also, tatsächlich. Wenn ich die Browser-Caches vorher richtig putze und das Caching explizit einschalte(!), dann habe ich die leere Seite in beiden Browsertypen (Vivaldi und FF 80.0.1). Das hat lange gedauert, bis ich das geschafft habe.

Andererseits betrifft das ja wirklich nur Admins - und nur wenn man so vorgeht, wie Manu beschreibt. Oder wie Olaf im vorhergehenden Post schreibt.
Merken wir uns das für 1.8 vor und versuchen wir eine Lösung zu finden.
Ich denke, es ist kein Weltuntergang (war ja auch schon in 1.7.2 ähnlich) und sollte 1.7.4 jetzt nicht weiter aufhalten.
Oder?

**Comment by olape-git** [comment]
> Wenn index.php?Start immer auf index.php weiter leitet, dann gibt es Probleme, wenn eine neue Startseite eingefügt wird, da die alte Startseite gar nicht mehr aufgerufen werden könnte.

Das ist zwar richtig. Natürlich kann sich da mal was ändern. Aber wenn ich das als gegeben nehmen würde, dann dürfte man nirgends mehr mit 301 arbeiten.
Vielleicht könnte man im Backend für die erste veröffentlichte Page mit `&normal` oder `&edit` im Link arbeiten, dabei greift die gecachte 301 nicht.

**Comment by cmb69** [comment]
> Das ist zwar richtig. Natürlich kann sich da mal was ändern. Aber wenn ich das als gegeben nehmen würde, dann dürfte man nirgends mehr mit 301 arbeiten.

Sehe ich nicht wirklich so. Prinzipiell ist an 301 Weiterleitungen nichts auszusetzen. Aber mit XH 1.7.3 ist es nicht mehr möglich eine Seite, die einmal Startseite war, durch eine andere Startseite zu ersetzen; und wenn man es dennoch tut, dann merkt man vielleicht nicht einmal, dass es für manche nun nicht mehr möglich ist, die alte Startseite einzusehen. Das finde ich nicht unproblematisch, zumal es wohl Fälle gibt, wo eine andere Startseite temporär geschaltet wird.

**Comment by olape-git** [comment]
> PS: ist es denn wirklich DC, wenn http://example.com/ und http://example.com/?Start die selbe Seite liefern? 

Ja, zwei URLs, der identische Inhalt.

> Ich meine, man kann doch oft beliebige (weitere) Parameter in der URL ergänzen (z.B. http://example.com/?&unbekannt=123), und bekommt dann auch die selbe Seite.

Ich weiß, das hatte ich auch schon mal angebracht. Das kann man aber nur verhindern, wenn man konsequent alle unbekannten Parameter entfernt. Das Problem haben (min. fast) alle Sites / Systeme. Mir wäre jetzt keine(s) bekannt, dass unbekannte Parameter entfernt.
Wäre ein guter Ansatz, aber ist wohl kaum umsetzbar.

> Vielleicht könnte man im Backend für die erste veröffentlichte Page mit `&normal` oder `&edit`

Warum eigentlich ist es Backend nicht generell so, dass bei Inhaltsseiten `&normal` oder `&edit` dran hängt? **Eine feste Linie dabei würde das Problem für das Backend lösen.**

> Aber mit XH 1.7.3 ist es nicht mehr möglich eine Seite, die einmal Startseite war, durch eine andere Startseite zu ersetzen; und wenn man es dennoch tut, dann merkt man vielleicht nicht einmal, dass es für manche nun nicht mehr möglich ist, die alte Startseite einzusehen.

Das ist alles richtig. Ist aber kein XH-Problem. Ich bleibe dabei, jede 301, egal ob per PHP oder htaccess hat den selben Effekt. Ändert man daran etwas, wird es immer User geben, bei denen alte Umleitungen aus dem Cache greifen.

Zu 302 oder 307. Da wir sonst eigentlich überall verhindert haben, dass der Link `?Start` auftaucht, sollte das eh nur noch ein Ausnahmefall sein. Von daher, wenn es nicht einfach umsetzbar ist immer mit `&normal` und `&edit` zu arbeiten, ist das wohl die „Krücke“ die wir greifen müssen. :-(

**Comment by manu37** [comment]
> ...
> Zu 302 oder 307. Da wir sonst eigentlich überall verhindert haben, dass der Link `?Start` auftaucht, sollte das eh nur noch ein Ausnahmefall sein. Von daher, wenn es nicht einfach umsetzbar ist immer mit `&normal` und `&edit` zu arbeiten, ist das wohl die „Krücke“ die wir greifen müssen. :-(

Sehe ich auch so, entschuldigt den Aufruhr.
In der freien Wildbahn wird `./?Start` nicht anzutreffen sein ausser bei "bösen" Absichten. Aber die Auswirkungen davon sind umso gravierender und keiner weiss dann Bescheid. 
Auch mein Vorschlag: ein 302/307 (ist ja gerade und speziell nur für diesen Fall) und gut ist.

**Comment by olape-git** [comment]
> Sehe ich auch so, entschuldigt den Aufruhr.

Es ist doch gut, dass dir das aufgefallen ist. Nur so können wir doch Lösungen finden.

**Comment by olape-git** [comment]
Die Alternative wäre, das https://github.com/cmsimple-xh/cmsimple-xh/issues/458 vollständig zu lösen. Das würde für den speziellen Fall zwei sich aufhebende Umleitungen ergeben, aber nach dem ersten Aufruf wäre das Problem aus der Welt, jedenfalls für den Admin.

**Comment by cmb69** [comment]
> Ich weiß, das hatte ich auch schon mal angebracht. Das kann man aber nur verhindern, wenn man konsequent alle unbekannten Parameter entfernt. Das Problem haben (min. fast) alle Sites / Systeme. Mir wäre jetzt keine(s) bekannt, dass unbekannte Parameter entfernt.
Wäre ein guter Ansatz, aber ist wohl kaum umsetzbar.

Ist dafür denn ein kanonischer Link nicht die pragmatische Lösung?

> Warum eigentlich ist es Backend nicht generell so, dass bei Inhaltsseiten &normal oder &edit dran hängt? Eine feste Linie dabei würde das Problem für das Backend lösen.

Das wäre auf jeden Fall möglich, und vielleicht auch die sauberere Lösung gewesen, aber ich fürchte dieser Zug ist abgefahren, da Plugins diese Query-Parameter wohl selten setzen.

**Comment by olape-git** [comment]
> Ist dafür denn ein kanonischer Link nicht die pragmatische Lösung?

Ganz allgemein ja, für diesen speziellen Fall bringt er natürlich nix.

Ok, dann 302 / 307. es bleibt wohl momentan nichts anderes übrig.

**Comment by olape-git** [comment]
Wie wäre das?
Nach https://github.com/cmsimple-xh/cmsimple-xh/blob/09827436341382c2f64c2a72ca2c96f977a629cb/cmsimple/seofuncs.php#L77
`header("Cache-Control: no-cache, no-store, must-revalidate");` einsetzen!

Dann bleibt es eine 301.

**Comment by manu37** [comment]
Ich nehme an, bei den header commands um Zeile 95 rum. Im gleichen Zug könntest Du ja noch Zeile 73 etwas dokumentieren. Wegen Augenkrebs und so.

**Comment by olape-git** [comment]
> Ich nehme an, bei den header commands um Zeile 95 rum.

Nein, als Zeile 78. Fügt man es bei 93-95 ein, wirkt sich das auf alle Umleitungen aus. Es geht hier ja aber nur um Umleitung der Startseite.

> Im gleichen Zug könntest Du ja noch Zeile 73 etwas dokumentieren. Wegen Augenkrebs und so.
Da muss ich mal sehen, was ich mir dabei so gedacht hatte.

**Comment by olape-git** [comment]
>  Im gleichen Zug könntest Du ja noch Zeile 73 etwas dokumentieren. Wegen Augenkrebs und so.

Also, die Kurzfassung: Zeile 73 ersetzt $su (Ausgewählte URL) im Query-String durch NIX.

Etwas länger: 
- nur wenn $su am Anfang steht, es wäre ja möglich, dass der Query-String so aussieht: ?aaaa/bbbb/aaaa.
- preg_quote - maskiert Zeichen regulärer Ausdrücke, ist also nur Mittel zum Zweck.
- -1 --> setzt kein Limit, ist aber sowieso Standardeinstellung
- $fpp_count --> zählt einfach, ob eine Ersetzung stattgefunden hat.

**Comment by lck-git** [comment]
> Wie wäre das?
> Nach
> 
> https://github.com/cmsimple-xh/cmsimple-xh/blob/09827436341382c2f64c2a72ca2c96f977a629cb/cmsimple/seofuncs.php#L77
> 
> 
> `header("Cache-Control: no-cache, no-store, must-revalidate");` einsetzen!
> Dann bleibt es eine 301.

Getestet, funktioniert! Das Problem wäre somit behoben :).

**Comment by manu37** [comment]
Machst Du es rein @olape-git Olaf? So kleine bug fixes können IMHO auch direkt im 1.7 Branch committed werden. 
Merci

**Comment by olape-git** [comment]
Kann man die Beschreibung nachträglich noch ändern/hinzufügen? Für GitHub-Anfänger bitte! :-(

**Comment by olape-git** [comment]
Ich hoffe, jetzt passt es halbwegs

**Comment by cmb69** [comment]
> Kann man die Beschreibung nachträglich noch ändern/hinzufügen? Für GitHub-Anfänger bitte! :-(

Man kann, sollte aber nicht. Ist ja auch nicht nötig; man kann ja einfach einen weiteren Commit machen. :)
