### ISSUE TITLE
Formatting of the mails from the contact form disturbed

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#470]
(lck-git hat diesen Fehler entdeckt)

Wenn im Kontaktformular die beiden nicht erforderlichen Felder Name und Telefonnummer nicht ausgefüllt wurden, dann hat die versendete Mail keine Zeilenumbrüche an diesen Stellen. Es sieht dann so aus:

Name: Telefon-Nr.: E-Mail-Adresse: max@muster.de

Ich denke, das ist ein Bug.

**Comment by olape-git** [comment]
ich kann das nicht bestätigen. Unterschiedliche Absender und Empfänger, Webmail und Outlook

![image](https://user-images.githubusercontent.com/35469568/93132391-d4fc6880-f6d5-11ea-8ede-3777cd1c59f6.png)

![image](https://user-images.githubusercontent.com/35469568/93132330-be561180-f6d5-11ea-9237-c6bed95f09ed.png)

**Comment by cmb69** [comment]
@frase-git, was hast du denn bei `$cf['mailform']['lf_only']` eingestellt?

**Comment by olape-git** [comment]
Aha, auf dem iPad sehen die selben zwei E-Mails aus, wie von Ludwig beschrieben, alles in einer Zeile bis auf die Nachricht selbst.
Schein also (auch) abhängig vom E-Mail-Client.

**Comment by cmb69** [comment]
Der relevante Code ist wohl
https://github.com/cmsimple-xh/cmsimple-xh/blob/59e2c6d494b7248a24c887e886ae75edb439fcb5/cmsimple/classes/Mailform.php#L171-L172
`::sendername` und `::senderphone` sind im gegebenen Fall leere Zeichenketten (siehe `::__construct()`). Ganz unabhängig von der Darstellung, scheint es mir nicht sinnvoll `Telefon-Nr.:` zu schreiben. Entweder die Zeile ganz weglassen, oder etwas wie `Telefon-Nr.: N/A` (der tatsächliche Text sollte dann per Sprachdatei konfiguriert werden können).

**Comment by frase-git** [comment]
> ... was hast du denn bei $cf['mailform']['lf_only'] eingestellt?

Ist im Originalzustand - leer.

**Comment by olape-git** [comment]
> Der relevante Code ist wohl

Aber warum ignorieren EINIGE Mail-Clients den Zeilenumbruch? Der wird ja auch gesetzt, wenn `::sendername` und `::senderphone` leer ist.
Das ergeibt doch irgendwie keinen Sinn.
Erst hatte ich fast den Verdacht, das es vielleicht teilweise als html statt als txt interpretiert würde, aber dann dürften gar keine Umbrüche funktionieren und das immer, auch wenn _Name_ und _Telefon_ ausgefüllt wäre.

Übrigens, auch hier habe ich weider das Problem, dass Outlook (zumindest 2010) die E-Mails teilweise leer anzeigt. Die gleichen E-Mails wie oben beschrieben, per Webmailer kein Problem, im Outlook leer. Da bin ich auch schon mal beim PW-Reset drüber gestollpert.

Haben wir vielleicht einen Fehler im grundsätzlichen Aufbau der E-Mail?

**Comment by cmb69** [comment]
Wir versenden Text-E-Mails, aber so mancher Client erzwingt wohl gerne HTML, und anscheinend fällt die Übersetzung nicht unbedingt nach unseren aus. Fände ich HTML-Mail nicht so Banane, dann würde ich jetzt vorschlagen, dass wir Multipart-Mails mit Text und HTML Version senden.

**Comment by olape-git** [comment]
> Wir versenden Text-E-Mails, aber so mancher Client erzwingt wohl gerne HTML

Aber dann müssten eben alle Zeilenumbrüche verschwinden, nicht nur die bei leeren Eingabefeldern. Das ist doch alles nicht logisch. Es ist letztenendes ein Sring mit Zeilenumbruch, egal ob das Feld leer war oder ausgefüllt.

Ich bin jetzt nochmal alles, was mit dem Mailversand zusammenhängt (Headerangaben, lineEnding, ...) durchgegangen. Ich kann nichts fehlerhaftes entdeecken. Ich wüsste nicht was wir ändern sollten.

> Entweder die Zeile ganz weglassen,

Ich glaube, das wäre die Lösung, sind die Felder leer dann die ganze Zeile weglassen.

**Comment by frase-git** [comment]
Habt ihr euch schonmal den Quelltext der Nachrichten angeschaut?
Ich habe ja keine Ahnung, was normal ist - aber ich finde bei mir keine andere Mail, deren Inhalt so aussieht.

![mail](https://user-images.githubusercontent.com/24246330/93182969-ae244d80-f73a-11ea-965a-0d4fb574b32c.png)

**Comment by olape-git** [comment]
>  aber ich finde bei mir keine andere Mail, deren Inhalt so aussieht.

Ich denke, das liegt daran:
https://github.com/cmsimple-xh/cmsimple-xh/blob/59e2c6d494b7248a24c887e886ae75edb439fcb5/cmsimple/classes/Mail.php#L63

Aber das andere Problem könnten vielleicht Einstellungen wie diese sein:
![grafik](https://user-images.githubusercontent.com/35469568/93183913-e5dfc500-f73b-11ea-9c84-971de045ecfc.png)

**Comment by cmb69** [comment]
> Ich habe ja keine Ahnung, was normal ist - aber ich finde bei mir keine andere Mail, deren Inhalt so aussieht.

Wir haben vor langer Zeit base64 Kodierung eingeführt, weil das ein Problem gelöst hat (nicht sicher welches; im Zweifel das Git-Log befragen). Ist ungewöhnlich, sollte aber an sich keine Probleme bereiten.

> Aber das andere Problem könnten vielleicht Einstellungen wie diese sein:

Gut möglich.

**Comment by frase-git** [comment]
> Aber das andere Problem könnten vielleicht Einstellungen wie diese sein:

Eine solche Einstellung kann ich in Thunderbird nicht finden.
Etwas ähnliches gibt es dort unter "Verfassen", das dürfte hier aber nicht relevant sein.

Vermutlich liegtes an 'base64' .

**Comment by frase-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/blob/59e2c6d494b7248a24c887e886ae75edb439fcb5/cmsimple/classes/Mail.php#L142-L147

**Comment by cmb69** [comment]
> Eine solche Einstellung kann ich in Thunderbird nicht finden.

Der braucht das auch nicht, weil er Textnachrichten einfach als solche darstellt, und sich nicht nach Leibeskräften müht, allen das Leben schwerer zu machen. Und nein, das hat mit base64 gewiss nichts zu tun. Du kannst ja einfach noch ein weiteres Leerzeichen (`"\n"`) einfügen; dann werden die einzelnen Zeilen möglicherweise als eigenständige Paragraphen interpretiert und angezeigt.

**Comment by frase-git** [comment]
> Du kannst ja einfach noch ein weiteres Leerzeichen ("\n") einfügen; dann werden die einzelnen Zeilen möglicherweise als eigenständige Paragraphen interpretiert und angezeigt.

Ha, stimmt.
Dann wäre das ja schon gelöst - falls das **bei allen anderen** auch hift.
Bei mir tut's das.

**Comment by cmb69** [comment]
Ich denke nach wie vor, dass es wenig sinnvoll ist, eine Zeile mit einer leeren Telefonnr. überhaupt auszugeben. Siehe https://github.com/cmsimple-xh/cmsimple-xh/issues/470#issuecomment-692352096.

**Comment by olape-git** [comment]
> Ich denke nach wie vor, dass es wenig sinnvoll ist, eine Zeile mit einer leeren Telefonnr. überhaupt auszugeben. Siehe [#470 (comment)](https://github.com/cmsimple-xh/cmsimple-xh/issues/470#issuecomment-692352096).

Sehe ich auch so. Steht nix drin, dann brauchen wir die Zeile auch nicht.

**Comment by frase-git** [comment]
> Ich denke nach wie vor, dass es wenig sinnvoll ist, eine Zeile mit einer leeren Telefonnr. überhaupt auszugeben. Siehe #470 (comment).

Auch wieder richtig.
Dann aber auch bei leerem Namen die Zeile raus, nicht nur bei Tel.Nr.

Die oben vorgeschlagenen doppelten "\n" erzeugen ja auch bei ausgefülltem Feld die Zeilenschaltung, was auch wieder nicht gut wäre.

Warum hat das bisher noch niemand moniert?
Denken unsere User: Na ja, es ist halt XH - also nicht perfekt.
Oder:
Sind die Formularbenutzer so trainiert, dass sie immer **jedes** Feld ausfüllen, was da ist?

**Comment by cmb69** [comment]
Ich denke, es hat mit der Text → HTML Umwandlung des jeweiligen E-Mail-Client zu tun; diese Umwandlung kann halt sehr "raffiniert" sein (und sich im Lauf der Zeit ändern) und ist u.U. konfigurierbar, so dass das bisher vielleicht wirklich nicht aufgefallen ist.

**Comment by olape-git** [comment]
> Die oben vorgeschlagenen doppelten "\n" erzeugen ja auch bei ausgefülltem Feld die Zeilenschaltung, was auch wieder nicht gut wäre.

Genau.

Mal ganz blöd in die Runde gefragt. Ich kann das jetzt nicht testen. Aber wenn keine Eingabe erfolgt, dann sind die letzten Zeichen im String `: `. Hat mal jemand versucht den Text in den Sprachdatein so abzuändern, dass der : und das Leerzeichen nicht die letzten Zeichen sind? Nur mal so versuchshalber. Eine Erklärung hätte ich schon gern.

Unsere Lösung, das Problem nur zu umgehen, stellt mich nicht so voll zufrieden.

**Comment by frase-git** [comment]
> Hat mal jemand versucht den Text in den Sprachdatein so abzuändern, dass der : und das Leerzeichen nicht die letzten Zeichen sind? Nur mal so versuchshalber. Eine Erklärung hätte ich schon gern.

Doppelpunkt dürfte klar sein, und das Leerzeichen sorgt für Abstand, damit die Dingers nicht aneinender kleben.
Name: Xxxxxx
Telefon-Nr.: 1234567890

Eine Alternaive wäre z.B.:
\*Name\*
Xxxxxx
\*Telefon-Nr\*
1234567890
\*E-Mail\*
...
Andere Formatierungsmöglichkeiten hat man bei TXT kaum.
Ob das besser ist?

**Comment by olape-git** [comment]
> Doppelpunkt dürfte klar sein, und das Leerzeichen sorgt für Abstand, damit die Dingers nicht aneinender kleben.
> Name: Xxxxxx
> Telefon-Nr.: 1234567890
> 
> Eine Alternaive wäre z.B.:
> *Name*
> Xxxxxx
> *Telefon-Nr*
> 1234567890
> *E-Mail*
> ...
> Andere Formatierungsmöglichkeiten hat man bei TXT kaum.
> Ob das besser ist?

Ne, ich will es nicht neu formatieren, ich will nur wissen, warum der Zeilenumbruch verschluckt wird, wenn die Felder nicht ausgefüllt sind. Deshalb hätte ich gern gewusst ob das auch ohne Leerzeichen und Doppelpunkt auftritt. Es muss doch eine irgendwie nachvollziehbare logische Erklärung geben.

**Comment by frase-git** [comment]
> ich will nur wissen, warum der Zeilenumbruch verschluckt wird

Ach so. Meldung folg alsbald.

**Comment by frase-git** [comment]
Aaaalso,
ohne ": " kommt als Mail heraus

> Name
Telefon-Nr
E-Mail-Adresse: example@example.com
test ohne ": "

Wobei vor dem Text noch eine Leerzeile ist, die ich hier nicht darstellen kann.

**Comment by olape-git** [comment]
> Aaaalso,
> ohne ": " kommt als Mail heraus

Also dann verschwinden die Zeilenumbrüche nicht?

**Comment by frase-git** [comment]
> Also dann verschwinden die Zeilenumbrüche nicht?

Exakt!

Noch genauer:
Es genügt, das Leerzeichen am Ende zu entfernen. Der Doppelpunkt kann bleiben.

Wenn man also das (Abstands-)Leerzeichen in der Mailform.php reinsetzte, dann wäre alles OK und die Zeilen könnten sogar stehen bleiben (falls du das willst).

**Comment by olape-git** [comment]
Also müsste theoretisch statt:
https://github.com/cmsimple-xh/cmsimple-xh/blob/59e2c6d494b7248a24c887e886ae75edb439fcb5/cmsimple/classes/Mailform.php#L171-L172

`rtrim($tx['mailform']['sendername'] . $this->sendername) . "\n"`
`. rtrim($tx$tx['mailform']['senderphone'] . $this->senderphone) . "\n"`

das Problem lösen.

**Comment by frase-git** [comment]
Nein. rtrim entfern das Leerzeichen und die Teile kleben aneinander.
Vor `. $this->sendername) .` und vor ` . $this->senderphone . ` muss ein Abstand (oder eine weitere Zeilenschaltung) eingefügt werden.

**Comment by olape-git** [comment]
Hast du probiert?
Denn eigentlich sollte das Leerzeichen nur verschwinden, wenn Name und Telefonnummer leer bleiben.

Das ganze bedeutet übrigens, wenn ich nichts übersehen habe, dass ausgefüllte Felder mit Leerzeichen am Ende den gleichen Effekt auslösen würden.

**Comment by frase-git** [comment]
Hm, wenn ich in der zweiten Zeile deines Codes das doppelte "$tx" korrigiere, passiert folgendes:

Ohne Name und Nr.:

> Name:
Telefon-Nr.:
E-Mail-Adresse: example@example.com

Mit Eingabe:

> Name:Tester
Telefon-Nr.:1234567890
E-Mail-Adresse: example@example.com

Also: Name:Tester kleben aneinander.

**Comment by frase-git** [comment]
Haha, ich Dummer ich!
Ich hatte in der Sprachdatei noch das Leerzeichen entfernt.

Die Mail mit Eingabe sieht so aus:

> Name: Tester
Telefon-Nr.: 1234567890
E-Mail-Adresse: example@example.com

Also alles bestens!
Sorry, solche Schnelltests sind fehleranfällig.

**Comment by olape-git** [comment]
ok, dann müssen wir uns nur entscheiden, ob rtrim oder Zeile weglassen

**Comment by frase-git** [comment]
> ok, dann müssen wir uns nur entscheiden, ob rtrim oder Zeile weglassen

Hm, siehe den Nachsatz in meinem letzten Post.
Das ist unschön und auch fehleranfällig, wenn man mal was ändern will.

Eigentlich finde ich es gar nicht so schlecht, wenn Name: und Telefon-Nr.: solo dastehen bleiben.
Da sieht man gleich, welche Felder nicht ausgefüllt wurden.

**Comment by olape-git** [comment]
> Eigentlich finde ich es gar nicht so schlecht, wenn Name: und Telefon-Nr.: solo dastehen bleiben.
> Da sieht man gleich, welche Felder nicht ausgefüllt wurden.

Davon ausgehend, dass ausgefüllte Felder mit Leerzeichen am Ende den selben Effekt auslösen (ungetestet), ist die Variante rtrim wohl tatsächlich die bessere Wahl.

**Comment by frase-git** [comment]
Denke ich auch.
Trimmen, um BC Break zu vermeiden.
Zukünftig Sprachvariablen ohne Leerzeichen am Ende.
Dann muss aber irgendein Abstand wieder reingeschmuggelt werden. Oder denke ich da falsch?

**Comment by olape-git** [comment]
> Zukünftig Sprachvariablen ohne Leerzeichen am Ende.

Das ist sicher die einfachere Übung. Bei neuen Variablen kann man das richtig anlegen.

Aber die bestehenden zu ändern, wird wohl nicht so ohne weiteres funktionieren. Allerings weiss ich jetzt nicht, um wie viele es sich handelt. Da müsste man dann sicher an einigen Stellen span-Tags mit reinbringen, um das dann per CSS regeln zu können.
Also definitiv ein BC-Break.

**Comment by olape-git** [comment]
ok, also Christoph, Manu Ludwig, Holger!

**Wie wollen wir das hier nun lösen?**

**Comment by frase-git** [comment]
cmb69 wrote:

> Wir versenden Text-E-Mails, aber so mancher Client erzwingt wohl gerne HTML, und anscheinend fällt die Übersetzung nicht unbedingt nach unseren aus. Fände ich HTML-Mail nicht so Banane, dann würde ich jetzt vorschlagen, dass wir Multipart-Mails mit Text und HTML Version senden.

Da Christoph in advanced-Mail mittlerweile auch html-Versand anbietet, ist diese Idee vielleicht gar nicht so schlecht (und Banane auch nicht ;-) )
Dann würde ich auch noch auf das base64 verzichten.

**Comment by olape-git** [comment]
> Da Christoph in advanced-Mail mittlerweile auch html-Versand anbietet, ist diese Idee vielleicht gar nicht so schlecht (und Banane auch nicht ;-) )
> Dann würde ich auch noch auf das base64 verzichten.

Dann sollten wir das vielleicht damit verbinden https://github.com/cmsimple-xh/cmsimple-xh/issues/332

Jetzt brauchen wir eine Lösung für 1.7.4

**Comment by frase-git** [comment]
> Dann sollten wir das vielleicht damit verbinden #332

Einverstanden. Gerne.

> Jetzt brauchen wir eine Lösung für 1.7.4

Da schlage ich vor, alles so zu lassen, wie es ist (ich meine die Sprachvariablen).
Deine zwei trim-Zeilen rein.
Dann werden also auch die leeren Felder (Name und Tel.Nr.) übertragen - und die Optik stimmt.

Das geht schnell und genügt für 1.7.4
Alles andere beratschlagen und für 1.8 vorsehen.

**Comment by cmb69** [comment]
> Eigentlich ist das hart kodiertes Styling.

Man kann Text-Mails nicht stylen. Natürlich sollte das Leerzeichen nicht in der Sprachvariable stehen, sondern im Programmcode, und zwar nur dann, wenn auch Name/Telefonnummer angegeben werden.

> (und Banane auch nicht ;-) )

Na ja, vielleicht bin ich einfach nur zu blöd für HTML-Mail, aber das einzige Mal, dass ich um Haaresbreite Phishern auf den Leim gegangen wäre, war eben eine HTML-Mail. Bei Textmail wäre mir das garantiert nicht passiert (da sieht man nämlich auf was man klickt).

Auf jeden Fall: wenn wir Multipart Mail versenden wollen, dann sollten wir eine Bibliothek verwenden (PHP-Mailer vielleicht). Wird ansonsten einfach zu komplex.

**Comment by frase-git** [comment]
Alles gut.

Aber, was sagst du zum Vorschlag für 1.7.4?

**Comment by cmb69** [comment]
Ja, passt schon, aber wir sollten eben ein Leerzeichen einfügen, falls Name/Telefonnummer angegeben wurden.

**Comment by frase-git** [comment]
> Ja, passt schon, aber wir sollten eben ein Leerzeichen einfügen, falls Name/Telefonnummer angegeben wurden.

Im Moment (und das wollen wir für 1.7.4 nicht ändern) sind in den Sprachvariablen die Leerzeichen standardmäßig dran.
Ist nichts eingegeben, werden die Leerzeichen entfernt (Zeilenumbruch).
Ist etwas eingegeben, dann ist alles sowieso OK (bleibt wie es ist).

Damit haben wir schon 3 Stimmen dafür.
@lck-git, @manu37, @TN03

**Comment by lck-git** [comment]
Konnte heute Nachmittag leider an der Diskussion nicht teilnehmen. Also mal kurz überflogen und eigene Tests angestellt.
Es würde sogar reichen bei
```
$tx['mailform']['sendername']="Name: ";
$tx['mailform']['senderphone']="Telefon-Nr.: ";
```
das Leerzeichen am Ende durch ein geschütztes Leerzeichen (auf Tastatur: ALT+0160) zu ersetzen. Aber dann müssten halt alle ausgelieferten Sprachdateien geändert werden.

**Comment by olape-git** [comment]
> Aber dann müssten halt alle ausgelieferten Sprachdateien geändert werden.

Und daran scheitern wir beim Update.

**Comment by frase-git** [comment]
@lck-git 
Die Leerzeichen am Ende einiger Sprachvariablen wollen wir in Zukunft weg haben bzw. durch Programmcode ersetzen. Viel zu leicht zu übersehen bei Übersetzungen oder Änderungen usw. Im Moment sind sie aber da - und das können wir nicht so schnell ändern.
Für 1.7.4 hat Olaf [einen Fix](https://github.com/cmsimple-xh/cmsimple-xh/issues/470#issuecomment-692647775) vorgeschlagen, der den Darstellungsfehler behebt, den du entdeckt hattest.
Könntest auch du das mal testen und das Ergebnis mitteilen?
Dann könnten wir (Olaf) das noch für 1.7.4 einarbeiten.
Alles andere müssen wir noch diskutieren und für 1.8 planen.

**Comment by lck-git** [comment]
> Für 1.7.4 hat Olaf [einen Fix](https://github.com/cmsimple-xh/cmsimple-xh/issues/470#issuecomment-692647775) vorgeschlagen, der den Darstellungsfehler behebt, den du entdeckt hattest.
> Könntest auch du das mal testen und das Ergebnis mitteilen?

Getestet, passt jetzt. Zeilen werden umgebrochen, getestet mit Thunderbird und Windows Live Mail 2012. Wobei in Live Mail die Zeilenumbrüche auch vorher schon da waren, ohne Anpassung der Mailform.php. 

Im Fix ist aber ein Fehler, ein$tx ist hier zuviel
`. rtrim($tx$tx['mailform']['senderphone'] . $this->senderphone) . "\n"`

**Comment by frase-git** [comment]
> Im Fix ist aber ein Fehler, ein$tx ist hier zuviel

Ja, das wurde [hier](https://github.com/cmsimple-xh/cmsimple-xh/issues/470#issuecomment-692657318) schon festgestellt ;-)

Also @olape-git, es sieht nach mehrheitlichem Einverständnis aus.
Soll ich noch ein bisschen Chaos veranstalten indem **ich** einen PR erstelle, oder könntest du uns das ersparen?

**Comment by olape-git** [comment]
das werden wir uns sparen, denke ich jedenfalls.

@manu37 , @cmb69
Wieder direkt in die 1.7? Ich versuche es diesmal auch mit Beschreibung. Da hatte ich kletztens nicht aufgepasst, weil ich es dieekt online gemacht hatte.
