### ISSUE TITLE
Template -fhs-simple-2019 td respTable css missing?

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#471]
@frase-git: Auf ./?Templates/TEMPLATE-fhs-simple-2019/Template-specific-styles ist die Tabelle .respTable beschrieben. Nur funktioniert das "schmale" Design nicht. Im CSS ist auch nichts zu finden. Ist das bei Euch auch so?

**Comment by frase-git** [comment]
> Ist das bei Euch auch so?

Leider ja.
Da ist bei meinen internen Tests etwas stehen geblieben.
https://github.com/cmsimple-xh/cmsimple-xh/blob/3fd0da0c9d5e492f30a14e3bdab0fe1c67ce078c/templates/fhs-simple-2019/stylesheet.css#L972

Es ist auskommentiert - muss aber aktiv sein.
Kannst du das "schnell" ändern?
Danke!

**Comment by manu37** [comment]
Das kann ich gerne machen. 
Meine Frage ist aber weitaus komplizierter:
- kurze Version: wird bei einem merge die ./content/content.htm nicht aktualisiert??
- lange Version: Ich habe meinen Branch "API-Call" und habe diesen mit 1.7 aktualisiert, sprich ich machte einen merge 1.7 -> API-Call. Keine Konflikte, na gut. Unverständlicherweise hat es mir aber nicht die content.htm als Konflikt gemeldet (da hatte ich Änderungen im meiner Version), nein sogar ignoriert. Das beunruhigt mich doch etwas. Was hat es sonst noch ignoriert ohne eine Wartung? Weiss evtl. @cmb69 eine Antwort?

**Comment by cmb69** [comment]
Bei einem Merge müssten Konflikte eigentlich festgestellt werden; war dein ausgecheckter 1.7 Branch möglicherweise nicht mit dem origin Branch synchron? Aber grundsätzlich halte ich solche Merges für falsch; man macht da besser einen Rebase.

**Comment by manu37** [comment]
Vom Resultat her sollte doch beim merge oder rebase dasselbe rauskommen (immer schön den 1.7er vorher gepulled).

**Comment by cmb69** [comment]
Ja, schon, aber beim mergen hat man halt einen zusätzlichen Commit, der eigentlich unnötig ist.

**Comment by cmb69** [comment]
Ah, fällt mir gerade ein: ich verwende eigentlich `git merge` immer nur mit der `--ff-only` option. :)
