### ISSUE TITLE
Standard templates

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#473]
[https://cmsimpleforum.com/viewtopic.php?f=16&t=16780&start=10#p77669](https://cmsimpleforum.com/viewtopic.php?f=16&t=16780&start=10#p77669)

> Ich möchte, dass richu172_2 in der nächsten Version nicht mehr ausgeliefert wird.

**Comment by olape-git** [comment]
Das wäre ja eigentlich erledigt.

**Comment by cmb69** [comment]
Tatsächlich: https://github.com/cmsimple-xh/cmsimple-xh/commit/62068791d82bad88ac96d0a64c9da5076ba40fab
