### ISSUE TITLE
1.8 Branch setup - questions

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#475]
Hallo Alle
Im Master sind jetzt alle 1.7er Entwicklungen gemerged. Laut unserer [heiligen Schrift](https://wiki.cmsimple-xh.org/doku.php/core_development#git_branching_strategy) sollte ein neuer Branch ab dem Master gezogen werden. Darum bitte ich Euch, mal kurz den Master auszutesten, ob da wirklich alle 1.7 Funktionen greifen und nicht andersweitige Funktionen auftauchen (laut Log sollte alles ok sein, aber man weiss ja nie). Im Prinzip würde jetzt die Entwicklung im Master laufen (Master branchen, erweitern, PR einreichen). 
Ich habe da aber eine grundsätzliche Frage: Wie ist es, wenn jetzt jemand schon an der 2.0 werkelt und dies gemäss Anleitung im Master tut? Dann wird es schwierig, vom Master ein 1.8 Branch abzuleiten (der auf 1.7.x folgt). Bin ich jetzt etwas begriffsstutzig oder ist da ein Denkfehler in unserer Anleitung? @cmb69 was meinst Du dazu?

**Comment by cmb69** [comment]
1.7 und master sollten gleich sein: https://github.com/cmsimple-xh/cmsimple-xh/compare/master...1.7. Für einen gründlichere Prüfung könnte man beide Branches herunterladen, und dann diffen.

> Wie ist es, wenn jetzt jemand schon an der 2.0 werkelt und dies gemäss Anleitung im Master tut?

Das wäre ein Problem. So wie wir es handhaben, muss immer klar sein, welche Version der "master" Branch mal werden soll. Also am besten vorab klären, ob als nächstes 1.8 oder 2.0 kommt. Der Unterschied ist nur, ob bei der nächsten Version Inkompatibilitäten eingeführt werden *können*/*sollen*.

**Comment by olape-git** [comment]
So, ich habe mal die 1.7 und den Master runtergeladen und durch WinMerge geschickt.
Danach sind beide vollständig identisch.
![image](https://user-images.githubusercontent.com/35469568/101887744-8e67be80-3b9d-11eb-9360-7ccf4d19347f.png)

**Comment by manu37** [comment]
Sehr gut, danke Olaf!

> 
> 
> 1.7 und master sollten gleich sein: [master...1.7](https://github.com/cmsimple-xh/cmsimple-xh/compare/master...1.7). Für einen gründlichere Prüfung könnte man beide Branches herunterladen, und dann diffen.
> 
> > Wie ist es, wenn jetzt jemand schon an der 2.0 werkelt und dies gemäss Anleitung im Master tut?
> 
> Das wäre ein Problem. So wie wir es handhaben, muss immer klar sein, welche Version der "master" Branch mal werden soll. Also am besten vorab klären, ob als nächstes 1.8 oder 2.0 kommt. Der Unterschied ist nur, ob bei der nächsten Version Inkompatibilitäten eingeführt werden _können_/_sollen_.

Demnach würde ich die Aussage, immer im Master zu entwickeln, doch sehr hinterfragen. Ich denke, sobald klar ist, in welchen Milestone die Entwicklung gehört, einen entsprechenden Branch anlegen und dort entwickeln. Die Regel, vorzu in den Master zu mergen kann ja bleiben (obwohl dies auch Konflikte birgt). Müssen wir unser Wiki dazu anpassen?

**Comment by olape-git** [comment]
> Müssen wir unser Wiki dazu anpassen?

Wenn es unstimmige Aussagen gibt, ja.

mal ne andere Frage: Kann ich gefahrlos die ganzen Branches löschen, die ich so für 1.7.3 und .4 verzapft habe?
Das wird mir hier zu unübersichtlich.

**Comment by cmb69** [comment]
> Ich denke, sobald klar ist, in welchen Milestone die Entwicklung gehört, einen entsprechenden Branch anlegen und dort entwickeln.

Nicht verkehrt. Aber wenn ich bedenke, wie es seit langem läuft, könnten wir auch ganz auf die Version-Branches verzichten; letztlich arbeiten wir doch immer nur an der nächsten Version. Und sollte es dazu kommen, dass wir an 1.8 arbeiten, und doch noch etwas in 1.7 nachbessern müssen, können wir immer noch einen 1.7 Branch erstellen, und relevante Commits cherry-picken.

> mal ne andere Frage: Kann ich gefahrlos die ganzen Branches löschen, die ich so für 1.7.3 und .4 verzapft habe?

Ja. das sollte kein Problem sein.

**Comment by cmb69** [comment]
> Aber wenn ich bedenke, wie es seit langem läuft, könnten wir auch ganz auf die Version-Branches verzichten; letztlich arbeiten wir doch immer nur an der nächsten Version. Und sollte es dazu kommen, dass wir an 1.8 arbeiten, und doch noch etwas in 1.7 nachbessern müssen, können wir immer noch einen 1.7 Branch erstellen, und relevante Commits cherry-picken.

Ich glaube, dass wir das in der Zwischenzeit auch so beschlossen hatten. Oder habe ich das einfach so gemacht – oder bilde ich mir das nur ein?

**Comment by olape-git** [comment]
> Ich glaube, dass wir das in der Zwischenzeit auch so beschlossen hatten. Oder habe ich das einfach so gemacht – oder bilde ich mir das nur ein?

Das ist schon OK so. Ob wir das nun beschlossen hatten, das weiß ich auch nicht mehr. Ist aber auch egal.
Es macht die Sache einfacher und darauf kommt es an.

**Comment by cmb69** [comment]
Okay, dann kann dieses Ticket geschlossen werden.
