### ISSUE TITLE
No logout after changing password due to OPcache

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#477]
In XH 1.7.4 wird man nach dem Ändern des Passworts nicht sofort ausgeloggt, erst nach einem Page-reload  oder bei Klick auf einen Link. In XH 1.7.3 wurde sofort ausgeloggt. Kann jemand das nachvollziehen?

**Comment by olape-git** [comment]
Also ich fliege mit der 1.7.4 sofort raus.

**Comment by cmb69** [comment]
Aus dem Kopf: ich meine das Logout wird per serverseitigem Redirect durchgeführt; vielleicht schlägt dieser Fehl?

**Comment by lck-git** [comment]
> Aus dem Kopf: ich meine das Logout wird per serverseitigem Redirect durchgeführt; vielleicht schlägt dieser Fehl?

Wie könnte man das sichtbar machen, wo kann man das sehen/überprüfen?

Ich habe das Problem auf drei verschiedenen Servern, lokal unter Xampp nicht. Auf bplaced.net (frische Installation) tritt es auch auf, falls das mal jemand testen möchte. Hab das auch mit verschiedenen Browsern getestet.

Bei FF ist es so.
1) Ändert man das Passwort und speichert, dann  wird in der Seite angezeigt "Keine Seite ausgewählt", man ist noch nicht ausgeloggt.
2) Klick auf "Start", wird man ausgeloggt.

**Comment by olape-git** [comment]
> Wie könnte man das sichtbar machen, wo kann man das sehen/überprüfen?

Eigentlich sollte das passieren:

```
Status Code	URL	IP	Page Type	Redirect Type	Redirect URL
302	http://localhost/xh-devs-9/?&xh_change_password	127.0.0.1	server_redirect	temporary	http://localhost/xh-devs-9/
200	http://localhost/xh-devs-9/	127.0.0.1	normal	none	none
```

Ich habe jetzt aber noch nicht nachgesehen, wo das ausgelöst wird.

**Comment by lck-git** [comment]
So ganz kann ich das nicht nachvollziehen. Am besten ich schicke dir per PM mal den Link zur Website zum Testen.

**Comment by cmb69** [comment]
> Ich habe jetzt aber noch nicht nachgesehen, wo das ausgelöst wird.

Das passiert in [ChangePassword::saveAction()](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.4/cmsimple/classes/ChangePassword.php#L148-L161).

> Wie könnte man das sichtbar machen, wo kann man das sehen/überprüfen?

In der Browserkonsole, und zwar zunächst im Network-Tab (da sollte der Status-Code eigentlich 302 sein, wie Olaf schon schrieb). Falls das so ist, dann in den Response-Headers des POST-Requests von `?&xh_change_password` nach dem Location-Header suchen und prüfen, ob dieser okay ist. Falls der Status-Code nicht 302 ist, dann in o.g. Funktion debuggen. Wird vielleicht das `exit` ignoriert (ist die PHP-Erweiterung uopz installiert?). Wird dieser Code überhaupt ausgeführt (`$o .= XH_message('info', 'dies wurde ausgeführt);` einfügen)?

Kann auch sein, dass bereits Ausgabe erzeugt wurde, und darum `header(...)` nichts bewirkt. Dann sollte allerdings ein Warning im DebugMode ausgegeben werden.

**Comment by olape-git** [comment]
Redirect wird erfolgreich ausgeführt. Aber es passiert, was immer passiert, wen man im angemeldeten Zustand das root der Site aufruft. —> „keine Seite gewählt“. (Ludwigs Installation auf bplaced)
Mehr kann ich auch noch nicht sagen, ich musste meinen bplaced-Account erst mal reaktivieren.

**Comment by olape-git** [comment]
1.7.2 auf bplaced das gleiche Problem.
Vielleicht kann man diese Zeile um
`?&logout erweitern`

https://github.com/cmsimple-xh/cmsimple-xh/blob/2bd3332504e47710bb6a49f9eccbfffdab377baa/cmsimple/classes/ChangePassword.php#L156
`            header('Location: ' . CMSIMPLE_URL);`

**Comment by cmb69** [comment]
Probier doch bitte mal https://github.com/cmsimple-xh/cmsimple-xh/blob/2bd3332504e47710bb6a49f9eccbfffdab377baa/cmsimple/classes/ChangePassword.php#L221
durch folgendes zu ersetzen:
````.php
$res = (bool) XH_writeFile($pth['file']['config'], $o);
if (function_exists('opcache_invalidate')) {
    opcache_invalidate($pth['file']['config']);
}
return $res;
````

**Comment by olape-git** [comment]
Damit fliegt man auf bplaced sang- und klanglos raus.
Also eigentlich wie immer.
Ich habe jetzt aber nicht auf anderen Hosts getestet.

**Comment by cmb69** [comment]
> Damit fliegt man auf bplaced sang- und klanglos raus.

Dann ist das tatsächlich ein OPcache-Problem, und da wir beim Speichern der Konfigurations- und Sprachdateien ebenfalls invalidieren, dann sollten wir das hier ebenfalls tun.

**Comment by frase-git** [comment]
Mit den Gratis-Accounts kann man auf bplaced nicht testen!
Da sind zu viele Erweiterungen nicht aktiv (z.B. fsockopen).
Und auch noch ein paar andere Einschränkungen.
Zitat:

> Verbindungen zu anderen Diensten (sog. Socket-Funktionen, wie z.B. „fsockopen” oder cURL) stehen ab bplaced pro zur Verfügung.

**Comment by olape-git** [comment]
> Mit den Gratis-Accounts kann man auf bplaced nicht testen!
> Da sind zu viele Erweiterungen nicht aktiv

Für den Fall wie gemacht

**Comment by cmb69** [comment]
Ist auch nicht bplaced spezifisch; ich kann das lokal reproduzieren, wenn ich `opcache.revalidate_freq=10` in der php.ini einstelle; dann kann ich nach dem Ändern noch knapp 10 sec munter im Backend navigieren, bevor ich ausgeloggt werde. Und wenn `opcache.validate_timestamps=0` ist (empfohlen für Produktivumgebungen), dann werde ich nach Passwordänderung gar nicht ausgeloggt. Man könnte nun höchstens darüber streiten, ob das ein Feature ist (nicht alle bevorzugen ja dieses Logout). ;)

**Comment by olape-git** [comment]
> Man könnte nun höchstens darüber streiten, ob das ein Feature ist (nicht alle bevorzugen ja dieses Logout). ;)

Da wir das ja aber nicht beeinflussen können.
Logout oder nicht? Ehrlich, mir ist das egal. Wie oft macht man das denn?



> und da wir beim Speichern der Konfigurations- und Sprachdateien ebenfalls invalidieren, dann sollten wir das hier ebenfalls tun.

Aber dem entnehme ich, dass es auch an anderer Stelle Probleme aufwerfen kann. Dann sollten wir das auch beheben.

**Comment by cmb69** [comment]
> Aber dem entnehme ich, dass es auch an anderer Stelle Probleme aufwerfen kann. Dann sollten wir das auch beheben.

Ja, der Password-Reset ist auch davon betroffen, und da wird es dann wirklich garstig.
