### ISSUE TITLE
replace FA icons in configuration fields with SVGs

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#478]
Um Abhängigkeiten vom FA-Plugin zu vermeiden, sollten die FA-Icons bei den Checkboxen durch SVGs ersetzt werden.
Dazu müssen zwei Grafiken im Ordner assets/css/ hinzugefügt werden.
[check-on-off-svg.zip](https://github.com/cmsimple-xh/cmsimple-xh/files/5724367/check-on-off-svg.zip)
Danach müssen [diese Zeilen](https://github.com/cmsimple-xh/cmsimple-xh/blob/e3cc319f5317f6556bd23a68ad61e9209eab68b5/assets/css/core.css#L1569-L1590) durch folgende ersetzt werden:
```
div.xh_field input[type="checkbox"]::after {
	content: "";
	color: #fff;
	position: absolute !important;
	top: -1px !important;
	left: -1px !important;
	width: 1.75em !important;
	height: 1.5em !important;
	transition: left 0.1s cubic-bezier(0.785, 0.135, 0.15, 0.86) !important;
	text-align: center;
	line-height: 1.5;
	background: #666 url(xh-check-off.svg) no-repeat center center;
	background-size: contain;
}
div.xh_field input[type="checkbox"]:checked::after {
	background-image: url(xh-check-on.svg);
}
div.xh_field input[type="checkbox"]:checked {
	background-color: #3c0 !important;
	border-color:#ccc !important;
}
```

**Comment by cmb69** [comment]
Oh, ja, das muss geändert werden. Danke für den Patch!
