### ISSUE TITLE
Get rid of font icons/Fa_XH plugin in the backend

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#479]
sie https://cmsimpleforum.com/viewtopic.php?f=12&t=16943&start=10#p78501

**Comment by cmb69** [comment]
This has already been [resolved for the core](c47fa33b343b54afaeb25d6ef5b123cca44b4a32), but the filebrowser still needs Fa_XH, what is not that much of an issue, but should be changed anyway, since Fa_XH should not be used by plugins any longer, due to version conflicts of FontAwesome.

**Comment by frase-git** [comment]
> ... but the filebrowser still needs Fa_XH

... and the page manager as well.
In the assets folder there are already some SVG icons - for historical reasons they are colored.
Maybe you should create a whole set of the most needed icons - maybe monochrome, with the dark grey background of the default admin menu? These would then be universally applicable, for the backend in general, for plugins - and maybe even for the content, if you build a Tiny plugin for it.

I don't know exactly how it is with the copy rights at FA - if it's just about making SVGs out of the font glyphs, then I guess it's pretty quick and straightforward.
With a list of the needed icons (can be extended later), I could tackle that.
For "real own" (rights free), the effort would be much bigger.

**Comment by cmb69** [comment]
Ah, right, Pagemanager! However, this is still an external plugin, so I've just filed https://github.com/cmb69/pagemanager_xh/issues/73.

I don't think that I'll switch to SVG; I'm currently toying with the idea of using the https://github.com/google/material-design-icons fonts; shouldn't be hard to do a few renames (so that it won't clash with other uses), and bundle that with a separate plugin (maybe Pfw_XH).

**Comment by frase-git** [comment]
This is quite an acceptable idea. Above all, I like the integration with PFW.

Whether FontAwesome or Google's Material design icons, or any other font - it doesn't matter. In the end, it's again a dependency on external sources. Who guarantees that Google won't change something, like FontAwesome did the other day?

With an XH icon set we would achieve a bit more uniformity in the backend. (Just look at hi_updatecheck).

**Comment by lck-git** [comment]
> Whether FontAwesome or Google's Material design icons, or any other font - it doesn't matter. In the end, it's again a dependency on external sources.

> I don't think that I'll switch to SVG;

Proposal. How about pure CSS icons?
In case of need we can customize, design and extend them ourselves.

[Example](https://css.gg/), MIT license.  Small file 418 kB, minified 318 kB.

**Comment by frase-git** [comment]
> Proposal. How about pure CSS icons?
> In case of need we can customize, design and extend them ourselves.
> Example, MIT license. Small file 418 kB, minified 318 kB.

Pure CSS icons are also a great idea.
However, making your own icons seems non-trivial to me. Besides, this solution also has all the disadvantages mentioned above.
(Additionally, all icons are block elements, for whatever reason, and coloring and size must be controlled with extra CSS rules.)

We should form a "working group" and think about it again ;-)

**Comment by cmb69** [comment]
> In the end, it's again a dependency on external sources. Who guarantees that Google won't change something, like FontAwesome did the other day?

I would choose a hard fork anyway. Renaming (font names, style selectors, etc.) would ensure there are no issues with other uses, and I don't see much issues regarding *required* updates; that stuff likely works for decades (maybe not that great, but still). Frankly, could use a renamed FA4 as well, but so much would have to be renamed there; looks for Material Icons that would be way less work (okay, fewer icons, but might just be sufficient).

> We should form a "working group" and think about it again ;-)

I'm open to that, but I don't want to spend much time on it. I'm using Fa_XH in way more plugins than I thought, and switching to something else is already quite time consuming.

> With an XH icon set we would achieve a bit more uniformity in the backend. (Just look at hi_updatecheck).

hi_updatecheck might be well served with the built-in `.xh_success`, `.xh_fail`, `.xh_warning` and `.xh_info` classes.

> Proposal. How about pure CSS icons?
In case of need we can customize, design and extend them ourselves.

Haven't heard of that so far (thanks!) However, we could design font icons as well, if need be; the discussion about that might easily take longer than the actual design even for a beginner. :)
