### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#482]
Would that make sense?
There is still a long way to go until 1.8.

**Comment by cmb69** [comment]
The biggest issue regarding PHP 8 are likely plugins and addons (and maybe their interactions with the core), and perhaps some templates. Until CMSimple_XH has a version which is compatible with PHP 8, issues in extensions are unlikely to be addressed, or even found in the first place. So I'm +1 on doing this ASAP.

**Comment by olape-git** [comment]
> Until CMSimple_XH has a version which is compatible with PHP 8, issues in extensions are unlikely to be addressed, or even found in the first place. So I'm +1 on doing this ASAP.

One more reason.
But it will be a compromise solution.
Because we can't reduce the support for PHP to 7 and 8 in 1.7.

**Comment by cmb69** [comment]
> Because we can't reduce the support for PHP to 7 and 8 in 1.7.

Well, we still need to support PHP 5.3.7, but that shouldn't be a real issue; it's just that we can't use some PHP 7 goodies to catch potential early.

**Comment by olape-git** [comment]
In my tests with the basic 1.7.4 installation, it seems that this fix is actually the only problem.

https://github.com/cmsimple-xh/cmsimple-xh/blob/eae190362b30f0293f8a6193c4fd6a3a94206627/cmsimple/classes/Li.php#L77
to `$this->b = ((int) $this->st) - 1;`

I can't see any other things like that.
That would be swell.

**Comment by cmb69** [comment]
You likely hit #484 with XH 1.7.4 as well. The real problem is that manual testing is likely to miss most issues; without a comprehensive test suite and/or static analysis a lot of edge cases will only be found by users.

**Comment by olape-git** [comment]
![image](https://user-images.githubusercontent.com/35469568/111071233-76257980-84d5-11eb-8b53-19011d67c3fa.png)

I can't relate to that, everything is as it should be with me.

**Comment by cmb69** [comment]
It happens for `'show_last_edit'=>''` (not with `'show_last_edit'=>'0'`); the problem is https://3v4l.org/v4p2U.

**Comment by olape-git** [comment]
ok, versuchen wir es mal in de.
Ich verstehe offensichtlich das Problem nicht.

Ich habe bei den Seiten-Parametern keinerlei Meldung, weder von XH noch von Apache.
Nicht, wenn ich den unveränderten originalen Content verwende, noch wenn ich Einstellungen ändere oder diese wieder auf den Urzustand setze.
Alles funktioniert wie gewohnt.

**Comment by cmb69** [comment]
Wenn ich ein unmodifiziertes XH 1.7.4 unter PHP 8 laufen habe, und dann die Page-Params der "Template"-Seite anschaue, dann ist weder bei "Show last edit" noch bei "Redirect page" etwas vorbelegt. Das liegt daran dass der Vergleich `"" == 0` unter PHP 8 eben `false` ist, so dass kein "selected" ausgegeben wird.

Dieses Problem ist im "master" gelöst, aber ich vermute es gibt halt noch viele andere Stellen (gerade auch in Plugins), wo ähnliches passiert. Es ist grundsätzlich keine gute Idee, `==` zu verwenden, eben weil PHP da doch sehr speziell ist, und sich "Details" unter PHP 8 ändern.

Aber egal, wir können nicht alles manuell überprüfen, und sollten im Zweifel eben PHP 8 Kompatibilität dokumentieren, und eventuelle Bugs dann halt zeitnah beheben.

**Comment by olape-git** [comment]
Ah, ok.
Jetzt die Frage, ohne lange darüber nachgedacht zu haben.
Warum ist das nicht bei Start, Start-DE, Content oder Inhalt-DE so?
Das fängt wirklich erst bei Templates an.

**Comment by cmb69** [comment]
Dort ist eine `'0'` eingetragen (das passiert seit einigen Versionen(?) beim Speichern, aber "Templates" wurde wohl schon eine Weile nicht mehr gespeichert).

**Comment by olape-git** [comment]
ok, dann hätten wir das auch geklärt.

> Aber egal, wir können nicht alles manuell überprüfen, und sollten im Zweifel eben PHP 8 Kompatibilität dokumentieren, und eventuelle Bugs dann halt zeitnah beheben.

Das wird dann wohl nicht anders werden.

**Comment by olape-git** [comment]
Habe heute mal den aktuellen Master gezogen und unter 8.0.0 laufen gelassen.
Ich habe keinerlei Fehlermeldungen, ich kann auch nicht festellen, dass irgendwas nicht funktionieren würde.
👍

**Comment by cmb69** [comment]
Super! Dann, denke ich, können wir dieses Ticket schließen.
