### ISSUE TITLE
Document that API parameter names are subject to change

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#483]
PHP 8.0.0 introduces [named arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments), which are a nice feature, but would lock parameter names of XH APIs (and I have some doubts, that we want to stick with all of them in the long run; review pending). Therefore, I suggest to clearly document that all parameter names are subject to change, and none of the XH APIs should be called using named arguments for now.

**Comment by olape-git** [comment]
Do you have an example of this?

**Comment by cmb69** [comment]
`li(ta: $hc, st: 1)` would not be more readable than `li($hc, 1)`, but would prevent that we rename the parameters to something readable (maybe $pages and $start). I don't suggest to rename the parameters right away, because that would likely lead to a lot of bikeshedding, and there are more important issues.

**Comment by olape-git** [comment]
I'm not sure I understand this correctly.
Where would we possibly want to rename it?

In principle, it should be possible to use both variants at the same time without changing the function.

**Comment by cmb69** [comment]
My point is not so much that we will or should change the parameter names, but rather that we leave the possibility to rename them open.

**Comment by olape-git** [comment]
I think I'm beginning to understand where you're going.
I had not studied this at all, just skimmed what changes there are in PHP 8
