### ISSUE TITLE
jQuery - set default version to last stable version

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#489]
As [v1 + v2 are definitely EOL](https://stackoverflow.com/questions/60389461/is-there-anything-like-end-of-support-for-jquery-versions-similar-to-end-of-life) we should roll out our standard release with the latest stable jQuery version setting (after profound testing). 
Or do we get rid of jQuery completely? Anyway, even the jQuery Plugin should be provided with the latest stable jQuery setting setting.

**Comment by cmb69** [comment]
I don't think we can drop jQuery anytime soon; it's used by too many plugins (even pagemanager still relies on it; I hope that there will be [jsTree 4](https://github.com/vakata/jstree/tree/v.4.0)) and templates.

I agree that we should switch to using jQuery 3 by default as of CMSimple_XH 1.8.0.

**Comment by cmb69** [comment]
It's probably a good idea to do this for 1.7.6 already.

**Comment by olape-git** [comment]
Update to [jQuery 3.6.4](https://code.jquery.com/jquery-3.6.4.min.js) and [jQuery Migrate 3.4.0](https://code.jquery.com/jquery-migrate-3.4.0.min.js) ?

**Comment by olape-git** [comment]
<img width="340" alt="jQuery 2023-03-13 104525" src="https://user-images.githubusercontent.com/35469568/224665537-f4621609-0b3e-4464-8428-254e9ed012d2.png">

**Comment by olape-git** [comment]
Perhaps we should also remove versions 1 and 2 of jQuery altogether?

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/jQuery_XH/tree/v1.6.6
