### ISSUE TITLE
Fix link checker

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#49]
[Forum discussion](http://cmsimpleforum.com/viewtopic.php?t=7566)

**Comment by cmb69** [comment]
Anybody willing to do this? Otherwise I would suggest to remove the link checker from the core (IMO it's broken by design). If there's any need to keep the current link checker alive, it could be moved to a plugin.

**Comment by manu37** [comment]
Even if the link checker has its drawbacks and bugs IMHO it's still a strong feature to fix broken links.

**Comment by cmb69** [comment]
Since there is no fix in sight, we should document the limitations. :)

**Comment by cmb69** [comment]
[Documentation](http://www.cmsimple-xh.org/wiki/doku.php/validate_links) is now available – closing.

**Comment by olape-git** [comment]
https://github.com/olape-git/cmsimple-xh/commit/bcc3916a1ba720f4fe349836c6a35b9273facdd4
