### ISSUE TITLE
TinyMCE5 - replace TinyMCE4

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#492]
As TinyMCE4 has reached its EOL, it should be replaced by TinyMCE5.

**Comment by olape-git** [comment]
:+1:

**Comment by manu37** [comment]
**TinyMCE5 inits as JSON?**
Dies wäre der ideale Moment, um die init files auf JSON umzustellen.
Vorteile:
Der init Code könnte auf seine Gültigkeit geprüft werden und wäre robuster gegen JS Fehler. Diese können abgefangen und als Fehlermeldung ausgegeben werden.
Der init Code kann viel einfacher verarbeitet werden und ist einfacher anzupassen, wenn gewünscht. Theoretisch können gewünschte Settings per Konfigutation eingestellt werden.
Nachteile:
Der JSON Code des init Files [sieht etwas anders aus](https://medium.com/@easyexpresssoft/object-literal-vs-json-7a2084872907) als der JS Literal, wie es tiny.cloud vorschlägt. Das könnte zu kleineren Konfusionen führen, wenn jemand Beispielcode von [tiny.cloud](https://www.tiny.cloud/docs/demo/basic-example/) kopiert.
```
{
  "table_advtab": true,
  "table_cell_advtab": true,
  "table_style_by_css": true,
  "image_advtab": true,
  "image_title": true,
  "importcss_append":true,
  "style_formats_autohide": true,
  ....
}
```
Wie ich sehe, hat das @cmb69 im [codeeditor](https://github.com/cmb69/codeeditor_xh) bereits vor Jahren umgesetzt.

Was meint ihr dazu? Thumbs up/down?

**Comment by cmb69** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/commit/d53633d841d5d711f50c25c919b78f929d7f53aa has added TinyMCE 5, but for 1.7 we need to still ship TinyMCE 4. Anyhow, this can be closed now in favor of PR #507.

**Comment by manu37** [comment]
> [d53633d](https://github.com/cmsimple-xh/cmsimple-xh/commit/d53633d841d5d711f50c25c919b78f929d7f53aa) has added TinyMCE 5, but for 1.7 we need to still ship TinyMCE 4. Anyhow, this can be closed now in favor of PR #507.

Why? TinyMCE5 can get rolled out. Default in full install. On updates, the cms config file is unchanged. (TinyMCE4 is still there, could be remarked in deleted_files.txt). The user desides which editor he/she (still) uses.
