### ISSUE TITLE
Debug output leftover in functions.php

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#493]
https://github.com/cmsimple-xh/cmsimple-xh/blob/a401977094dc59f2ae2f0fbe0b4a9b665a7fc2da/cmsimple/functions.php#L1637

**Comment by cmb69** [comment]
No, that's a bug.

**Comment by cmb69** [comment]
I'm going to remove the 1.7.5 milestone, since this bug has been introduced after 1.7.4, and it would be confusing to list it in the changelog.
