### ISSUE TITLE
Better usability of Softhypens in Pagemanager

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#500]
https://github.com/cmsimple-xh/cmsimple-xh/compare/master...olape-git:softhypens-toc

In the page manager you can set softhypens with "ALT + 0173" (as before) or with "|-|".
Softhypens are always displayed as "|-|".
Until now, it was not possible to see softhypens in the page manager.

**Comment by cmb69** [comment]
I still consider special soft hyphen support for Pagemanager_XH to be the wrong approach. I wonder whether soft hypens in page headings are even needed. If they are, PR #501 appears to be a more general solution. Otherwise, why not leave it as it is?

**Comment by cmb69** [comment]
I'm closing the vote. The feature has been accepted with 2:1 votes.
