### ISSUE TITLE
No WebP preview available in filebrowser

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#503]
It would be time to support the newer image formats with better compression at good quality by CMSimple_XH - especially `*.webp`. Theoretically it is already possible to use these formats, but you don't get to see an image preview.

**Comment by cmb69** [comment]
Das überlappt mit #294, aber da ist insgesamt mehr zu berücksichtigen. Ich bin einfach mal so frei und ändere den Titel, und stufe die fehlende WebP-Vorschau als Bug ein, der noch in XH 1.7.5 gelöst werden sollte.

**Comment by cmb69** [comment]
To clarify: this fix will only work as of PHP 7.0.10.

**Comment by frase-git** [comment]
`$plugin_cf['filebrowser']['extensions_images']="gif, jpg, jpeg, png, svg, webp";`
... ist aber auch noch nötig.
Dann ist es wohl Sache der Dokumentation:
"Wenn du `webp` angezeigt bekommen möchtest, dann musst du min. PHP 7.0.10 haben und in der Config `webp` hinzufügen."

**Comment by cmb69** [comment]
> Wirft das dann bei kleineren PHP-Versionen einen Fehler?

Nein, da wird einfach keine Vorschau angezeigt. Eigentlich nett, weil es User vielleicht zum Update bewegen wird. :) Und man muss ja nicht an die große Glocke hängen, dass die Vorschau bei PHP 5 ab PHP 5.6.25 auch funktioniert.

> $plugin_cf['filebrowser']['extensions_images']="gif, jpg, jpeg, png, svg, webp";

Ich denke, dass sollten wir einfach noch machen. Bei Updates ist die Änderung irrelevant, und bei Neuinstallationen sehe ich kein Problem

**Comment by frase-git** [comment]
Gut.

**Comment by cmb69** [comment]
Done; 8ff44d6610b7eb5d8e52c19898514428a156013c.
