### ISSUE TITLE
Adapt XH_redirectSelectedUrl to SEO betterments

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#509]
Especially when selecting the startpage (with further query string): selected='' doesn't do anything. Selected=Shop (=startpage) forces a redirect by loosing the query string. Would be nice to have this clarified to step up with XH_Shops issues https://github.com/cmsimple-xh/xhshop/issues/204.

**Comment by cmb69** [comment]
Hmm, not sure I understand. With a clean XH 1.7.5, `?&selected=Start&foo=bar` redirects to `?&foo=bar` (regardless whether I'm admin or not) – what am I missing?

**Comment by manu37** [comment]
> 
> 
> Hmm, not sure I understand. With a clean XH 1.7.5, `?&selected=Start&foo=bar` redirects to `?&foo=bar` (regardless whether I'm admin or not) – what am I missing?
You are right. I cannot reproduce it either. My XH_Shop Problems lie somewhere else.
