### ISSUE TITLE
Languages and File Manager in TinyMCE 5

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#511]
See https://cmsimpleforum.com/viewtopic.php?f=29&t=17823&start=20#p80895

https://github.com/cmsimple-xh/cmsimple-xh/tree/master/plugins/tinymce5/tinymce/langs

1) Download and install latest language files from  [https://www.tiny.cloud/get-tiny/language-packages/](url)

2) Non-downloadable language files, but /plugins/tinymce5/tinymce/langs existing ones, check line starts and correct if necessary, e.g. `tinymce.addI18n('fr_FR',{` change to `tinymce.addI18n('fr',{`

3) Install empty en.js as well to display the toolbar of the Tiny in the second language en as well (if the main language of the website is set to de).

4) Enlarge the File Manager window. For example see
Insert > Image > Source
https://cmsimpleforum.com/viewtopic.php?f=29&t=17823&start=30#p80899

**Comment by cmb69** [comment]
Thank you! @manu37, could you please take care of this?
