### ISSUE TITLE
hi_updatecheck, add tinymce5

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#512]
https://cmsimpleforum.com/viewtopic.php?f=29&t=17823&start=10#p80879

Add tinymce5 to Ignore List.
https://github.com/cmsimple-xh/cmsimple-xh/blob/c4b663617a50721806c0a117e6b18d2739062636/plugins/hi_updatecheck/config/config.php#L6

**Comment by cmb69** [comment]
Thanks! I'm leaving that open for now, since I'm not sure whether @manu37 prefers to have TinyMCE 5 as "internal" plugin.

**Comment by cmb69** [comment]
Okay, TinyMCE 5 [will be integrated as "internal" plugin](https://cmsimpleforum.com/viewtopic.php?t=17823&p=80909#p80909), so this ticket is obsolete.
