### ISSUE TITLE
$tx['login']['warning'] in de.php is missing trailing period

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#513]
https://github.com/cmsimple-xh/cmsimple-xh/blob/af724b3eaaf24e6c8ce07b70c794b801c3809f4e/cmsimple/languages/de.php#L185
Addition at the end with a dot.
`$tx['login']['warning']="Administrationsbereich. Bitte Passwort eingeben.";`

**Comment by cmb69** [comment]
Thank you!
