### ISSUE TITLE
Increase maxsize default of images and downloads

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#514]
https://github.com/cmsimple-xh/cmsimple-xh/blob/c4b663617a50721806c0a117e6b18d2739062636/cmsimple/config.php#L28
https://github.com/cmsimple-xh/cmsimple-xh/blob/c4b663617a50721806c0a117e6b18d2739062636/cmsimple/config.php#L29

I think we should raise these values.
A value of 5000000 seems reasonable to me.

**Comment by cmb69** [comment]
[`upload_max_filesize`](https://www.php.net/manual/en/ini.core.php#ini.sect.file-uploads) still defaults to 2MB, so 5MB may be confusing. Perhaps set both to `2000000`?

**Comment by frase-git** [comment]
Set both to 5000000.

**Comment by manu37** [comment]
Very nice! If you use the powerfull ImageUpload/Image Editor in TinyMCE5 (drag&drop images) you upload usually the original image before you resize it in the image editor.

**Comment by lck-git** [comment]
> Very nice! If you use the powerfull ImageUpload/Image Editor in TinyMCE5 (drag&drop images) you upload usually the original image before you resize it in the image editor.

Now is that negative or positive?

Frank has great practical experience and if he also recommends 5 MB, then that seems to be necessary after all.
What speaks against it?

**Comment by cmb69** [comment]
On further consideration, I don't see an issue with having a larger size than possibly configured for PHP, since there is a clear error message as well, and at least PHP might avoid the big upload to fully happen in that case. So I'm fine with `5000000`.

**Comment by manu37** [comment]
> 
> 
> > Very nice! If you use the powerfull ImageUpload/Image Editor in TinyMCE5 (drag&drop images) you upload usually the original image before you resize it in the image editor.
> 
> Now is that negative or positive?
> 
> Frank has great practical experience and if he also recommends 5 MB, then that seems to be necessary after all.
> What speaks against it?

That's definitely positive! I'm a big fan of ImageUpload and Image Editor. It eases the regular jobs of uploading and resizing/cropping pictures. You can say it's quicky&dirty but it makes the job so quick and easy. Inserting pictures out of the clibboard(a section copied from the screen) etc.

**Comment by cmb69** [comment]
We may consider to drop these configuration settings altogether in 1.8 or later (perhaps after some deprecation phase). They don't make really sense to me.
