### ISSUE TITLE
Remove duplicate rules from filebrowser/css/stylesheet.css

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#516]
https://github.com/cmsimple-xh/cmsimple-xh/blob/21f274d75aebf6fbd927064b16468c1c90b01045/plugins/filebrowser/css/stylesheet.css#L132
`a.xhfbfile span,
span.xhfbfile span {
	display: none;
}`

https://github.com/cmsimple-xh/cmsimple-xh/blob/21f274d75aebf6fbd927064b16468c1c90b01045/plugins/filebrowser/css/stylesheet.css#L148

**Comment by cmb69** [comment]
Ah, right, thanks! Which one would you prefer to keep?

**Comment by frase-git** [comment]
> Ah, right, thanks! Which one would you prefer to keep?

Im Zweifel immer den letzten Eintrag stehen lassen - denn der gilt sowieso.
