### ISSUE TITLE
filebrowser stylesheet.css

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#517]
https://github.com/cmsimple-xh/cmsimple-xh/blob/21f274d75aebf6fbd927064b16468c1c90b01045/plugins/filebrowser/css/stylesheet.css#L40

`div.xhFilebrowserDiv ul li,
div.xhFilebrowserDiv ul ul li,
div.xhFilebrowserDiv ul ul ul li {
	list-style-type: none !important;
	list-style-image: none !important;
	list-style-position: inside !important;
	padding: 4px 0 0 2px !important;
	white-space: nowrap !important;
	margin: 0 !important;
}`

add `cursor: pointer;`

**Comment by frase-git** [comment]
> That doesn't look right to me. I can place the mouse pointer between any of the `<li>`s, and clicking would do nothing.

So ist es.
Wenn man den Pointer unbedingt haben will, dann müsste man folgendes hinzufügen:
```
span.xhfbfile {
    cursor: pointer;
}
span.xhfbfile  span {
    cursor: default;
}
```
Bei dieser Gelegenheit ist mir aufgefallen, dass beim Bilde-Einfügen, man auch auf das Bild klicken kann.
Es passiert zwar nichts auffälliges, aber die Konsole wirft einen Fehler!

**Comment by lck-git** [comment]
> Wenn man den Pointer unbedingt haben will, dann müsste man folgendes hinzufügen:

Ja natürlich, war gestern Abend noch ein Schnellschuss bevor ich es wieder vergesse ;)
Ich bin dafür! Dann ist es so wie im Dateimanager.


> Bei dieser Gelegenheit ist mir aufgefallen, dass beim Bilder-Einfügen, man auch auf das Bild klicken kann.
Es passiert zwar nichts auffälliges, aber die Konsole wirft einen Fehler!

Da sollte eigentlich das Bild in einem neuen Tab geöffnet werden, zumindest ist das so beim Dateimanager. Ich glaube das ist ein BUG.

> Uncaught Error: Expected value to be string
    at theme.min.js:9
    at setLink (?filebrowser=editorbrowser&editor=tinymce5&prefix=./&type=image:12)
    at HTMLSpanElement.onFileChoose (filebrowser.min.js:20)

**Comment by cmb69** [comment]
Fixed as a3ff7e7c6abb8f12184fdce8374c69b4df716068 and 9654ef2f731125175ef9fa963d7b03659574315b, respectively.
