### ISSUE TITLE
TinyMCE 5 Plugins: missing languages

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/cmsimple-xh#521]
[xhplugincall/langs](https://github.com/cmsimple-xh/cmsimple-xh/tree/master/plugins/tinymce5/tinymce/plugins/xhplugincall/langs)
Why are there only 3 language files here? Normally there are 13 in [TinyMCE 4](https://github.com/cmsimple-xh/cmsimple-xh/tree/master/plugins/tinymce4/tinymce/plugins/xhplugincall/langs).

Browser-Console says:

> tinymce.min.js:9 GET http://localhost/cmsimplexh175rc1/plugins/tinymce5/tinymce/plugins/xhplugincall/langs/fr.js net::ERR_ABORTED 404 (Not Found)

**Comment by cmb69** [comment]
@manu37, I think we could just copy the missing files from TinyMCE4. Right? If so, I can do that if your busy. :)

**Comment by lck-git** [comment]
> I think we could just copy the missing files from TinyMCE4. Right? If so, I can do that if your busy. :)

Ja kann man! Das sind nur leere Dateien und somit wird bei denen anscheinend auch "englisch" als Sprache verwendet.

Übrigens, das Issue betrifft auch das codemirror Plugin. Da fehlen auch Sprachfiles vom TinyMCE 4 codemirror Plugin.
Ansonsten gibt's z.B. bei Zweitsprache "fr" folgende Fehlermeldung in der Browser-Console.

> tinymce.min.js:9 GET http://localhost/xh175rc1/plugins/tinymce5/tinymce/plugins/codemirror/langs/fr.js 404 (Not Found)

**Comment by cmb69** [comment]
I've added what was there (and massaged a bit). We should probably reconsider our stance on language files; having them maintained by translators doesn't really work, and for TinyMCE it appears at least empty files are required, so it might be best to bundle additional language files (*.php) (if available and sufficiently up to date) at some point in time.

**Comment by manu37** [comment]
> 
> 
> @manu37, I think we could just copy the missing files from TinyMCE4. Right? If so, I can do that if your busy. :)

Oh yes please.
Thats for the fa, codemirror and xh_plugincall plugins.
