### ISSUE TITLE
Fix case-sensitive parsing of Location headers

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#533]
This is just a reminder so that it will not be forgotten in the next XH version, see:
https://cmsimpleforum.com/viewtopic.php?f=16&t=17678&start=10#p80667
and the Solution:
https://github.com/TN03/hi_updatecheck/pull/5

**Comment by cmb69** [comment]
Already done: https://github.com/cmsimple-xh/cmsimple-xh/commit/0bf71e15fa7a1c40761ecde20c587864854df805 :)

**Comment by frase-git** [comment]
Sorry. I had misplaced my glasses, or it was foggy, or something. ;-)
