### ISSUE TITLE
Contact form: Label for captcha input missing

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#536]
Various html validators complain about a missing label for the captcha input field.
Actually this is not a real bug - I think.
Maybe you could put the hint text ("Please enter this number (spam prevention)" as input label?
This sentence is anyway as `<p>` in the middle of the form and awkward to style.
But means a BC break.

**Comment by frase-git** [comment]
Just now it occurs to me that the above also applies to the textarea.

**Comment by cmb69** [comment]
Right, both inputs should have labels, and I consider the missing labels more like a bug, but let's fix that for 1.8 only.
