### ISSUE TITLE
TinyMCE 5 is not shown on the product pages of XHShop

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#546]
[Reported by hixi](https://cmsimpleforum.com/viewtopic.php?t=18058&p=81955#p81955).

[Possible solution](https://cmsimpleforum.com/viewtopic.php?t=18058&p=81955#p81958). I'm not sure, though, whether that might have unwanted side effects. @manu37, could you please have a look.

**Comment by manu37** [comment]
Is this the 1st occurrance we use tinymce5_replace()? This is really a bug. As I see it, on tinymce5_replace() the hole config establish is missing and the solution above solves that. I don't see any problems with this fix.

**Comment by cmb69** [comment]
There are probably only few plugins which call editor_replace(). I only do that in Coco_XH, and that has the same issue (no editor without the fix).
