### ISSUE TITLE
Upgrade to jQueryUI 1.13.1

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#550]
jQuery 1.13.0 fixed a potential [XSS vulnerability](https://github.com/jquery/jquery-ui/security/advisories/GHSA-gpqq-952q-5327), and although I don't know if any extension would be affected, it appears to be prudent to do the update anyway, and change the default to the new version.

**Comment by olape-git** [comment]
https://cmsimpleforum.com/viewtopic.php?f=42&t=18998&start=210#p86767
