### ISSUE TITLE
TinyMCE5: add GDPR/DSGVO Reminder

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#551]
Set a reminder at config CDN switch and documentation: When using CDN you fetch from a foreign server and leave personal data (IP address) there. On the long term you have to register at tiny.cloud anyway. https://cmsimpleforum.com/viewtopic.php?f=16&t=18239&start=10#p82586

**Comment by cmb69** [comment]
Yeah, we should definitely document this, especially for the case where the editors are used by plugins and made available to non adminstrators. However, there are more cases where external requests are made, and we need to document these as well. At least hi_updatecheck comes to mind, which requests files from whereever the plugins choose to store their version.nfo (and from cmsimple-xh.org for the core). Are there more such cases?

**Comment by olape-git** [comment]
> especially for the case where the editors are used by plugins and made available to non adminstrators.

Yes, for this case that would probably be important

> At least hi_updatecheck comes to mind, which requests files from whereever the plugins choose to store their version.nfo (and from cmsimple-xh.org for the core).

But in this case it is usually not personal data, it is the IP of the server. On the other hand, in case of home/local installation, it is the personal IP.
