### ISSUE TITLE
TinyMCE5: remove imagetools/Image_upload by default?

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#554]
Ausgangslage: TinyMCE5 wird momentan mit [imagetools ](https://www.tiny.cloud/docs-4x/demo/image-tools/)/[image_upload](https://www.tiny.cloud/docs/general-configuration-guide/upload-images/) ausgeliefert. Dies ermöglicht Bilder per drag&drop oder copy&paste einzufügen. Die eingefügten Bilder werden automatisch ins image Verzeichnis hochgeladen. Das kann zu Problemen/Missfallen führen. Die ganze Diskussion ist [hier](https://cmsimpleforum.com/viewtopic.php?f=16&t=18256). 

- Thumbs up für: Belassen der Funktionalität in den _init Dateien. Bei benannten Bilddateien wird (neu) der Dateiname übernommen (beim Update mit Imagetools wird der Dateiname mit einer Versionsnummer ergänzt). Die eingebetteten Bilder im Beispielcontent werden (neu) gefiltert und nicht hochgeladen. Das heisst, auch mit dieser Variante haben diejenigen, die diese Funktionalität nicht anwenden wollen, keinerlei Nachteile.
- Thumbs down für: Imagetools/image_upload in eine separate _init Datei auslagern.

Bitte ab- und mitbestimmen bis 11.03.2022

**Comment by cmb69** [comment]
> Bitte ab- und mitbestimmen bis 11.03.2022

Dann steht das Ergebnis wohl fest: 4:1. Somit bleibt also alles wie es ist, wenn ich es richtig verstanden habe, und dieses Ticket kann geschlossen werden.
