### ISSUE TITLE
empty lines before the content (in the source code)

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#555]
https://cmsimpleforum.com/viewtopic.php?f=16&t=18315&start=40#p83019

https://cmsimpleforum.com/viewtopic.php?f=16&t=18315&start=60#p83037

**Comment by TN03** [comment]
It seems to me that there is a non Ascii character (U+00a0) in every new empty page. You can find them in content.htm and in the "empty" textarea with deactivated WYSIWYG editor. Maybe some left over from splitting etc?
That's the reason why a "simple" trim() etc. fails. Maybe it's better to use the utf-8 functions provided by the core in plugins?

**Comment by olape-git** [comment]
> Maybe some left over from splitting etc?

Yes, I suspect that too.
Once when removing the splitting comment and once when removing the PHP area Page-Data.

**Comment by olape-git** [comment]
Das wäre vielleicht noch etwas für die 1.7.6
