### ISSUE TITLE
Anpassung des Standard-Templates (fhs-simple-2019) an WebKit-Browser

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#556]
Siehe diesen Post und folgende:
https://cmsimpleforum.com/viewtopic.php?f=16&t=18230&start=10#p83055

**Comment by frase-git** [comment]
Das betrifft wahrscheinlich auch die core.css (was noch zu prüfen wäre).

**Comment by cmb69** [comment]
Hm, da sollten wir wohl noch für 1.7.6 was machen; iOS ist schließlich keine unwesentliche Plattform. Hat jemand Zeit, sich das anzuschauen?

**Comment by frase-git** [comment]
> Hat jemand Zeit, sich das anzuschauen?

Zeit? Was ist das?
Ich denke, es ging bisher so und kann bis 1.8 so bleiben (wenn auch mit Bauchschmerzen).
Dann brauchen wir was Neues.

**Comment by olape-git** [comment]
Ich schau mal "meine" Templates durch.
Da habe ich immer eine Lösung drin gehabt.

**Comment by olape-git** [comment]
Aber eigentlich gibt es die Lösung doch schon:
https://cmsimpleforum.com/viewtopic.php?f=16&t=18230&start=20#p83083

**Comment by olape-git** [comment]
So, mal zum Vergleich
wiki ohne Patch
![screen_wiki_vor](https://user-images.githubusercontent.com/35469568/214511776-9fde06d9-e4cc-40d4-9b27-b44e9ae9bd75.jpg)
wiki mit Patch
![screen_wiki_nach](https://user-images.githubusercontent.com/35469568/214511847-1f65e832-95e3-48cd-a44e-98eeb4630137.jpg)

**Comment by olape-git** [comment]
Demo ohne Patch
![screen_demo_vor](https://user-images.githubusercontent.com/35469568/214511945-377a5411-f65a-47dc-b6cf-d980fa19f958.jpg)
Demo mit Patch
![screen_demo_nach](https://user-images.githubusercontent.com/35469568/214511979-5fd55a9f-914a-4138-a2f8-eacbb0586798.jpg)

**Comment by olape-git** [comment]
Demo ohne Patch
![screen_demo_vor2](https://user-images.githubusercontent.com/35469568/214512096-56318e82-0e3d-4bb7-a0e2-cee87b467ad5.jpg)
Zum Vergleich ExpandContract mit Patch

![screen_expand_nach](https://user-images.githubusercontent.com/35469568/214512180-8fa4377f-dba5-45bf-ace3-6681797a5215.jpg)

**Comment by cmb69** [comment]
Danke für die Screenshots, @olape! #568 würde ja nur das Search-Form fixen; soll ich das trotzdem schon einspielen, oder brauchen wir gleich noch weitere Nachbesserungen?

**Comment by frase-git** [comment]
Bin einigermaßen betrübt.
Da ich hier **nichts** testen kann, kann ich auch keine Unterstützung leisten.

**Comment by olape-git** [comment]
> würde ja nur das Search-Form fixen; soll ich das trotzdem schon einspielen, oder brauchen wir gleich noch weitere Nachbesserungen?

Ich denke ja
mit zusätzlich
`#searchbox input[name="search"] {
	-webkit-appearance: none;
	-webkit-border-radius: 0;`
sieht es glaube ich passend aus.
![screen_demo_nach2](https://user-images.githubusercontent.com/35469568/214555536-010cbb39-d82e-451a-904a-722a37d7807d.jpg)

**Comment by cmb69** [comment]
> mit zusätzlich
> `#searchbox input[name="search"] { -webkit-appearance: none; -webkit-border-radius: 0;`
> sieht es glaube ich passend aus.

[Also so](https://github.com/cmsimple-xh/cmsimple-xh/pull/568/files)?

**Comment by olape-git** [comment]
> [Also so](https://github.com/cmsimple-xh/cmsimple-xh/pull/568/files)?

Ja, so habe ich es jetzt in der Demo drin (Screenshot).

**Comment by cmb69** [comment]
Super! Eingespielt.

**Comment by olape-git** [comment]
> IMHO, grundsätzlich sollten wir nur Änderungen machen, wenn das Problem mindestens von einer weiteren Person bestätigt wird.

Dann wären aber schon viele Dinge liegengeblieben.
Ganz grundsätzlich weiß ich, das Apple-User an die runden Button gewöhnt sind.
Steht der Button allein, ist das ja auch nicht wirklich das Problem.
Aber so wie es hier aussah, war es echt Sch...

Ich verstehe dein Problem, wenn man es nicht selber Testen kann ist das Mist, aber das kann man ändern. ;-)

Ich kann es nur empfehlen. Mir ist es regelmäßig ein Graus, wenn ich mich mit Android rumärgern muss.
Ich nutze privat noch ein iPad 5. Generation, Einführung März 2017. Es läuft top, der Akku ist noch sehr gut, es wird immer noch mit Updates versorgt. Das sind jetzt also 6 Jahre. In der Zeit hätte man bei Android schon 2x kaufen müssen, um aktuelle zu bleiben.
Aber diesen Streit möchte ich hier nicht beginnen.

Die Dinge lassen sich leider nicht in irgendwelchen Online-Test-Tools prüfen
Das sollte uns aber nicht veranlassen eine ganze Usergruppe zu vernachlässigen.

> iOS8 ist ja schon etwas in die Jahre gekommen (von 2014), mittlerweile gibt es schon iOS16. Welche Browserversion von Safari läuft den da drauf?

Keine Angst, es ist iOS 16.1 gewesen.
https://developer.apple.com/documentation/safari-release-notes/safari-16_1-release-notes

Ich habe noch ein iPad mit iOS8, aber ich glaube da geht so gut wie gar nix mehr.
Könnte ich glatt mal testen.

**Comment by cmb69** [comment]
> Das sollte uns aber nicht veranlassen eine ganze Usergruppe zu vernachlässigen.

Denke ich auch. Und in diesem Fall bemerkt es der Webmaster selbst wahrscheinlich gar nicht; und ein vorbeischauender Besucher meldet dem Webmaster das Problem nicht, weil er keine Lust auf eine "kaputte" Site hat. Und insbesondere `-webkit-*` Regeln stören mich nicht wirklich.

**Comment by lck-git** [comment]
> Keine Angst, es ist iOS 16.1 gewesen.

Ah ja, ok. Im Forum hast du iOS 8 erwähnt, deswegen meine Bedenken.
Ich habe MacOS Monterey mal in einer VirtualBox in Windows 11 installiert. Da konnte ich im Safari keine Probleme feststellen. 

Wie sieht es dann mit dem Template overlay_03 aus, muss da nicht auch der Fix hinzu?

**Comment by olape-git** [comment]
> Wie sieht es dann mit dem Template overlay_03 aus, muss da nicht auch der Fix hinzu?

Ganz theoretisch ja. Ich hatte es schon geschrieben. Eigentlich müssten alle Eingabefelder und Button damit versehen werden.
Du siehst das auch in den Screenshots beim Themeswitcher. Aber ich hatte auch schon geschrieben, da wo die Felder oder die Buttons allein stehen, finde ich das jetzt nicht ganz so wichtig. Apple-User kennen das Problem, viele bemerken es vielleicht gar nicht, weil es eben fast immer so ist. Aber an einigen Stellen sah es dann wirklich sehr bescheiden aus.
Ich schau heute Abend overlay_03 nochmal durch. Und wenn ich es heute schaffe, teste ich nochmal mit iOS8 ;-)

**Comment by olape-git** [comment]
> Und wenn ich es heute schaffe, teste ich nochmal mit iOS8 ;-)

Schade, das geht wirklich gar nicht mehr. Also alle Seiten unter cmsimple-xh.org können gar nicht geladen werden. Das liegt aber an irgendwelchen Sicherheitsproblemen, aber dafür habe ich jetzt keinen Nerv. Komischerweise, die Seiten unter meiner Domain und unsere Vereinsseite funktionieren, mit einer Warnung, aber dann geht es und sieht auch alles normal aus. Keine Design-Ausreißer.

**Comment by olape-git** [comment]
Von der Demo, also noch Version 2.
Ich habe heute auf die Schnelle keine Möglichkeit mehr für Version 3.
Aber, auch in 2 ist nichts ungewöhnliches zu sehen.
Alles wie erwartet.
![0459A2CE-81E6-42CA-B732-6DF48606843D](https://user-images.githubusercontent.com/35469568/215848836-8cba9325-d3e2-4774-848e-f382a831dc3c.jpeg)
![36652CF1-5AD7-4206-89AE-C071EAD9EA12](https://user-images.githubusercontent.com/35469568/215848846-702368f0-0d9a-4ce1-805e-1c00dad6647d.jpeg)
![020F0D30-9780-4C62-A45F-27C21A0E4B67](https://user-images.githubusercontent.com/35469568/215848850-d45ef608-0681-4bdc-8039-d90cb1b06363.jpeg)

**Comment by lck-git** [comment]
> [“olape-git wrote:]
> Aber, auch in 2 ist nichts ungewöhnliches zu sehen.

Wenn du etwas Zeit hast, schau dir mal die Template-Demo overlay_03 mit dem iPad 5 an und hier das [Mailformular](http://www.cmsimplexh.momadu.de/demos/overlay_03/?&mailform). Normalerweise sind da keine abgerundeten Ecken in den input-Feldern.
Ich habe hier folgenden Fix eingebaut.

```
/* Fix for Browser Safari border-radius issue */
input:not([type="radio"]):not([type="checkbox"]) {
    -webkit-appearance: none;
    -webkit-border-radius: 0;
    appearance: none;
    border-radius: 0;
}
```
@ Alle
Wenn das so passt, sollten wir das dann nicht gleich in die core.css übernehmen?

**Comment by frase-git** [comment]
> @ Alle
> Wenn das so passt, sollten wir das dann nicht gleich in die core.css übernehmen?

So wie es jetzt da steht, würde es ja auf **alle** Inputs wirken. Außer Radio und Check (warum eigentlich?).
Das könnte u.U. die Absichten des Templates stören.
Ich denke, mit solchen Aktionen sollten wir warten, bis wir den abgetrennten Admin-Modus haben und uns das dann nochmal genauer anschauen. Möglicherweise müsste das noch genauer spezifiziert (xhContainer) und/oder überhaupt nur im Admin-Template deklariert werden. (Vielleicht schenkt mir bis dahin jemand ein ausgedientes iGerät.) ;-)

**Comment by frase-git** [comment]
Übrigens:
Mit `appearance: none;` setzt man **alle Eigenschaften** zurück und muss/sollte diese dann anschließend neu (im gewollten Stil) deklarieren – sonst ist das Ergebnis auch unerwartet.

https://www.mediaevent.de/css/appearance.html

**Comment by olape-git** [comment]
> Wenn du etwas Zeit hast, schau dir mal die Template-Demo overlay_03 mit dem iPad 5 an und hier das [Mailformular](http://www.cmsimplexh.momadu.de/demos/overlay_03/?&mailform).

Mach ich

> Normalerweise sind da keine abgerundeten Ecken in den input-Feldern.

Ich weiß, aber hier ist es nicht so krass, damit kann man leben denke ich.

> Ich denke, mit solchen Aktionen sollten wir warten

Ich denke auch, das sollten wir jetzt nicht übers Knie brechen. Wenn wir erst mal die grobe "Fehler" fixen, ist das für die 1.7.6 erst mal ok.

**Comment by lck-git** [comment]
Danke. Interessant, sogar die textarea wird nicht verschont.

> Ich denke auch, das sollten wir jetzt nicht übers Knie brechen. Wenn wir erst mal die grobe "Fehler" fixen, ist das für die 1.7.6 erst mal ok.

Ok.

**Comment by frase-git** [comment]
Kleiner Hinweis:

![overlay_03-screenshot](https://user-images.githubusercontent.com/24246330/216402591-71b956ef-4c96-4d7c-ae5e-ee8683e5570d.png)

**Comment by lck-git** [comment]
Danke fürs melden!
Ähnliches Problem hast du mir [schon mal gemeldet](https://cmsimpleforum.com/viewtopic.php?f=13&t=18122#p83757). Das hab ich auch schon gefixt, aber nur lokal noch nicht online und im Download. :(

**Comment by lck-git** [comment]
> Das hab ich auch schon gefixt, aber nur lokal noch nicht online und im Download. :(

Erledigt, [Pull-Requests](https://github.com/cmsimple-xh/cmsimple-xh/pulls) erstellt.
