### ISSUE TITLE
Prevent text overflow in PD tab (select)

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#557]
If a page has an extremely long name, then the text in the select field may overflow:

![screen-overflow-select pd-tab](https://user-images.githubusercontent.com/24246330/160238214-08c7ebca-3924-47ae-a848-c2cf7da09555.png)

This should be prevented with a small addition in core.css.

https://github.com/cmsimple-xh/cmsimple-xh/blob/aefa8834c47df38c7bfd9f20aab9cead6505d682/assets/css/core.css#L535-L538

```
#xh_pdviews select {
	width: auto !important;
	max-width: 100%;
	padding: .125em !important;
	overflow: hidden;
	text-overflow: ellipsis;
}
```

**Comment by cmb69** [comment]
Thank you! Makes sense to me.
