### ISSUE TITLE
Backups - duplicated in Adminmenu

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#560]
Es gibt den Menüpunkt:
`Admin-Menü `→ `Einstellungen` → `Sicherheitskopien`

Unter
`Admin-Menü` → `Einstellungen`
... taucht aber der nahezu identische Inhalt unter der Überschrift "Sicherheitskopien" auch auf.
Ich denke, an dieser Stelle könnte das weg.

**Comment by cmb69** [comment]
> Ich denke, an dieser Stelle könnte das weg.

Ja und nein. Ich denke es ist wichtig, dass man dieses Feature auch ohne das Submenü erreichen kann (da gab es zumindest in der Vergangenheit bisweilen Problemchen), aber ein einfacher Link wie bei den anderen Punkten sollte genügen.

**Comment by frase-git** [comment]
> ... aber ein einfacher Link wie bei den anderen Punkten sollte genügen.

Genau, so meinte ich das auch.

**Comment by cmb69** [comment]
@olape-git, du hast das mit "wontfix" gelabelt; willst du damit sagen, dass wir alles so lassen sollen wie es jetzt ist?

**Comment by olape-git** [comment]
> @olape-git, du hast das mit "wontfix" gelabelt; willst du damit sagen, dass wir alles so lassen sollen wie es jetzt ist?

Nein, aber ich finde das jetzt nicht so wichtig, dass ich unbedingt darauf bestehen würde.

**Comment by cmb69** [comment]
> Nein, aber ich finde das jetzt nicht so wichtig, dass ich unbedingt darauf bestehen würde.

Warum dann nicht den Milestone entfernen, oder auf 1.8 ändern?

**Comment by olape-git** [comment]
Es ist ein vergleichsweise geringer Aufwand, aber wie gesagt, es muss jetzt nicht sein. Mich persönlich stört es nicht, wie es jetzt ist.
Ich denke nur, wenn wir zu viel auf die 1.8 schieben, wird es nachher auch wieder zu viel.

**Comment by cmb69** [comment]
> Es ist ein vergleichsweise geringer Aufwand, aber wie gesagt, es muss jetzt nicht sein.

Okay, verstehe, aber der Fix ist wirklich trivial, und wir sparen sogar eine Zeile Code. :)
