### ISSUE TITLE
deprecated since 1.8

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#604]
In der funtions.php gibt es einige Funktionen, die für die 1.8, teilweise schon für die 1.7 als deprecated vorgemerkt sind, bzw. die schon jetzt Warnung generieren.
Wie wollen wir hier verfahren?

Die Funktionen, die jetzt schon eine Warnung generieren, würde ich auf jeden Fall in die compat.php verschieben wollen.

Zu anderen:

- stsl() -> tut nichts
- tag() -> soll schon seit 1.7 weg
- XH_decodeJson() -> tut nicht mehr als json_decode()
- XH_encodeJson() -> tut nicht mehr als json_encode()
- XH_lastJsonError() -> tut nicht mehr als (bool) json_last_error()
- XH_renameFile() -> tut nicht mehr als rename()

Wollen wir hier der gedachten Empfehlung folgen?

**Comment by lck-git** [comment]
Die Funktionen stehen dann ja weiterhin zur Verfügung solange die Einbindung in der config.php nicht deaktiviert wird.
Wenn das keine negativen Auswirkungen hat, bin ich dafür.

**Comment by olape-git** [comment]
> Wenn das keine negativen Auswirkungen hat, bin ich dafür.



> * stsl() -> tut nichts
> 
> * tag() -> soll schon seit 1.7 weg
> 
> * XH_decodeJson() -> tut nicht mehr als json_decode()
> 
> * XH_encodeJson() -> tut nicht mehr als json_encode()
> 
> * XH_lastJsonError() -> tut nicht mehr als (bool) json_last_error()
> 
> * XH_renameFile() -> tut nicht mehr als rename()

Bei diesen Funktionen hätte es Auswirkungen. Zukünftig würden Warnungen angezeigt wenn debug aktiviert ist.
Allerdings, wenn das nicht passiert, dann ändert sich auch nichts.
