### ISSUE TITLE
Exclude plugins from the search if there is no searchable content. i.E. Shariff_XH

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#612]
https://cmsimpleforum.com/viewtopic.php?t=13241&start=30#p65629

**Comment by cmb69** [comment]
Argh, ich bin ein Trottel! Das globale Flag gibt es schon immer, nämlich den Query-Parameter `function=search`, und das kann einfach per `if ($function === "search")` (oder halt `if ($GLOBALS["function"] === "search")`) abgefragt werden.
