### ISSUE TITLE
Page_params: add date-time picker

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#67]
[Forum discussion](http://cmsimpleforum.com/viewtopic.php?f=16&t=7875)

**Comment by cmb69** [comment]
I suggest to merge PR #191.

**Comment by manu37** [comment]
I cannot follow exactly. Is the conversion from 1.6.x to 1.7 made by Exchange_XH?

**Comment by cmb69** [comment]
> Is the conversion from 1.6.x to 1.7 made by Exchange_XH?

Yes, it is supposed to. Basically, one has to install the plugin in the old version, export the contents, install the new XH version and Exchange_XH, and import the contents. A bit fiddly, but this way the details of the split marker are dealt with by CMSimple_XH automatically.
