### ISSUE TITLE
Replace bundled templates

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#68]
[Forum discussion](http://cmsimpleforum.com/viewtopic.php?t=7940&p=43131#p43118)

**Comment by cmb69** [comment]
I suggest to remove all current templates, and [as discussed elsewhere](https://github.com/TN03/XH_split/issues/24#issuecomment-289548008) to add three new templates:

* [lck_overlay_01](http://www.cmsimplexh.momadu.de/demos/lck_overlay_01/) by lck
* [richu171-split](http://richukunst.ch/?Webdesign:CMSimple_XH_Templates:richu171-split) by richukunst
* an overhaul of [fhs-simple-split](https://github.com/TN03/XH_split/tree/master/source/templates/fhs-simple-split) by frase which is work-in-progress

**Comment by manu37** [comment]
What about the [„fhs-anchorific-pure“](http://www.fhseidel.de/cmsxh/fhs-anchorific-pure/index.php?Das-Template) Template?

**Comment by frase-git** [comment]
> What about the „fhs-anchorific-pure“ Template?

Thats not fit for the new splitting method (!?).
