### ISSUE TITLE
Don't show generator=CMSimple_XH in HTML header

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#7]
See the [forum discussion](http://www.cmsimpleforum.com/viewtopic.php?f=10&t=9889).

**Comment by cmb69** [comment]
I've just added PR #11 which is one solution to this issue.

**Comment by Tata55** [comment]
What is the reason?

**Comment by cmb69** [comment]
Revealing the exact software (version) can be useful for potential attackers, who can target only certain version which are known to be vulnerable to a certain attack. Note that the PHP manual recommends to [turn off expose_php](http://php.net/manual/en/security.hiding.php) for security reasons.

**Comment by Tata55** [comment]
Got it.

Odoslané z iPhonu

Dňa 15. 6. 2017, o 0:16, Christoph M. Becker <notifications@github.com> napísal:
