### ISSUE TITLE
Highlight plugin calls

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#72]
[Forum discussion](http://cmsimpleforum.com/viewtopic.php?f=29&t=8322)

**Comment by cmb69** [comment]
I don't see an easy solution which wouldn't require at least minor changes to the editors, and considering that we're short of time, I suggest to postpone this decision to a later version.

**Comment by frase-git** [comment]
Issue kann geschlossen werden.
Seit XH 1.7.3 gibt es eine Init-Datei mit "plugincall".

**Comment by cmb69** [comment]
Ah, richtig!
