### ISSUE TITLE
Improve switching between edit and view mode of unpublished pages

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#81]
[Forum discussion](http://cmsimpleforum.com/viewtopic.php?f=10&t=8393)

**Comment by cmb69** [comment]
This seems not the most important feature, so for time reasons I suggest to postpone the decision to a later version.

**Comment by olape-git** [comment]
https://github.com/cmsimple-xh/cmsimple-xh/commit/8f763727027e5358e8d8c03123ad8be4de22bf2d
